
//automatically generated by Tuto
using uLearn;
namespace UXR 
{
    [Slide(@"Техника активного слушанья","02de1f50-c736-4b24-b81e-daf6aae19c0f")]
    public class Техника_активного_слушанья
        {
		//#video nlIWYjrs10k

        }
}