
//automatically generated by Tuto
using uLearn;
namespace UXR 
{
    [Slide(@"Пример персоны и сценария","38097062-3df2-41b6-90dd-91541f1e8964")]
    public class Пример_персоны_и_сценария
        {
		//#video dNxF3WwCrts

        }
}