
//automatically generated by Tuto
using uLearn;
namespace UXR 
{
    [Slide(@"Метод пассивного наблюдения","d495b697-fe64-4fd5-999b-feaa4a80a31b")]
    public class Метод_пассивного_наблюдения
        {
		//#video GvQIQ7ZnQBc

        }
}