
//automatically generated by Tuto
using uLearn;
namespace UXR 
{
    [Slide(@"Метод мыслей вслух","84ecb2e7-d5f1-40f1-9e66-25cc8bc94e6c")]
    public class Метод_мыслей_вслух
        {
		//#video O-LnuPeNFL0

        }
}