
//automatically generated by Tuto
using uLearn;
namespace UXR 
{
    [Slide(@"Пример отчета по итогам юзабилити-тестирования","55641e4e-cb65-4882-8ca7-034aa2fb7c10")]
    public class Пример_отчета_по_итогам_юзабилити_тестирования
        {
		//#video MCaN7sWsN_s

        }
}