// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace Database.Migrations
{
	[GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class AcceptedSolutionsIndex : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AcceptedSolutionsIndex));
        
        string IMigrationMetadata.Id
        {
            get { return "201502041429186_AcceptedSolutionsIndex"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
