// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace Database.Migrations
{
	[GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddManualQuizChecks : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddManualQuizChecks));
        
        string IMigrationMetadata.Id
        {
            get { return "201605310936533_AddManualQuizChecks"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
