
//automatically generated by Tuto
using uLearn;
namespace AIML 
{
    [Slide(@"Функция XOR и многослойный персептрон","cf092683-403d-4610-ba1f-bc01206a848f")]
    public class Функция_XOR_и_многослойный_персептрон
        {
		//#video IEVYDZkEBpY
		/*
		[Презентация](_S050.pdf)
		*/

        }
}