
//automatically generated by Tuto
using uLearn;
namespace AIML 
{
    [Slide(@"Нейронная сеть как функция действительных переменных","d95c09c5-3407-47ae-89a8-7a45aed3be80")]
    public class Нейронная_сеть_как_функция_действительных_переменных
        {
		//#video cbbn2fH5b6A
		/*
		[Презентация](_S010.pdf)
		*/

        }
}