
//automatically generated by Tuto
using uLearn;
namespace AIML 
{
    [Slide(@"Заключение","1672234e-7ab4-47a5-8149-2e8c5f544855")]
    public class Заключение
        {
		//#video LvfKJj8k4Co

        }
}