// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace Database.Migrations
{
	[GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class Cascading : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Cascading));
        
        string IMigrationMetadata.Id
        {
            get { return "201408260518531_Cascading"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
