namespace Database.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class CourseIdLength100 : DbMigration
    {
        public override void Up()
        {
            DropIndex("dbo.AdditionalScores", "IDX_AdditionalScore_ByCourseAndUser");
            DropIndex("dbo.AdditionalScores", "IDX_AdditionalScore_ByCourseUnitScoringGroupAndUser");
            DropIndex("dbo.AutomaticExerciseCheckings", "IDX_AbstractSlideChecking_AbstractSlideCheckingByCourseAndUser");
            DropIndex("dbo.AutomaticExerciseCheckings", "IDX_AbstractSlideChecking_AbstractSlideCheckingBySlide");
            DropIndex("dbo.AutomaticExerciseCheckings", "IDX_AbstractSlideChecking_AbstractSlideCheckingBySlideAndTime");
            DropIndex("dbo.AutomaticExerciseCheckings", "IDX_AbstractSlideChecking_AbstractSlideCheckingBySlideAndUser");
            DropIndex("dbo.AutomaticQuizCheckings", "IDX_AbstractSlideChecking_AbstractSlideCheckingByCourseAndUser");
            DropIndex("dbo.AutomaticQuizCheckings", "IDX_AbstractSlideChecking_AbstractSlideCheckingBySlide");
            DropIndex("dbo.AutomaticQuizCheckings", "IDX_AbstractSlideChecking_AbstractSlideCheckingBySlideAndTime");
            DropIndex("dbo.AutomaticQuizCheckings", "IDX_AbstractSlideChecking_AbstractSlideCheckingBySlideAndUser");
            DropIndex("dbo.UserQuizSubmissions", "IDX_UserQuizSubmission_BySlideAndUser");
            DropIndex("dbo.UserQuizSubmissions", "IDX_UserQuizSubmission_ByCourseAndSlide");
            DropIndex("dbo.UserQuizSubmissions", "IDX_UserQuizSubmission_BySlideAndTime");
            DropIndex("dbo.ManualQuizCheckings", "IDX_AbstractSlideChecking_AbstractSlideCheckingByCourseAndUser");
            DropIndex("dbo.ManualQuizCheckings", "IDX_AbstractSlideChecking_AbstractSlideCheckingBySlide");
            DropIndex("dbo.ManualQuizCheckings", "IDX_AbstractSlideChecking_AbstractSlideCheckingBySlideAndTime");
            DropIndex("dbo.ManualQuizCheckings", "IDX_AbstractSlideChecking_AbstractSlideCheckingBySlideAndUser");
            DropIndex("dbo.CertificateTemplates", "IDX_CertificateTemplate_ByCourse");
            DropIndex("dbo.CourseAccesses", "IDX_CourseAccess_ByCourse");
            DropIndex("dbo.CourseAccesses", "IDX_CourseAccess_ByCourseAndIsEnabled");
            DropIndex("dbo.CourseAccesses", "IDX_CourseAccess_ByCourseUserAndIsEnabled");
            DropIndex("dbo.CourseVersions", "IDX_CourseVersion_ByCourseAndLoadingTime");
            DropIndex("dbo.CourseVersions", "IDX_CourseVersion_ByCourseAndPublishTime");
            DropIndex("dbo.Groups", "IDX_Group_GroupByCourse");
            DropIndex("dbo.ManualExerciseCheckings", "IDX_AbstractSlideChecking_AbstractSlideCheckingBySlideAndUser");
            DropIndex("dbo.ManualExerciseCheckings", "IDX_AbstractSlideChecking_AbstractSlideCheckingByCourseAndUser");
            DropIndex("dbo.ManualExerciseCheckings", "IDX_AbstractSlideChecking_AbstractSlideCheckingBySlide");
            DropIndex("dbo.ManualExerciseCheckings", "IDX_AbstractSlideChecking_AbstractSlideCheckingBySlideAndTime");
            DropIndex("dbo.UserExerciseSubmissions", "IDX_UserExerciseSubmissions_BySlideAndUser");
            DropIndex("dbo.UserExerciseSubmissions", "IDX_UserExerciseSubmissions_ByCourseAndIsRightAnswer");
            DropIndex("dbo.UserExerciseSubmissions", "IDX_UserExerciseSubmissions_ByCourseAndSlide");
            DropIndex("dbo.UserExerciseSubmissions", "IDX_UserExerciseSubmissions_BySlideAndIsRightAnswer");
            DropIndex("dbo.UserExerciseSubmissions", "IDX_UserExerciseSubmissions_BySlideAndTime");
            DropIndex("dbo.SlideHints", "FullIndex");
            DropIndex("dbo.LastVisits", "IDX_LastVisits_ByCourseAndUser");
            DropIndex("dbo.UnitAppearances", "CourseAndTime");
            DropIndex("dbo.UserFlashcardsVisits", "IDX_UserFlashcardsVisits_ByUserIdAndCourseIdAndUnitIdAndFlashcardId");
            DropIndex("dbo.Visits", "IDX_Visits_ByCourseSlideAndUser");
            DropPrimaryKey("dbo.CommentsPolicies");
            DropPrimaryKey("dbo.TempCourseErrors");
            DropPrimaryKey("dbo.TempCourses");
            AlterColumn("dbo.AdditionalScores", "CourseId", c => c.String(nullable: false, maxLength: 100));
            AlterColumn("dbo.UserQuestions", "CourseId", c => c.String(maxLength: 100));
            AlterColumn("dbo.AutomaticExerciseCheckings", "CourseId", c => c.String(nullable: false, maxLength: 100));
            AlterColumn("dbo.AutomaticQuizCheckings", "CourseId", c => c.String(nullable: false, maxLength: 100));
            AlterColumn("dbo.UserQuizSubmissions", "CourseId", c => c.String(nullable: false, maxLength: 100));
            AlterColumn("dbo.ManualQuizCheckings", "CourseId", c => c.String(nullable: false, maxLength: 100));
            AlterColumn("dbo.CertificateTemplates", "CourseId", c => c.String(nullable: false, maxLength: 100));
            AlterColumn("dbo.Comments", "CourseId", c => c.String(nullable: false, maxLength: 100));
            AlterColumn("dbo.CommentsPolicies", "CourseId", c => c.String(nullable: false, maxLength: 100));
            AlterColumn("dbo.CourseAccesses", "CourseId", c => c.String(nullable: false, maxLength: 100));
            AlterColumn("dbo.CourseFiles", "CourseId", c => c.String(nullable: false, maxLength: 100));
            AlterColumn("dbo.CourseVersions", "CourseId", c => c.String(nullable: false, maxLength: 100));
            AlterColumn("dbo.CourseGitRepos", "CourseId", c => c.String(maxLength: 100));
            AlterColumn("dbo.Groups", "CourseId", c => c.String(nullable: false, maxLength: 100));
            AlterColumn("dbo.ManualExerciseCheckings", "CourseId", c => c.String(nullable: false, maxLength: 100));
            AlterColumn("dbo.UserExerciseSubmissions", "CourseId", c => c.String(nullable: false, maxLength: 100));
            AlterColumn("dbo.GraderClients", "CourseId", c => c.String(nullable: false, maxLength: 100));
            AlterColumn("dbo.SlideHints", "CourseId", c => c.String(nullable: false, maxLength: 100));
            AlterColumn("dbo.LastVisits", "CourseId", c => c.String(nullable: false, maxLength: 100));
            AlterColumn("dbo.SlideRates", "CourseId", c => c.String(nullable: false, maxLength: 100));
            AlterColumn("dbo.TempCourseErrors", "CourseId", c => c.String(nullable: false, maxLength: 100));
            AlterColumn("dbo.TempCourses", "CourseId", c => c.String(nullable: false, maxLength: 100));
            AlterColumn("dbo.UnitAppearances", "CourseId", c => c.String(nullable: false, maxLength: 100));
            AlterColumn("dbo.UserFlashcardsVisits", "CourseId", c => c.String(nullable: false, maxLength: 100));
            AlterColumn("dbo.Visits", "CourseId", c => c.String(nullable: false, maxLength: 100));
            AddPrimaryKey("dbo.CommentsPolicies", "CourseId");
            AddPrimaryKey("dbo.TempCourseErrors", "CourseId");
            AddPrimaryKey("dbo.TempCourses", "CourseId");
            CreateIndex("dbo.AdditionalScores", new[] { "CourseId", "UserId" }, name: "IDX_AdditionalScore_ByCourseAndUser");
            CreateIndex("dbo.AdditionalScores", new[] { "CourseId", "UnitId", "ScoringGroupId", "UserId" }, unique: true, name: "IDX_AdditionalScore_ByCourseUnitScoringGroupAndUser");
            CreateIndex("dbo.AutomaticExerciseCheckings", new[] { "CourseId", "UserId" }, name: "IDX_AbstractSlideChecking_AbstractSlideCheckingByCourseAndUser");
            CreateIndex("dbo.AutomaticExerciseCheckings", new[] { "CourseId", "SlideId" }, name: "IDX_AbstractSlideChecking_AbstractSlideCheckingBySlide");
            CreateIndex("dbo.AutomaticExerciseCheckings", new[] { "CourseId", "SlideId", "Timestamp" }, name: "IDX_AbstractSlideChecking_AbstractSlideCheckingBySlideAndTime");
            CreateIndex("dbo.AutomaticExerciseCheckings", new[] { "CourseId", "SlideId", "UserId" }, name: "IDX_AbstractSlideChecking_AbstractSlideCheckingBySlideAndUser");
            CreateIndex("dbo.AutomaticQuizCheckings", new[] { "CourseId", "UserId" }, name: "IDX_AbstractSlideChecking_AbstractSlideCheckingByCourseAndUser");
            CreateIndex("dbo.AutomaticQuizCheckings", new[] { "CourseId", "SlideId" }, name: "IDX_AbstractSlideChecking_AbstractSlideCheckingBySlide");
            CreateIndex("dbo.AutomaticQuizCheckings", new[] { "CourseId", "SlideId", "Timestamp" }, name: "IDX_AbstractSlideChecking_AbstractSlideCheckingBySlideAndTime");
            CreateIndex("dbo.AutomaticQuizCheckings", new[] { "CourseId", "SlideId", "UserId" }, name: "IDX_AbstractSlideChecking_AbstractSlideCheckingBySlideAndUser");
            CreateIndex("dbo.UserQuizSubmissions", new[] { "CourseId", "SlideId", "UserId" }, name: "IDX_UserQuizSubmission_BySlideAndUser");
            CreateIndex("dbo.UserQuizSubmissions", new[] { "CourseId", "SlideId" }, name: "IDX_UserQuizSubmission_ByCourseAndSlide");
            CreateIndex("dbo.UserQuizSubmissions", new[] { "CourseId", "SlideId", "Timestamp" }, name: "IDX_UserQuizSubmission_BySlideAndTime");
            CreateIndex("dbo.ManualQuizCheckings", new[] { "CourseId", "UserId" }, name: "IDX_AbstractSlideChecking_AbstractSlideCheckingByCourseAndUser");
            CreateIndex("dbo.ManualQuizCheckings", new[] { "CourseId", "SlideId" }, name: "IDX_AbstractSlideChecking_AbstractSlideCheckingBySlide");
            CreateIndex("dbo.ManualQuizCheckings", new[] { "CourseId", "SlideId", "Timestamp" }, name: "IDX_AbstractSlideChecking_AbstractSlideCheckingBySlideAndTime");
            CreateIndex("dbo.ManualQuizCheckings", new[] { "CourseId", "SlideId", "UserId" }, name: "IDX_AbstractSlideChecking_AbstractSlideCheckingBySlideAndUser");
            CreateIndex("dbo.CertificateTemplates", "CourseId", name: "IDX_CertificateTemplate_ByCourse");
            CreateIndex("dbo.CourseAccesses", "CourseId", name: "IDX_CourseAccess_ByCourse");
            CreateIndex("dbo.CourseAccesses", new[] { "CourseId", "IsEnabled" }, name: "IDX_CourseAccess_ByCourseAndIsEnabled");
            CreateIndex("dbo.CourseAccesses", new[] { "CourseId", "UserId", "IsEnabled" }, name: "IDX_CourseAccess_ByCourseUserAndIsEnabled");
            CreateIndex("dbo.CourseVersions", new[] { "CourseId", "LoadingTime" }, name: "IDX_CourseVersion_ByCourseAndLoadingTime");
            CreateIndex("dbo.CourseVersions", new[] { "CourseId", "PublishTime" }, name: "IDX_CourseVersion_ByCourseAndPublishTime");
            CreateIndex("dbo.Groups", "CourseId", name: "IDX_Group_GroupByCourse");
            CreateIndex("dbo.ManualExerciseCheckings", new[] { "CourseId", "SlideId", "UserId", "ProhibitFurtherManualCheckings" }, name: "IDX_AbstractSlideChecking_AbstractSlideCheckingBySlideAndUser");
            CreateIndex("dbo.ManualExerciseCheckings", new[] { "CourseId", "UserId" }, name: "IDX_AbstractSlideChecking_AbstractSlideCheckingByCourseAndUser");
            CreateIndex("dbo.ManualExerciseCheckings", new[] { "CourseId", "SlideId" }, name: "IDX_AbstractSlideChecking_AbstractSlideCheckingBySlide");
            CreateIndex("dbo.ManualExerciseCheckings", new[] { "CourseId", "SlideId", "Timestamp" }, name: "IDX_AbstractSlideChecking_AbstractSlideCheckingBySlideAndTime");
            CreateIndex("dbo.UserExerciseSubmissions", new[] { "CourseId", "SlideId", "UserId" }, name: "IDX_UserExerciseSubmissions_BySlideAndUser");
            CreateIndex("dbo.UserExerciseSubmissions", new[] { "CourseId", "AutomaticCheckingIsRightAnswer" }, name: "IDX_UserExerciseSubmissions_ByCourseAndIsRightAnswer");
            CreateIndex("dbo.UserExerciseSubmissions", new[] { "CourseId", "SlideId" }, name: "IDX_UserExerciseSubmissions_ByCourseAndSlide");
            CreateIndex("dbo.UserExerciseSubmissions", new[] { "CourseId", "SlideId", "AutomaticCheckingIsRightAnswer" }, name: "IDX_UserExerciseSubmissions_BySlideAndIsRightAnswer");
            CreateIndex("dbo.UserExerciseSubmissions", new[] { "CourseId", "SlideId", "Timestamp" }, name: "IDX_UserExerciseSubmissions_BySlideAndTime");
            CreateIndex("dbo.SlideHints", new[] { "CourseId", "SlideId", "UserId", "HintId", "IsHintHelped" }, name: "FullIndex");
            CreateIndex("dbo.LastVisits", new[] { "CourseId", "UserId" }, name: "IDX_LastVisits_ByCourseAndUser");
            CreateIndex("dbo.UnitAppearances", new[] { "CourseId", "PublishTime" }, name: "CourseAndTime");
            CreateIndex("dbo.UserFlashcardsVisits", new[] { "UserId", "CourseId", "UnitId", "FlashcardId" }, name: "IDX_UserFlashcardsVisits_ByUserIdAndCourseIdAndUnitIdAndFlashcardId");
            CreateIndex("dbo.Visits", new[] { "CourseId", "SlideId", "UserId" }, name: "IDX_Visits_ByCourseSlideAndUser");
        }
        
        public override void Down()
        {
            DropIndex("dbo.Visits", "IDX_Visits_ByCourseSlideAndUser");
            DropIndex("dbo.UserFlashcardsVisits", "IDX_UserFlashcardsVisits_ByUserIdAndCourseIdAndUnitIdAndFlashcardId");
            DropIndex("dbo.UnitAppearances", "CourseAndTime");
            DropIndex("dbo.LastVisits", "IDX_LastVisits_ByCourseAndUser");
            DropIndex("dbo.SlideHints", "FullIndex");
            DropIndex("dbo.UserExerciseSubmissions", "IDX_UserExerciseSubmissions_BySlideAndTime");
            DropIndex("dbo.UserExerciseSubmissions", "IDX_UserExerciseSubmissions_BySlideAndIsRightAnswer");
            DropIndex("dbo.UserExerciseSubmissions", "IDX_UserExerciseSubmissions_ByCourseAndSlide");
            DropIndex("dbo.UserExerciseSubmissions", "IDX_UserExerciseSubmissions_ByCourseAndIsRightAnswer");
            DropIndex("dbo.UserExerciseSubmissions", "IDX_UserExerciseSubmissions_BySlideAndUser");
            DropIndex("dbo.ManualExerciseCheckings", "IDX_AbstractSlideChecking_AbstractSlideCheckingBySlideAndTime");
            DropIndex("dbo.ManualExerciseCheckings", "IDX_AbstractSlideChecking_AbstractSlideCheckingBySlide");
            DropIndex("dbo.ManualExerciseCheckings", "IDX_AbstractSlideChecking_AbstractSlideCheckingByCourseAndUser");
            DropIndex("dbo.ManualExerciseCheckings", "IDX_AbstractSlideChecking_AbstractSlideCheckingBySlideAndUser");
            DropIndex("dbo.Groups", "IDX_Group_GroupByCourse");
            DropIndex("dbo.CourseVersions", "IDX_CourseVersion_ByCourseAndPublishTime");
            DropIndex("dbo.CourseVersions", "IDX_CourseVersion_ByCourseAndLoadingTime");
            DropIndex("dbo.CourseAccesses", "IDX_CourseAccess_ByCourseUserAndIsEnabled");
            DropIndex("dbo.CourseAccesses", "IDX_CourseAccess_ByCourseAndIsEnabled");
            DropIndex("dbo.CourseAccesses", "IDX_CourseAccess_ByCourse");
            DropIndex("dbo.CertificateTemplates", "IDX_CertificateTemplate_ByCourse");
            DropIndex("dbo.ManualQuizCheckings", "IDX_AbstractSlideChecking_AbstractSlideCheckingBySlideAndUser");
            DropIndex("dbo.ManualQuizCheckings", "IDX_AbstractSlideChecking_AbstractSlideCheckingBySlideAndTime");
            DropIndex("dbo.ManualQuizCheckings", "IDX_AbstractSlideChecking_AbstractSlideCheckingBySlide");
            DropIndex("dbo.ManualQuizCheckings", "IDX_AbstractSlideChecking_AbstractSlideCheckingByCourseAndUser");
            DropIndex("dbo.UserQuizSubmissions", "IDX_UserQuizSubmission_BySlideAndTime");
            DropIndex("dbo.UserQuizSubmissions", "IDX_UserQuizSubmission_ByCourseAndSlide");
            DropIndex("dbo.UserQuizSubmissions", "IDX_UserQuizSubmission_BySlideAndUser");
            DropIndex("dbo.AutomaticQuizCheckings", "IDX_AbstractSlideChecking_AbstractSlideCheckingBySlideAndUser");
            DropIndex("dbo.AutomaticQuizCheckings", "IDX_AbstractSlideChecking_AbstractSlideCheckingBySlideAndTime");
            DropIndex("dbo.AutomaticQuizCheckings", "IDX_AbstractSlideChecking_AbstractSlideCheckingBySlide");
            DropIndex("dbo.AutomaticQuizCheckings", "IDX_AbstractSlideChecking_AbstractSlideCheckingByCourseAndUser");
            DropIndex("dbo.AutomaticExerciseCheckings", "IDX_AbstractSlideChecking_AbstractSlideCheckingBySlideAndUser");
            DropIndex("dbo.AutomaticExerciseCheckings", "IDX_AbstractSlideChecking_AbstractSlideCheckingBySlideAndTime");
            DropIndex("dbo.AutomaticExerciseCheckings", "IDX_AbstractSlideChecking_AbstractSlideCheckingBySlide");
            DropIndex("dbo.AutomaticExerciseCheckings", "IDX_AbstractSlideChecking_AbstractSlideCheckingByCourseAndUser");
            DropIndex("dbo.AdditionalScores", "IDX_AdditionalScore_ByCourseUnitScoringGroupAndUser");
            DropIndex("dbo.AdditionalScores", "IDX_AdditionalScore_ByCourseAndUser");
            DropPrimaryKey("dbo.TempCourses");
            DropPrimaryKey("dbo.TempCourseErrors");
            DropPrimaryKey("dbo.CommentsPolicies");
            AlterColumn("dbo.Visits", "CourseId", c => c.String(nullable: false, maxLength: 64));
            AlterColumn("dbo.UserFlashcardsVisits", "CourseId", c => c.String(nullable: false, maxLength: 64));
            AlterColumn("dbo.UnitAppearances", "CourseId", c => c.String(nullable: false, maxLength: 64));
            AlterColumn("dbo.TempCourses", "CourseId", c => c.String(nullable: false, maxLength: 64));
            AlterColumn("dbo.TempCourseErrors", "CourseId", c => c.String(nullable: false, maxLength: 64));
            AlterColumn("dbo.SlideRates", "CourseId", c => c.String(nullable: false, maxLength: 64));
            AlterColumn("dbo.LastVisits", "CourseId", c => c.String(nullable: false, maxLength: 64));
            AlterColumn("dbo.SlideHints", "CourseId", c => c.String(nullable: false, maxLength: 64));
            AlterColumn("dbo.GraderClients", "CourseId", c => c.String(nullable: false, maxLength: 64));
            AlterColumn("dbo.UserExerciseSubmissions", "CourseId", c => c.String(nullable: false, maxLength: 40));
            AlterColumn("dbo.ManualExerciseCheckings", "CourseId", c => c.String(nullable: false, maxLength: 64));
            AlterColumn("dbo.Groups", "CourseId", c => c.String(nullable: false, maxLength: 64));
            AlterColumn("dbo.CourseGitRepos", "CourseId", c => c.String(maxLength: 64));
            AlterColumn("dbo.CourseVersions", "CourseId", c => c.String(nullable: false, maxLength: 64));
            AlterColumn("dbo.CourseFiles", "CourseId", c => c.String(nullable: false, maxLength: 64));
            AlterColumn("dbo.CourseAccesses", "CourseId", c => c.String(nullable: false, maxLength: 64));
            AlterColumn("dbo.CommentsPolicies", "CourseId", c => c.String(nullable: false, maxLength: 64));
            AlterColumn("dbo.Comments", "CourseId", c => c.String(nullable: false, maxLength: 64));
            AlterColumn("dbo.CertificateTemplates", "CourseId", c => c.String(nullable: false, maxLength: 40));
            AlterColumn("dbo.ManualQuizCheckings", "CourseId", c => c.String(nullable: false, maxLength: 64));
            AlterColumn("dbo.UserQuizSubmissions", "CourseId", c => c.String(nullable: false, maxLength: 40));
            AlterColumn("dbo.AutomaticQuizCheckings", "CourseId", c => c.String(nullable: false, maxLength: 64));
            AlterColumn("dbo.AutomaticExerciseCheckings", "CourseId", c => c.String(nullable: false, maxLength: 64));
            AlterColumn("dbo.UserQuestions", "CourseId", c => c.String(maxLength: 64));
            AlterColumn("dbo.AdditionalScores", "CourseId", c => c.String(nullable: false, maxLength: 64));
            AddPrimaryKey("dbo.TempCourses", "CourseId");
            AddPrimaryKey("dbo.TempCourseErrors", "CourseId");
            AddPrimaryKey("dbo.CommentsPolicies", "CourseId");
            CreateIndex("dbo.Visits", new[] { "CourseId", "SlideId", "UserId" }, name: "IDX_Visits_ByCourseSlideAndUser");
            CreateIndex("dbo.UserFlashcardsVisits", new[] { "UserId", "CourseId", "UnitId", "FlashcardId" }, name: "IDX_UserFlashcardsVisits_ByUserIdAndCourseIdAndUnitIdAndFlashcardId");
            CreateIndex("dbo.UnitAppearances", new[] { "CourseId", "PublishTime" }, name: "CourseAndTime");
            CreateIndex("dbo.LastVisits", new[] { "CourseId", "UserId" }, name: "IDX_LastVisits_ByCourseAndUser");
            CreateIndex("dbo.SlideHints", new[] { "CourseId", "SlideId", "UserId", "HintId", "IsHintHelped" }, name: "FullIndex");
            CreateIndex("dbo.UserExerciseSubmissions", new[] { "CourseId", "SlideId", "Timestamp" }, name: "IDX_UserExerciseSubmissions_BySlideAndTime");
            CreateIndex("dbo.UserExerciseSubmissions", new[] { "CourseId", "SlideId", "AutomaticCheckingIsRightAnswer" }, name: "IDX_UserExerciseSubmissions_BySlideAndIsRightAnswer");
            CreateIndex("dbo.UserExerciseSubmissions", new[] { "CourseId", "SlideId" }, name: "IDX_UserExerciseSubmissions_ByCourseAndSlide");
            CreateIndex("dbo.UserExerciseSubmissions", new[] { "CourseId", "AutomaticCheckingIsRightAnswer" }, name: "IDX_UserExerciseSubmissions_ByCourseAndIsRightAnswer");
            CreateIndex("dbo.UserExerciseSubmissions", new[] { "CourseId", "SlideId", "UserId" }, name: "IDX_UserExerciseSubmissions_BySlideAndUser");
            CreateIndex("dbo.ManualExerciseCheckings", new[] { "CourseId", "SlideId", "Timestamp" }, name: "IDX_AbstractSlideChecking_AbstractSlideCheckingBySlideAndTime");
            CreateIndex("dbo.ManualExerciseCheckings", new[] { "CourseId", "SlideId" }, name: "IDX_AbstractSlideChecking_AbstractSlideCheckingBySlide");
            CreateIndex("dbo.ManualExerciseCheckings", new[] { "CourseId", "UserId" }, name: "IDX_AbstractSlideChecking_AbstractSlideCheckingByCourseAndUser");
            CreateIndex("dbo.ManualExerciseCheckings", new[] { "CourseId", "SlideId", "UserId", "ProhibitFurtherManualCheckings" }, name: "IDX_AbstractSlideChecking_AbstractSlideCheckingBySlideAndUser");
            CreateIndex("dbo.Groups", "CourseId", name: "IDX_Group_GroupByCourse");
            CreateIndex("dbo.CourseVersions", new[] { "CourseId", "PublishTime" }, name: "IDX_CourseVersion_ByCourseAndPublishTime");
            CreateIndex("dbo.CourseVersions", new[] { "CourseId", "LoadingTime" }, name: "IDX_CourseVersion_ByCourseAndLoadingTime");
            CreateIndex("dbo.CourseAccesses", new[] { "CourseId", "UserId", "IsEnabled" }, name: "IDX_CourseAccess_ByCourseUserAndIsEnabled");
            CreateIndex("dbo.CourseAccesses", new[] { "CourseId", "IsEnabled" }, name: "IDX_CourseAccess_ByCourseAndIsEnabled");
            CreateIndex("dbo.CourseAccesses", "CourseId", name: "IDX_CourseAccess_ByCourse");
            CreateIndex("dbo.CertificateTemplates", "CourseId", name: "IDX_CertificateTemplate_ByCourse");
            CreateIndex("dbo.ManualQuizCheckings", new[] { "CourseId", "SlideId", "UserId" }, name: "IDX_AbstractSlideChecking_AbstractSlideCheckingBySlideAndUser");
            CreateIndex("dbo.ManualQuizCheckings", new[] { "CourseId", "SlideId", "Timestamp" }, name: "IDX_AbstractSlideChecking_AbstractSlideCheckingBySlideAndTime");
            CreateIndex("dbo.ManualQuizCheckings", new[] { "CourseId", "SlideId" }, name: "IDX_AbstractSlideChecking_AbstractSlideCheckingBySlide");
            CreateIndex("dbo.ManualQuizCheckings", new[] { "CourseId", "UserId" }, name: "IDX_AbstractSlideChecking_AbstractSlideCheckingByCourseAndUser");
            CreateIndex("dbo.UserQuizSubmissions", new[] { "CourseId", "SlideId", "Timestamp" }, name: "IDX_UserQuizSubmission_BySlideAndTime");
            CreateIndex("dbo.UserQuizSubmissions", new[] { "CourseId", "SlideId" }, name: "IDX_UserQuizSubmission_ByCourseAndSlide");
            CreateIndex("dbo.UserQuizSubmissions", new[] { "CourseId", "SlideId", "UserId" }, name: "IDX_UserQuizSubmission_BySlideAndUser");
            CreateIndex("dbo.AutomaticQuizCheckings", new[] { "CourseId", "SlideId", "UserId" }, name: "IDX_AbstractSlideChecking_AbstractSlideCheckingBySlideAndUser");
            CreateIndex("dbo.AutomaticQuizCheckings", new[] { "CourseId", "SlideId", "Timestamp" }, name: "IDX_AbstractSlideChecking_AbstractSlideCheckingBySlideAndTime");
            CreateIndex("dbo.AutomaticQuizCheckings", new[] { "CourseId", "SlideId" }, name: "IDX_AbstractSlideChecking_AbstractSlideCheckingBySlide");
            CreateIndex("dbo.AutomaticQuizCheckings", new[] { "CourseId", "UserId" }, name: "IDX_AbstractSlideChecking_AbstractSlideCheckingByCourseAndUser");
            CreateIndex("dbo.AutomaticExerciseCheckings", new[] { "CourseId", "SlideId", "UserId" }, name: "IDX_AbstractSlideChecking_AbstractSlideCheckingBySlideAndUser");
            CreateIndex("dbo.AutomaticExerciseCheckings", new[] { "CourseId", "SlideId", "Timestamp" }, name: "IDX_AbstractSlideChecking_AbstractSlideCheckingBySlideAndTime");
            CreateIndex("dbo.AutomaticExerciseCheckings", new[] { "CourseId", "SlideId" }, name: "IDX_AbstractSlideChecking_AbstractSlideCheckingBySlide");
            CreateIndex("dbo.AutomaticExerciseCheckings", new[] { "CourseId", "UserId" }, name: "IDX_AbstractSlideChecking_AbstractSlideCheckingByCourseAndUser");
            CreateIndex("dbo.AdditionalScores", new[] { "CourseId", "UnitId", "ScoringGroupId", "UserId" }, unique: true, name: "IDX_AdditionalScore_ByCourseUnitScoringGroupAndUser");
            CreateIndex("dbo.AdditionalScores", new[] { "CourseId", "UserId" }, name: "IDX_AdditionalScore_ByCourseAndUser");
        }
    }
}
