// <auto-generated />
namespace Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class AutomaticExerciseCheckingPoints : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AutomaticExerciseCheckingPoints));
        
        string IMigrationMetadata.Id
        {
            get { return "202002120803203_AutomaticExerciseCheckingPoints"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
