export default {
	allTestPassed: 'Все тесты пройдены',
	allTestPassedNoReview: 'Все тесты пройдены, задача сдана',
	allTestPassedPendingReview: 'Все тесты пройдены, решение ожидает код-ревью',
	allTestPassedWasReviewed: 'Все тесты пройдены, решение прошло код-ревью',
	allTestPassedProhibitFurtherReview: 'Все тесты пройдены, по этой задаче код-ревью больше не проводится',
	noTestsPendingReview: 'Решение ожидает код-ревью',
	noTestsWasReviewed: 'Решение прошло код-ревью',
	noTestsProhibitFurtherReview: 'По этой задаче код-ревью больше не проводится',
	notCheckedAtAll: 'Эта задача проверяется только вручную преподавателем, но вы не принадлежите к студенческой группе',
	running: 'Решение проверяется',
	waiting: 'Решение ждет своей очереди на проверку',
	wrongAnswer: 'Тесты не пройдены',
	compilationError: 'Ошибка компиляции',
	runtimeError: 'Ошибка времени выполнения',
	serverError: 'Ошибка сервера',
	serverMessage: 'Сообщение от сервера',
	waitingTimeLimitExceeded: 'Серверу не удалось проверить решение',
}
