export default {
	allTestPassed: 'Все тесты пройдены',
	allTestPassedNoReview: 'Все тесты пройдены, задача сдана',
	allTestPassedPendingReview: 'Все тесты пройдены, решение ожидает код-ревью',
	allTestPassedWasReviewed: 'Все тесты пройдены, решение прошло код-ревью',
	allTestPassedProhibitFurtherReview: 'Все тесты пройдены, по этой задаче код-ревью больше не проводится',
	noTestsPendingReview: 'Решение ожидает код-ревью',
	noTestsWasReviewed: 'Решение прошло код-ревью',
	noTestsProhibitFurtherReview: 'По этой задаче код-ревью больше не проводится',
	running: 'Решение проверяется',
	waiting: 'Решение ждет своей очереди на проверку',
	wrongAnswer: 'Результат проверки: Тесты не пройдены',
	compilationError: 'Результат проверки: Ошибка компиляции',
	serverError: 'Ошибка сервера',
	serverMessage: 'Сообщение от сервера',
	waitingTimeLimitExceeded: 'Серверу не удалось проверить решение',
}
