
//automatically generated by Tuto
using uLearn;
namespace AIML 
{
    [Slide(@"Логическое программирование","a88f234b-87e7-4d0e-8538-d91d038e7564")]
    public class Логическое_программирование
        {
		//#video SPs_VCw69lQ
		/*
		[Презентация](_S07-slides.pdf)
		*/

        }
}