
//automatically generated by Tuto
using uLearn;
namespace AIML 
{
    [Slide(@"Нечеткий вывод","01cb1668-bb02-4e7a-ade1-7a884163a2ee")]
    public class Нечеткий_вывод
        {
		//#video c3xGGS1yjD4
		/*
		[Презентация](_S00-slides.pdf)
		*/

        }
}