--
-- PostgreSQL database dump
--

-- Dumped from database version 13.2
-- Dumped by pg_dump version 13.2

-- Started on 2021-03-17 17:27:30

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 6 (class 2615 OID 57071)
-- Name: antiplagiarism; Type: SCHEMA; Schema: -; Owner: ulearn
--

CREATE SCHEMA antiplagiarism;


ALTER SCHEMA antiplagiarism OWNER TO ulearn;

--
-- TOC entry 3016 (class 3456 OID 57230)
-- Name: case_insensitive; Type: COLLATION; Schema: public; Owner: ulearn
--

CREATE COLLATION public.case_insensitive (provider = icu, deterministic = false, locale = 'und@colStrength=secondary');


ALTER COLLATION public.case_insensitive OWNER TO ulearn;

--
-- TOC entry 3 (class 3079 OID 56986)
-- Name: pg_trgm; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS pg_trgm WITH SCHEMA public;


--
-- TOC entry 3973 (class 0 OID 0)
-- Dependencies: 3
-- Name: EXTENSION pg_trgm; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION pg_trgm IS 'text similarity measurement and index searching based on trigrams';


--
-- TOC entry 2 (class 3079 OID 56975)
-- Name: uuid-ossp; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA public;


--
-- TOC entry 3974 (class 0 OID 0)
-- Dependencies: 2
-- Name: EXTENSION "uuid-ossp"; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION "uuid-ossp" IS 'generate universally unique identifiers (UUIDs)';


--
-- TOC entry 377 (class 1255 OID 57065)
-- Name: immutable_concat_ws(text, text[]); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE FUNCTION public.immutable_concat_ws(text, VARIADIC text[]) RETURNS text
    LANGUAGE internal IMMUTABLE PARALLEL SAFE
    AS $$text_concat_ws$$;


ALTER FUNCTION public.immutable_concat_ws(text, VARIADIC text[]) OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 205 (class 1259 OID 57074)
-- Name: Clients; Type: TABLE; Schema: antiplagiarism; Owner: ulearn
--

CREATE TABLE antiplagiarism."Clients" (
    "Id" integer NOT NULL,
    "Token" uuid NOT NULL,
    "Name" character varying(200) NOT NULL,
    "IsEnabled" boolean NOT NULL
);


ALTER TABLE antiplagiarism."Clients" OWNER TO ulearn;

--
-- TOC entry 204 (class 1259 OID 57072)
-- Name: Clients_Id_seq; Type: SEQUENCE; Schema: antiplagiarism; Owner: ulearn
--

ALTER TABLE antiplagiarism."Clients" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME antiplagiarism."Clients_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 207 (class 1259 OID 57081)
-- Name: Codes; Type: TABLE; Schema: antiplagiarism; Owner: ulearn
--

CREATE TABLE antiplagiarism."Codes" (
    "Id" integer NOT NULL,
    "Text" text
);


ALTER TABLE antiplagiarism."Codes" OWNER TO ulearn;

--
-- TOC entry 206 (class 1259 OID 57079)
-- Name: Codes_Id_seq; Type: SEQUENCE; Schema: antiplagiarism; Owner: ulearn
--

ALTER TABLE antiplagiarism."Codes" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME antiplagiarism."Codes_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 208 (class 1259 OID 57089)
-- Name: ManualSuspicionLevels; Type: TABLE; Schema: antiplagiarism; Owner: ulearn
--

CREATE TABLE antiplagiarism."ManualSuspicionLevels" (
    "TaskId" uuid NOT NULL,
    "FaintSuspicion" double precision,
    "StrongSuspicion" double precision,
    "Timestamp" timestamp without time zone NOT NULL
);


ALTER TABLE antiplagiarism."ManualSuspicionLevels" OWNER TO ulearn;

--
-- TOC entry 220 (class 1259 OID 57160)
-- Name: MostSimilarSubmissions; Type: TABLE; Schema: antiplagiarism; Owner: ulearn
--

CREATE TABLE antiplagiarism."MostSimilarSubmissions" (
    "SubmissionId" integer NOT NULL,
    "SimilarSubmissionId" integer NOT NULL,
    "Weight" double precision NOT NULL,
    "Timestamp" timestamp without time zone NOT NULL
);


ALTER TABLE antiplagiarism."MostSimilarSubmissions" OWNER TO ulearn;

--
-- TOC entry 210 (class 1259 OID 57096)
-- Name: OldSubmissionsInfluenceBorder; Type: TABLE; Schema: antiplagiarism; Owner: ulearn
--

CREATE TABLE antiplagiarism."OldSubmissionsInfluenceBorder" (
    "Id" integer NOT NULL,
    "Date" timestamp without time zone
);


ALTER TABLE antiplagiarism."OldSubmissionsInfluenceBorder" OWNER TO ulearn;

--
-- TOC entry 209 (class 1259 OID 57094)
-- Name: OldSubmissionsInfluenceBorder_Id_seq; Type: SEQUENCE; Schema: antiplagiarism; Owner: ulearn
--

ALTER TABLE antiplagiarism."OldSubmissionsInfluenceBorder" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME antiplagiarism."OldSubmissionsInfluenceBorder_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 212 (class 1259 OID 57103)
-- Name: Snippets; Type: TABLE; Schema: antiplagiarism; Owner: ulearn
--

CREATE TABLE antiplagiarism."Snippets" (
    "Id" integer NOT NULL,
    "TokensCount" integer NOT NULL,
    "SnippetType" smallint NOT NULL,
    "Hash" integer NOT NULL
);


ALTER TABLE antiplagiarism."Snippets" OWNER TO ulearn;

--
-- TOC entry 222 (class 1259 OID 57177)
-- Name: SnippetsOccurences; Type: TABLE; Schema: antiplagiarism; Owner: ulearn
--

CREATE TABLE antiplagiarism."SnippetsOccurences" (
    "Id" integer NOT NULL,
    "SubmissionId" integer NOT NULL,
    "SnippetId" integer NOT NULL,
    "FirstTokenIndex" integer NOT NULL
);


ALTER TABLE antiplagiarism."SnippetsOccurences" OWNER TO ulearn;

--
-- TOC entry 221 (class 1259 OID 57175)
-- Name: SnippetsOccurences_Id_seq; Type: SEQUENCE; Schema: antiplagiarism; Owner: ulearn
--

ALTER TABLE antiplagiarism."SnippetsOccurences" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME antiplagiarism."SnippetsOccurences_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 219 (class 1259 OID 57145)
-- Name: SnippetsStatistics; Type: TABLE; Schema: antiplagiarism; Owner: ulearn
--

CREATE TABLE antiplagiarism."SnippetsStatistics" (
    "Id" integer NOT NULL,
    "SnippetId" integer NOT NULL,
    "TaskId" uuid NOT NULL,
    "ClientId" integer NOT NULL,
    "AuthorsCount" integer NOT NULL
);


ALTER TABLE antiplagiarism."SnippetsStatistics" OWNER TO ulearn;

--
-- TOC entry 218 (class 1259 OID 57143)
-- Name: SnippetsStatistics_Id_seq; Type: SEQUENCE; Schema: antiplagiarism; Owner: ulearn
--

ALTER TABLE antiplagiarism."SnippetsStatistics" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME antiplagiarism."SnippetsStatistics_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 211 (class 1259 OID 57101)
-- Name: Snippets_Id_seq; Type: SEQUENCE; Schema: antiplagiarism; Owner: ulearn
--

ALTER TABLE antiplagiarism."Snippets" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME antiplagiarism."Snippets_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 217 (class 1259 OID 57125)
-- Name: Submissions; Type: TABLE; Schema: antiplagiarism; Owner: ulearn
--

CREATE TABLE antiplagiarism."Submissions" (
    "Id" integer NOT NULL,
    "ClientId" integer NOT NULL,
    "TaskId" uuid NOT NULL,
    "AuthorId" uuid NOT NULL,
    "ProgramId" integer NOT NULL,
    "AdditionalInfo" character varying(500),
    "AddingTime" timestamp without time zone NOT NULL,
    "Language" smallint NOT NULL,
    "TokensCount" integer NOT NULL,
    "ClientSubmissionId" character varying(50)
);


ALTER TABLE antiplagiarism."Submissions" OWNER TO ulearn;

--
-- TOC entry 216 (class 1259 OID 57123)
-- Name: Submissions_Id_seq; Type: SEQUENCE; Schema: antiplagiarism; Owner: ulearn
--

ALTER TABLE antiplagiarism."Submissions" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME antiplagiarism."Submissions_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 57194)
-- Name: TaskStatisticsSourceData; Type: TABLE; Schema: antiplagiarism; Owner: ulearn
--

CREATE TABLE antiplagiarism."TaskStatisticsSourceData" (
    "Id" integer NOT NULL,
    "Submission1Id" integer NOT NULL,
    "Submission2Id" integer NOT NULL,
    "Weight" double precision NOT NULL
);


ALTER TABLE antiplagiarism."TaskStatisticsSourceData" OWNER TO ulearn;

--
-- TOC entry 223 (class 1259 OID 57192)
-- Name: TaskStatisticsSourceData_Id_seq; Type: SEQUENCE; Schema: antiplagiarism; Owner: ulearn
--

ALTER TABLE antiplagiarism."TaskStatisticsSourceData" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME antiplagiarism."TaskStatisticsSourceData_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 213 (class 1259 OID 57108)
-- Name: TasksStatisticsParameters; Type: TABLE; Schema: antiplagiarism; Owner: ulearn
--

CREATE TABLE antiplagiarism."TasksStatisticsParameters" (
    "TaskId" uuid NOT NULL,
    "Mean" double precision NOT NULL,
    "Deviation" double precision NOT NULL,
    "SubmissionsCount" integer NOT NULL,
    "Timestamp" timestamp without time zone
);


ALTER TABLE antiplagiarism."TasksStatisticsParameters" OWNER TO ulearn;

--
-- TOC entry 215 (class 1259 OID 57115)
-- Name: WorkQueueItems; Type: TABLE; Schema: antiplagiarism; Owner: ulearn
--

CREATE TABLE antiplagiarism."WorkQueueItems" (
    "Id" integer NOT NULL,
    "QueueId" integer NOT NULL,
    "ItemId" text NOT NULL,
    "TakeAfterTime" timestamp without time zone
);


ALTER TABLE antiplagiarism."WorkQueueItems" OWNER TO ulearn;

--
-- TOC entry 214 (class 1259 OID 57113)
-- Name: WorkQueueItems_Id_seq; Type: SEQUENCE; Schema: antiplagiarism; Owner: ulearn
--

ALTER TABLE antiplagiarism."WorkQueueItems" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME antiplagiarism."WorkQueueItems_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 247 (class 1259 OID 57356)
-- Name: AdditionalScores; Type: TABLE; Schema: public; Owner: ulearn
--

CREATE TABLE public."AdditionalScores" (
    "Id" integer NOT NULL,
    "CourseId" character varying(100) NOT NULL COLLATE public.case_insensitive,
    "UnitId" uuid NOT NULL,
    "ScoringGroupId" character varying(64) NOT NULL COLLATE public.case_insensitive,
    "UserId" character varying(64) NOT NULL COLLATE public.case_insensitive,
    "Score" integer NOT NULL,
    "InstructorId" character varying(64) NOT NULL COLLATE public.case_insensitive,
    "Timestamp" timestamp without time zone NOT NULL
);


ALTER TABLE public."AdditionalScores" OWNER TO ulearn;

--
-- TOC entry 246 (class 1259 OID 57354)
-- Name: AdditionalScores_Id_seq; Type: SEQUENCE; Schema: public; Owner: ulearn
--

ALTER TABLE public."AdditionalScores" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AdditionalScores_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 245 (class 1259 OID 57341)
-- Name: AspNetRoleClaims; Type: TABLE; Schema: public; Owner: ulearn
--

CREATE TABLE public."AspNetRoleClaims" (
    "Id" integer NOT NULL,
    "RoleId" text NOT NULL COLLATE public.case_insensitive,
    "ClaimType" text COLLATE public.case_insensitive,
    "ClaimValue" text COLLATE public.case_insensitive
);


ALTER TABLE public."AspNetRoleClaims" OWNER TO ulearn;

--
-- TOC entry 244 (class 1259 OID 57339)
-- Name: AspNetRoleClaims_Id_seq; Type: SEQUENCE; Schema: public; Owner: ulearn
--

ALTER TABLE public."AspNetRoleClaims" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AspNetRoleClaims_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 225 (class 1259 OID 57231)
-- Name: AspNetRoles; Type: TABLE; Schema: public; Owner: ulearn
--

CREATE TABLE public."AspNetRoles" (
    "Id" text NOT NULL COLLATE public.case_insensitive,
    "Name" character varying(256) COLLATE public.case_insensitive,
    "NormalizedName" character varying(256) COLLATE public.case_insensitive,
    "ConcurrencyStamp" text COLLATE public.case_insensitive
);


ALTER TABLE public."AspNetRoles" OWNER TO ulearn;

--
-- TOC entry 249 (class 1259 OID 57373)
-- Name: AspNetUserClaims; Type: TABLE; Schema: public; Owner: ulearn
--

CREATE TABLE public."AspNetUserClaims" (
    "Id" integer NOT NULL,
    "UserId" character varying(64) NOT NULL COLLATE public.case_insensitive,
    "ClaimType" text COLLATE public.case_insensitive,
    "ClaimValue" text COLLATE public.case_insensitive
);


ALTER TABLE public."AspNetUserClaims" OWNER TO ulearn;

--
-- TOC entry 248 (class 1259 OID 57371)
-- Name: AspNetUserClaims_Id_seq; Type: SEQUENCE; Schema: public; Owner: ulearn
--

ALTER TABLE public."AspNetUserClaims" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AspNetUserClaims_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 250 (class 1259 OID 57386)
-- Name: AspNetUserLogins; Type: TABLE; Schema: public; Owner: ulearn
--

CREATE TABLE public."AspNetUserLogins" (
    "LoginProvider" text NOT NULL COLLATE public.case_insensitive,
    "ProviderKey" text NOT NULL COLLATE public.case_insensitive,
    "ProviderDisplayName" text COLLATE public.case_insensitive,
    "UserId" character varying(64) NOT NULL COLLATE public.case_insensitive
);


ALTER TABLE public."AspNetUserLogins" OWNER TO ulearn;

--
-- TOC entry 251 (class 1259 OID 57399)
-- Name: AspNetUserRoles; Type: TABLE; Schema: public; Owner: ulearn
--

CREATE TABLE public."AspNetUserRoles" (
    "UserId" character varying(64) NOT NULL COLLATE public.case_insensitive,
    "RoleId" text NOT NULL COLLATE public.case_insensitive
);


ALTER TABLE public."AspNetUserRoles" OWNER TO ulearn;

--
-- TOC entry 252 (class 1259 OID 57417)
-- Name: AspNetUserTokens; Type: TABLE; Schema: public; Owner: ulearn
--

CREATE TABLE public."AspNetUserTokens" (
    "UserId" character varying(64) NOT NULL COLLATE public.case_insensitive,
    "LoginProvider" text NOT NULL COLLATE public.case_insensitive,
    "Name" text NOT NULL COLLATE public.case_insensitive,
    "Value" text COLLATE public.case_insensitive
);


ALTER TABLE public."AspNetUserTokens" OWNER TO ulearn;

--
-- TOC entry 226 (class 1259 OID 57239)
-- Name: AspNetUsers; Type: TABLE; Schema: public; Owner: ulearn
--

CREATE TABLE public."AspNetUsers" (
    "Id" character varying(64) NOT NULL COLLATE public.case_insensitive,
    "FirstName" text COLLATE public.case_insensitive,
    "LastName" text COLLATE public.case_insensitive,
    "Registered" timestamp without time zone NOT NULL,
    "LastEdit" timestamp without time zone,
    "AvatarUrl" text COLLATE public.case_insensitive,
    "TelegramChatId" bigint,
    "TelegramChatTitle" character varying(200) COLLATE public.case_insensitive,
    "KonturLogin" character varying(200) COLLATE public.case_insensitive,
    "LastConfirmationEmailTime" timestamp without time zone,
    "Gender" smallint,
    "IsDeleted" boolean NOT NULL,
    "Names" text GENERATED ALWAYS AS (public.immutable_concat_ws(' '::text, VARIADIC ARRAY[NULLIF(("UserName")::text, ''::text), NULLIF("FirstName", ''::text), NULLIF("LastName", ''::text), NULLIF("FirstName", ''::text)])) STORED,
    "UserName" character varying(256) COLLATE public.case_insensitive,
    "NormalizedUserName" character varying(256) COLLATE public.case_insensitive,
    "Email" character varying(256) COLLATE public.case_insensitive,
    "NormalizedEmail" character varying(256) COLLATE public.case_insensitive,
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text COLLATE public.case_insensitive,
    "SecurityStamp" text COLLATE public.case_insensitive,
    "ConcurrencyStamp" text COLLATE public.case_insensitive,
    "PhoneNumber" text COLLATE public.case_insensitive,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    "LockoutEndDateUtc" timestamp with time zone
);


ALTER TABLE public."AspNetUsers" OWNER TO ulearn;

--
-- TOC entry 296 (class 1259 OID 57764)
-- Name: AutomaticExerciseCheckings; Type: TABLE; Schema: public; Owner: ulearn
--

CREATE TABLE public."AutomaticExerciseCheckings" (
    "Id" integer NOT NULL,
    "Status" integer NOT NULL,
    "Elapsed" interval,
    "DisplayName" text COLLATE public.case_insensitive,
    "IsRightAnswer" boolean NOT NULL,
    "IsCompilationError" boolean NOT NULL,
    "CompilationErrorHash" character varying(40) COLLATE public.case_insensitive,
    "OutputHash" character varying(40) COLLATE public.case_insensitive,
    "DebugLogsHash" character varying(40) COLLATE public.case_insensitive,
    "ExecutionServiceName" character varying(40) COLLATE public.case_insensitive,
    "CheckingAgentName" character varying(256) COLLATE public.case_insensitive,
    "Score" integer,
    "Points" real,
    "CourseId" character varying(100) NOT NULL COLLATE public.case_insensitive,
    "SlideId" uuid NOT NULL,
    "Timestamp" timestamp without time zone NOT NULL,
    "UserId" character varying(64) NOT NULL COLLATE public.case_insensitive
);


ALTER TABLE public."AutomaticExerciseCheckings" OWNER TO ulearn;

--
-- TOC entry 295 (class 1259 OID 57762)
-- Name: AutomaticExerciseCheckings_Id_seq; Type: SEQUENCE; Schema: public; Owner: ulearn
--

ALTER TABLE public."AutomaticExerciseCheckings" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AutomaticExerciseCheckings_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 313 (class 1259 OID 57919)
-- Name: AutomaticQuizCheckings; Type: TABLE; Schema: public; Owner: ulearn
--

CREATE TABLE public."AutomaticQuizCheckings" (
    "Id" integer NOT NULL,
    "Score" integer NOT NULL,
    "IgnoreInAttemptsCount" boolean NOT NULL,
    "CourseId" character varying(100) NOT NULL COLLATE public.case_insensitive,
    "SlideId" uuid NOT NULL,
    "Timestamp" timestamp without time zone NOT NULL,
    "UserId" character varying(64) NOT NULL COLLATE public.case_insensitive
);


ALTER TABLE public."AutomaticQuizCheckings" OWNER TO ulearn;

--
-- TOC entry 294 (class 1259 OID 57749)
-- Name: CertificateTemplateArchives; Type: TABLE; Schema: public; Owner: ulearn
--

CREATE TABLE public."CertificateTemplateArchives" (
    "ArchiveName" character varying(128) NOT NULL COLLATE public.case_insensitive,
    "Content" bytea NOT NULL,
    "CertificateTemplateId" uuid NOT NULL
);


ALTER TABLE public."CertificateTemplateArchives" OWNER TO ulearn;

--
-- TOC entry 227 (class 1259 OID 57248)
-- Name: CertificateTemplates; Type: TABLE; Schema: public; Owner: ulearn
--

CREATE TABLE public."CertificateTemplates" (
    "Id" uuid NOT NULL,
    "CourseId" character varying(100) NOT NULL COLLATE public.case_insensitive,
    "Name" text NOT NULL COLLATE public.case_insensitive,
    "Timestamp" timestamp without time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "ArchiveName" character varying(128) NOT NULL COLLATE public.case_insensitive
);


ALTER TABLE public."CertificateTemplates" OWNER TO ulearn;

--
-- TOC entry 293 (class 1259 OID 57726)
-- Name: Certificates; Type: TABLE; Schema: public; Owner: ulearn
--

CREATE TABLE public."Certificates" (
    "Id" uuid NOT NULL,
    "TemplateId" uuid NOT NULL,
    "UserId" character varying(64) NOT NULL COLLATE public.case_insensitive,
    "InstructorId" character varying(64) NOT NULL COLLATE public.case_insensitive,
    "Parameters" text NOT NULL COLLATE public.case_insensitive,
    "Timestamp" timestamp without time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "IsPreview" boolean NOT NULL
);


ALTER TABLE public."Certificates" OWNER TO ulearn;

--
-- TOC entry 298 (class 1259 OID 57794)
-- Name: CommentLikes; Type: TABLE; Schema: public; Owner: ulearn
--

CREATE TABLE public."CommentLikes" (
    "Id" integer NOT NULL,
    "UserId" character varying(64) NOT NULL COLLATE public.case_insensitive,
    "CommentId" integer NOT NULL,
    "Timestamp" timestamp without time zone NOT NULL
);


ALTER TABLE public."CommentLikes" OWNER TO ulearn;

--
-- TOC entry 297 (class 1259 OID 57792)
-- Name: CommentLikes_Id_seq; Type: SEQUENCE; Schema: public; Owner: ulearn
--

ALTER TABLE public."CommentLikes" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."CommentLikes_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 254 (class 1259 OID 57432)
-- Name: Comments; Type: TABLE; Schema: public; Owner: ulearn
--

CREATE TABLE public."Comments" (
    "Id" integer NOT NULL,
    "CourseId" character varying(100) NOT NULL COLLATE public.case_insensitive,
    "SlideId" uuid NOT NULL,
    "AuthorId" character varying(64) NOT NULL COLLATE public.case_insensitive,
    "PublishTime" timestamp without time zone NOT NULL,
    "Text" text NOT NULL COLLATE public.case_insensitive,
    "IsApproved" boolean NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "IsCorrectAnswer" boolean NOT NULL,
    "IsPinnedToTop" boolean NOT NULL,
    "IsForInstructorsOnly" boolean NOT NULL,
    "ParentCommentId" integer NOT NULL
);


ALTER TABLE public."Comments" OWNER TO ulearn;

--
-- TOC entry 228 (class 1259 OID 57256)
-- Name: CommentsPolicies; Type: TABLE; Schema: public; Owner: ulearn
--

CREATE TABLE public."CommentsPolicies" (
    "CourseId" character varying(100) NOT NULL COLLATE public.case_insensitive,
    "IsCommentsEnabled" boolean NOT NULL,
    "ModerationPolicy" integer NOT NULL,
    "OnlyInstructorsCanReply" boolean NOT NULL
);


ALTER TABLE public."CommentsPolicies" OWNER TO ulearn;

--
-- TOC entry 253 (class 1259 OID 57430)
-- Name: Comments_Id_seq; Type: SEQUENCE; Schema: public; Owner: ulearn
--

ALTER TABLE public."Comments" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Comments_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 256 (class 1259 OID 57447)
-- Name: CourseAccesses; Type: TABLE; Schema: public; Owner: ulearn
--

CREATE TABLE public."CourseAccesses" (
    "Id" integer NOT NULL,
    "CourseId" character varying(100) NOT NULL COLLATE public.case_insensitive,
    "UserId" character varying(64) COLLATE public.case_insensitive,
    "GrantedById" character varying(64) COLLATE public.case_insensitive,
    "AccessType" smallint NOT NULL,
    "GrantTime" timestamp without time zone NOT NULL,
    "IsEnabled" boolean NOT NULL,
    "Comment" text COLLATE public.case_insensitive
);


ALTER TABLE public."CourseAccesses" OWNER TO ulearn;

--
-- TOC entry 255 (class 1259 OID 57445)
-- Name: CourseAccesses_Id_seq; Type: SEQUENCE; Schema: public; Owner: ulearn
--

ALTER TABLE public."CourseAccesses" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."CourseAccesses_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 300 (class 1259 OID 57811)
-- Name: CourseFiles; Type: TABLE; Schema: public; Owner: ulearn
--

CREATE TABLE public."CourseFiles" (
    "Id" integer NOT NULL,
    "CourseId" character varying(100) NOT NULL COLLATE public.case_insensitive,
    "CourseVersionId" uuid NOT NULL,
    "File" bytea NOT NULL
);


ALTER TABLE public."CourseFiles" OWNER TO ulearn;

--
-- TOC entry 299 (class 1259 OID 57809)
-- Name: CourseFiles_Id_seq; Type: SEQUENCE; Schema: public; Owner: ulearn
--

ALTER TABLE public."CourseFiles" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."CourseFiles_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 230 (class 1259 OID 57263)
-- Name: CourseGitRepos; Type: TABLE; Schema: public; Owner: ulearn
--

CREATE TABLE public."CourseGitRepos" (
    "Id" integer NOT NULL,
    "CourseId" character varying(100) COLLATE public.case_insensitive,
    "RepoUrl" text COLLATE public.case_insensitive,
    "Branch" text COLLATE public.case_insensitive,
    "PublicKey" text COLLATE public.case_insensitive,
    "PrivateKey" text COLLATE public.case_insensitive,
    "IsWebhookEnabled" boolean NOT NULL,
    "PathToCourseXml" text COLLATE public.case_insensitive,
    "CreateTime" timestamp without time zone NOT NULL
);


ALTER TABLE public."CourseGitRepos" OWNER TO ulearn;

--
-- TOC entry 229 (class 1259 OID 57261)
-- Name: CourseGitRepos_Id_seq; Type: SEQUENCE; Schema: public; Owner: ulearn
--

ALTER TABLE public."CourseGitRepos" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."CourseGitRepos_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 257 (class 1259 OID 57465)
-- Name: CourseVersions; Type: TABLE; Schema: public; Owner: ulearn
--

CREATE TABLE public."CourseVersions" (
    "Id" uuid NOT NULL,
    "CourseId" character varying(100) NOT NULL COLLATE public.case_insensitive,
    "LoadingTime" timestamp without time zone NOT NULL,
    "PublishTime" timestamp without time zone,
    "AuthorId" character varying(64) NOT NULL COLLATE public.case_insensitive,
    "RepoUrl" text COLLATE public.case_insensitive,
    "CommitHash" character varying(40) COLLATE public.case_insensitive,
    "Description" text COLLATE public.case_insensitive,
    "PathToCourseXml" text COLLATE public.case_insensitive
);


ALTER TABLE public."CourseVersions" OWNER TO ulearn;

--
-- TOC entry 302 (class 1259 OID 57826)
-- Name: EnabledAdditionalScoringGroups; Type: TABLE; Schema: public; Owner: ulearn
--

CREATE TABLE public."EnabledAdditionalScoringGroups" (
    "Id" integer NOT NULL,
    "GroupId" integer NOT NULL,
    "ScoringGroupId" text NOT NULL COLLATE public.case_insensitive
);


ALTER TABLE public."EnabledAdditionalScoringGroups" OWNER TO ulearn;

--
-- TOC entry 301 (class 1259 OID 57824)
-- Name: EnabledAdditionalScoringGroups_Id_seq; Type: SEQUENCE; Schema: public; Owner: ulearn
--

ALTER TABLE public."EnabledAdditionalScoringGroups" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."EnabledAdditionalScoringGroups_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 330 (class 1259 OID 58097)
-- Name: ExerciseCodeReviewComments; Type: TABLE; Schema: public; Owner: ulearn
--

CREATE TABLE public."ExerciseCodeReviewComments" (
    "Id" integer NOT NULL,
    "ReviewId" integer NOT NULL,
    "Text" text NOT NULL COLLATE public.case_insensitive,
    "AuthorId" character varying(64) NOT NULL COLLATE public.case_insensitive,
    "IsDeleted" boolean NOT NULL,
    "AddingTime" timestamp without time zone NOT NULL
);


ALTER TABLE public."ExerciseCodeReviewComments" OWNER TO ulearn;

--
-- TOC entry 329 (class 1259 OID 58095)
-- Name: ExerciseCodeReviewComments_Id_seq; Type: SEQUENCE; Schema: public; Owner: ulearn
--

ALTER TABLE public."ExerciseCodeReviewComments" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."ExerciseCodeReviewComments_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 328 (class 1259 OID 58072)
-- Name: ExerciseCodeReviews; Type: TABLE; Schema: public; Owner: ulearn
--

CREATE TABLE public."ExerciseCodeReviews" (
    "Id" integer NOT NULL,
    "ExerciseCheckingId" integer,
    "SubmissionId" integer,
    "StartLine" integer NOT NULL,
    "StartPosition" integer NOT NULL,
    "FinishLine" integer NOT NULL,
    "FinishPosition" integer NOT NULL,
    "Comment" text NOT NULL COLLATE public.case_insensitive,
    "AuthorId" character varying(64) NOT NULL COLLATE public.case_insensitive,
    "IsDeleted" boolean NOT NULL,
    "HiddenFromTopComments" boolean NOT NULL,
    "AddingTime" timestamp without time zone NOT NULL
);


ALTER TABLE public."ExerciseCodeReviews" OWNER TO ulearn;

--
-- TOC entry 327 (class 1259 OID 58070)
-- Name: ExerciseCodeReviews_Id_seq; Type: SEQUENCE; Schema: public; Owner: ulearn
--

ALTER TABLE public."ExerciseCodeReviews" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."ExerciseCodeReviews_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 320 (class 1259 OID 57993)
-- Name: ExerciseSolutionByGraders; Type: TABLE; Schema: public; Owner: ulearn
--

CREATE TABLE public."ExerciseSolutionByGraders" (
    "Id" integer NOT NULL,
    "ClientId" uuid NOT NULL,
    "SubmissionId" integer NOT NULL,
    "ClientUserId" text NOT NULL COLLATE public.case_insensitive
);


ALTER TABLE public."ExerciseSolutionByGraders" OWNER TO ulearn;

--
-- TOC entry 319 (class 1259 OID 57991)
-- Name: ExerciseSolutionByGraders_Id_seq; Type: SEQUENCE; Schema: public; Owner: ulearn
--

ALTER TABLE public."ExerciseSolutionByGraders" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."ExerciseSolutionByGraders_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 310 (class 1259 OID 57897)
-- Name: FeedViewTimestamps; Type: TABLE; Schema: public; Owner: ulearn
--

CREATE TABLE public."FeedViewTimestamps" (
    "Id" integer NOT NULL,
    "UserId" character varying(64) COLLATE public.case_insensitive,
    "TransportId" integer,
    "Timestamp" timestamp without time zone NOT NULL
);


ALTER TABLE public."FeedViewTimestamps" OWNER TO ulearn;

--
-- TOC entry 309 (class 1259 OID 57895)
-- Name: FeedViewTimestamps_Id_seq; Type: SEQUENCE; Schema: public; Owner: ulearn
--

ALTER TABLE public."FeedViewTimestamps" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."FeedViewTimestamps_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 258 (class 1259 OID 57478)
-- Name: GraderClients; Type: TABLE; Schema: public; Owner: ulearn
--

CREATE TABLE public."GraderClients" (
    "Id" uuid NOT NULL,
    "CourseId" character varying(100) NOT NULL COLLATE public.case_insensitive,
    "Name" character varying(100) NOT NULL COLLATE public.case_insensitive,
    "UserId" character varying(64) NOT NULL COLLATE public.case_insensitive
);


ALTER TABLE public."GraderClients" OWNER TO ulearn;

--
-- TOC entry 304 (class 1259 OID 57841)
-- Name: GroupAccesses; Type: TABLE; Schema: public; Owner: ulearn
--

CREATE TABLE public."GroupAccesses" (
    "Id" integer NOT NULL,
    "GroupId" integer NOT NULL,
    "UserId" character varying(64) COLLATE public.case_insensitive,
    "GrantedById" character varying(64) COLLATE public.case_insensitive,
    "AccessType" smallint NOT NULL,
    "GrantTime" timestamp without time zone NOT NULL,
    "IsEnabled" boolean NOT NULL
);


ALTER TABLE public."GroupAccesses" OWNER TO ulearn;

--
-- TOC entry 303 (class 1259 OID 57839)
-- Name: GroupAccesses_Id_seq; Type: SEQUENCE; Schema: public; Owner: ulearn
--

ALTER TABLE public."GroupAccesses" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."GroupAccesses_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 260 (class 1259 OID 57490)
-- Name: GroupLabels; Type: TABLE; Schema: public; Owner: ulearn
--

CREATE TABLE public."GroupLabels" (
    "Id" integer NOT NULL,
    "OwnerId" character varying(64) NOT NULL COLLATE public.case_insensitive,
    "Name" character varying(100) COLLATE public.case_insensitive,
    "ColorHex" character varying(6) COLLATE public.case_insensitive,
    "IsDeleted" boolean NOT NULL
);


ALTER TABLE public."GroupLabels" OWNER TO ulearn;

--
-- TOC entry 259 (class 1259 OID 57488)
-- Name: GroupLabels_Id_seq; Type: SEQUENCE; Schema: public; Owner: ulearn
--

ALTER TABLE public."GroupLabels" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."GroupLabels_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 306 (class 1259 OID 57863)
-- Name: GroupMembers; Type: TABLE; Schema: public; Owner: ulearn
--

CREATE TABLE public."GroupMembers" (
    "Id" integer NOT NULL,
    "GroupId" integer NOT NULL,
    "UserId" character varying(64) NOT NULL COLLATE public.case_insensitive,
    "AddingTime" timestamp without time zone
);


ALTER TABLE public."GroupMembers" OWNER TO ulearn;

--
-- TOC entry 305 (class 1259 OID 57861)
-- Name: GroupMembers_Id_seq; Type: SEQUENCE; Schema: public; Owner: ulearn
--

ALTER TABLE public."GroupMembers" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."GroupMembers_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 262 (class 1259 OID 57502)
-- Name: Groups; Type: TABLE; Schema: public; Owner: ulearn
--

CREATE TABLE public."Groups" (
    "Id" integer NOT NULL,
    "CourseId" character varying(100) NOT NULL COLLATE public.case_insensitive,
    "Name" character varying(300) NOT NULL COLLATE public.case_insensitive,
    "OwnerId" character varying(64) NOT NULL COLLATE public.case_insensitive,
    "IsDeleted" boolean NOT NULL,
    "IsArchived" boolean NOT NULL,
    "InviteHash" uuid NOT NULL,
    "IsInviteLinkEnabled" boolean NOT NULL,
    "IsManualCheckingEnabled" boolean NOT NULL,
    "IsManualCheckingEnabledForOldSolutions" boolean NOT NULL,
    "CanUsersSeeGroupProgress" boolean NOT NULL,
    "DefaultProhibitFutherReview" boolean NOT NULL,
    "CreateTime" timestamp without time zone
);


ALTER TABLE public."Groups" OWNER TO ulearn;

--
-- TOC entry 261 (class 1259 OID 57500)
-- Name: Groups_Id_seq; Type: SEQUENCE; Schema: public; Owner: ulearn
--

ALTER TABLE public."Groups" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Groups_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 308 (class 1259 OID 57880)
-- Name: LabelOnGroups; Type: TABLE; Schema: public; Owner: ulearn
--

CREATE TABLE public."LabelOnGroups" (
    "Id" integer NOT NULL,
    "GroupId" integer NOT NULL,
    "LabelId" integer NOT NULL
);


ALTER TABLE public."LabelOnGroups" OWNER TO ulearn;

--
-- TOC entry 307 (class 1259 OID 57878)
-- Name: LabelOnGroups_Id_seq; Type: SEQUENCE; Schema: public; Owner: ulearn
--

ALTER TABLE public."LabelOnGroups" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."LabelOnGroups_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 264 (class 1259 OID 57514)
-- Name: LastVisits; Type: TABLE; Schema: public; Owner: ulearn
--

CREATE TABLE public."LastVisits" (
    "Id" integer NOT NULL,
    "UserId" character varying(128) NOT NULL COLLATE public.case_insensitive,
    "CourseId" character varying(64) NOT NULL COLLATE public.case_insensitive,
    "SlideId" uuid NOT NULL,
    "Timestamp" timestamp without time zone NOT NULL
);


ALTER TABLE public."LastVisits" OWNER TO ulearn;

--
-- TOC entry 263 (class 1259 OID 57512)
-- Name: LastVisits_Id_seq; Type: SEQUENCE; Schema: public; Owner: ulearn
--

ALTER TABLE public."LastVisits" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."LastVisits_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 322 (class 1259 OID 58013)
-- Name: Likes; Type: TABLE; Schema: public; Owner: ulearn
--

CREATE TABLE public."Likes" (
    "Id" integer NOT NULL,
    "SubmissionId" integer NOT NULL,
    "UserId" character varying(64) NOT NULL COLLATE public.case_insensitive,
    "Timestamp" timestamp without time zone NOT NULL
);


ALTER TABLE public."Likes" OWNER TO ulearn;

--
-- TOC entry 321 (class 1259 OID 58011)
-- Name: Likes_Id_seq; Type: SEQUENCE; Schema: public; Owner: ulearn
--

ALTER TABLE public."Likes" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Likes_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 232 (class 1259 OID 57273)
-- Name: LtiConsumers; Type: TABLE; Schema: public; Owner: ulearn
--

CREATE TABLE public."LtiConsumers" (
    "ConsumerId" integer NOT NULL,
    "Name" character varying(64) NOT NULL COLLATE public.case_insensitive,
    "Key" character varying(64) NOT NULL COLLATE public.case_insensitive,
    "Secret" character varying(64) NOT NULL COLLATE public.case_insensitive
);


ALTER TABLE public."LtiConsumers" OWNER TO ulearn;

--
-- TOC entry 231 (class 1259 OID 57271)
-- Name: LtiConsumers_ConsumerId_seq; Type: SEQUENCE; Schema: public; Owner: ulearn
--

ALTER TABLE public."LtiConsumers" ALTER COLUMN "ConsumerId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."LtiConsumers_ConsumerId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 234 (class 1259 OID 57280)
-- Name: LtiSlideRequests; Type: TABLE; Schema: public; Owner: ulearn
--

CREATE TABLE public."LtiSlideRequests" (
    "RequestId" integer NOT NULL,
    "CourseId" character varying(100) NOT NULL COLLATE public.case_insensitive,
    "SlideId" uuid NOT NULL,
    "UserId" character varying(64) NOT NULL COLLATE public.case_insensitive,
    "Request" text NOT NULL COLLATE public.case_insensitive
);


ALTER TABLE public."LtiSlideRequests" OWNER TO ulearn;

--
-- TOC entry 233 (class 1259 OID 57278)
-- Name: LtiSlideRequests_RequestId_seq; Type: SEQUENCE; Schema: public; Owner: ulearn
--

ALTER TABLE public."LtiSlideRequests" ALTER COLUMN "RequestId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."LtiSlideRequests_RequestId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 324 (class 1259 OID 58030)
-- Name: ManualExerciseCheckings; Type: TABLE; Schema: public; Owner: ulearn
--

CREATE TABLE public."ManualExerciseCheckings" (
    "Id" integer NOT NULL,
    "SubmissionId" integer NOT NULL,
    "ProhibitFurtherManualCheckings" boolean NOT NULL,
    "Score" integer,
    "Percent" integer,
    "CourseId" character varying(100) NOT NULL COLLATE public.case_insensitive,
    "SlideId" uuid NOT NULL,
    "Timestamp" timestamp without time zone NOT NULL,
    "UserId" character varying(64) NOT NULL COLLATE public.case_insensitive,
    "LockedUntil" timestamp without time zone,
    "LockedById" character varying(64) COLLATE public.case_insensitive,
    "IsChecked" boolean NOT NULL
);


ALTER TABLE public."ManualExerciseCheckings" OWNER TO ulearn;

--
-- TOC entry 323 (class 1259 OID 58028)
-- Name: ManualExerciseCheckings_Id_seq; Type: SEQUENCE; Schema: public; Owner: ulearn
--

ALTER TABLE public."ManualExerciseCheckings" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."ManualExerciseCheckings_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 314 (class 1259 OID 57934)
-- Name: ManualQuizCheckings; Type: TABLE; Schema: public; Owner: ulearn
--

CREATE TABLE public."ManualQuizCheckings" (
    "Id" integer NOT NULL,
    "Score" integer NOT NULL,
    "IgnoreInAttemptsCount" boolean NOT NULL,
    "CourseId" character varying(100) NOT NULL COLLATE public.case_insensitive,
    "SlideId" uuid NOT NULL,
    "Timestamp" timestamp without time zone NOT NULL,
    "UserId" character varying(64) NOT NULL COLLATE public.case_insensitive,
    "LockedUntil" timestamp without time zone,
    "LockedById" character varying(64) COLLATE public.case_insensitive,
    "IsChecked" boolean NOT NULL
);


ALTER TABLE public."ManualQuizCheckings" OWNER TO ulearn;

--
-- TOC entry 334 (class 1259 OID 58237)
-- Name: NotificationDeliveries; Type: TABLE; Schema: public; Owner: ulearn
--

CREATE TABLE public."NotificationDeliveries" (
    "Id" integer NOT NULL,
    "NotificationId" integer NOT NULL,
    "NotificationTransportId" integer NOT NULL,
    "Status" smallint NOT NULL,
    "CreateTime" timestamp without time zone NOT NULL,
    "NextTryTime" timestamp without time zone,
    "FailsCount" integer NOT NULL
);


ALTER TABLE public."NotificationDeliveries" OWNER TO ulearn;

--
-- TOC entry 333 (class 1259 OID 58235)
-- Name: NotificationDeliveries_Id_seq; Type: SEQUENCE; Schema: public; Owner: ulearn
--

ALTER TABLE public."NotificationDeliveries" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."NotificationDeliveries_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 312 (class 1259 OID 57909)
-- Name: NotificationTransportSettings; Type: TABLE; Schema: public; Owner: ulearn
--

CREATE TABLE public."NotificationTransportSettings" (
    "Id" integer NOT NULL,
    "NotificationTransportId" integer NOT NULL,
    "CourseId" character varying(100) COLLATE public.case_insensitive,
    "NotificationType" smallint NOT NULL,
    "IsEnabled" boolean NOT NULL
);


ALTER TABLE public."NotificationTransportSettings" OWNER TO ulearn;

--
-- TOC entry 311 (class 1259 OID 57907)
-- Name: NotificationTransportSettings_Id_seq; Type: SEQUENCE; Schema: public; Owner: ulearn
--

ALTER TABLE public."NotificationTransportSettings" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."NotificationTransportSettings_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 266 (class 1259 OID 57526)
-- Name: NotificationTransports; Type: TABLE; Schema: public; Owner: ulearn
--

CREATE TABLE public."NotificationTransports" (
    "Id" integer NOT NULL,
    "UserId" character varying(64) COLLATE public.case_insensitive,
    "IsEnabled" boolean NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "Discriminator" text NOT NULL COLLATE public.case_insensitive
);


ALTER TABLE public."NotificationTransports" OWNER TO ulearn;

--
-- TOC entry 265 (class 1259 OID 57524)
-- Name: NotificationTransports_Id_seq; Type: SEQUENCE; Schema: public; Owner: ulearn
--

ALTER TABLE public."NotificationTransports" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."NotificationTransports_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 332 (class 1259 OID 58117)
-- Name: Notifications; Type: TABLE; Schema: public; Owner: ulearn
--

CREATE TABLE public."Notifications" (
    "Id" integer NOT NULL,
    "CourseId" character varying(100) NOT NULL COLLATE public.case_insensitive,
    "InitiatedById" character varying(64) NOT NULL COLLATE public.case_insensitive,
    "CreateTime" timestamp without time zone NOT NULL,
    "AreDeliveriesCreated" boolean NOT NULL,
    "Discriminator" text NOT NULL COLLATE public.case_insensitive,
    "CommentId1" integer,
    "LikedUserId" character varying(64) COLLATE public.case_insensitive,
    "ParentCommentId" integer,
    "AddedUserId" character varying(64) COLLATE public.case_insensitive,
    "ProcessId" integer,
    "GroupId" integer,
    "AccessId" integer,
    "UserId" character varying(64) COLLATE public.case_insensitive,
    "GroupMemberHasBeenRemovedNotification_GroupId" integer,
    "UserIds" text COLLATE public.case_insensitive,
    "UserDescriptions" text COLLATE public.case_insensitive,
    "Text" text COLLATE public.case_insensitive,
    "JoinedToYourGroupNotification_GroupId" integer,
    "JoinedUserId" character varying(64) COLLATE public.case_insensitive,
    "NotUploadedPackageNotification_CommitHash" text COLLATE public.case_insensitive,
    "NotUploadedPackageNotification_RepoUrl" text COLLATE public.case_insensitive,
    "CheckingId" integer,
    "IsRecheck" boolean,
    "PassedManualQuizCheckingNotification_CheckingId" integer,
    "CourseVersionId" uuid,
    "ScoreId" integer,
    "CertificateId" uuid,
    "CommentId" integer,
    "RevokedAccessToGroupNotification_AccessId" integer,
    "UploadedPackageNotification_CourseVersionId" uuid,
    "GroupId1" integer,
    "Text1" text COLLATE public.case_insensitive
);


ALTER TABLE public."Notifications" OWNER TO ulearn;

--
-- TOC entry 331 (class 1259 OID 58115)
-- Name: Notifications_Id_seq; Type: SEQUENCE; Schema: public; Owner: ulearn
--

ALTER TABLE public."Notifications" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Notifications_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 267 (class 1259 OID 57539)
-- Name: RestoreRequests; Type: TABLE; Schema: public; Owner: ulearn
--

CREATE TABLE public."RestoreRequests" (
    "Id" text NOT NULL COLLATE public.case_insensitive,
    "UserId" character varying(64) NOT NULL COLLATE public.case_insensitive,
    "Timestamp" timestamp without time zone NOT NULL
);


ALTER TABLE public."RestoreRequests" OWNER TO ulearn;

--
-- TOC entry 269 (class 1259 OID 57554)
-- Name: SlideHints; Type: TABLE; Schema: public; Owner: ulearn
--

CREATE TABLE public."SlideHints" (
    "Id" integer NOT NULL,
    "UserId" character varying(64) NOT NULL COLLATE public.case_insensitive,
    "HintId" integer NOT NULL,
    "CourseId" character varying(100) NOT NULL COLLATE public.case_insensitive,
    "SlideId" uuid NOT NULL,
    "IsHintHelped" boolean NOT NULL
);


ALTER TABLE public."SlideHints" OWNER TO ulearn;

--
-- TOC entry 268 (class 1259 OID 57552)
-- Name: SlideHints_Id_seq; Type: SEQUENCE; Schema: public; Owner: ulearn
--

ALTER TABLE public."SlideHints" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."SlideHints_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 271 (class 1259 OID 57566)
-- Name: SlideRates; Type: TABLE; Schema: public; Owner: ulearn
--

CREATE TABLE public."SlideRates" (
    "Id" integer NOT NULL,
    "Rate" integer NOT NULL,
    "UserId" character varying(64) NOT NULL COLLATE public.case_insensitive,
    "CourseId" character varying(100) NOT NULL COLLATE public.case_insensitive,
    "SlideId" uuid NOT NULL
);


ALTER TABLE public."SlideRates" OWNER TO ulearn;

--
-- TOC entry 270 (class 1259 OID 57564)
-- Name: SlideRates_Id_seq; Type: SEQUENCE; Schema: public; Owner: ulearn
--

ALTER TABLE public."SlideRates" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."SlideRates_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 273 (class 1259 OID 57578)
-- Name: StepikAccessTokens; Type: TABLE; Schema: public; Owner: ulearn
--

CREATE TABLE public."StepikAccessTokens" (
    "Id" integer NOT NULL,
    "UserId" character varying(64) NOT NULL COLLATE public.case_insensitive,
    "AccessToken" character varying(100) NOT NULL COLLATE public.case_insensitive,
    "AddedTime" timestamp without time zone NOT NULL
);


ALTER TABLE public."StepikAccessTokens" OWNER TO ulearn;

--
-- TOC entry 272 (class 1259 OID 57576)
-- Name: StepikAccessTokens_Id_seq; Type: SEQUENCE; Schema: public; Owner: ulearn
--

ALTER TABLE public."StepikAccessTokens" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."StepikAccessTokens_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 275 (class 1259 OID 57590)
-- Name: StepikExportProcesses; Type: TABLE; Schema: public; Owner: ulearn
--

CREATE TABLE public."StepikExportProcesses" (
    "Id" integer NOT NULL,
    "UlearnCourseId" character varying(100) NOT NULL COLLATE public.case_insensitive,
    "StepikCourseId" integer NOT NULL,
    "StepikCourseTitle" character varying(100) COLLATE public.case_insensitive,
    "IsFinished" boolean NOT NULL,
    "IsInitialExport" boolean NOT NULL,
    "IsSuccess" boolean NOT NULL,
    "Log" text COLLATE public.case_insensitive,
    "OwnerId" character varying(64) NOT NULL COLLATE public.case_insensitive,
    "StartTime" timestamp without time zone NOT NULL,
    "FinishTime" timestamp without time zone
);


ALTER TABLE public."StepikExportProcesses" OWNER TO ulearn;

--
-- TOC entry 274 (class 1259 OID 57588)
-- Name: StepikExportProcesses_Id_seq; Type: SEQUENCE; Schema: public; Owner: ulearn
--

ALTER TABLE public."StepikExportProcesses" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."StepikExportProcesses_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 236 (class 1259 OID 57290)
-- Name: StepikExportSlideAndStepMaps; Type: TABLE; Schema: public; Owner: ulearn
--

CREATE TABLE public."StepikExportSlideAndStepMaps" (
    "Id" integer NOT NULL,
    "UlearnCourseId" character varying(100) NOT NULL COLLATE public.case_insensitive,
    "StepikCourseId" integer NOT NULL,
    "SlideId" uuid NOT NULL,
    "StepId" integer NOT NULL,
    "SlideXml" text NOT NULL COLLATE public.case_insensitive
);


ALTER TABLE public."StepikExportSlideAndStepMaps" OWNER TO ulearn;

--
-- TOC entry 235 (class 1259 OID 57288)
-- Name: StepikExportSlideAndStepMaps_Id_seq; Type: SEQUENCE; Schema: public; Owner: ulearn
--

ALTER TABLE public."StepikExportSlideAndStepMaps" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."StepikExportSlideAndStepMaps_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 237 (class 1259 OID 57298)
-- Name: StyleErrorSettings; Type: TABLE; Schema: public; Owner: ulearn
--

CREATE TABLE public."StyleErrorSettings" (
    "ErrorType" integer NOT NULL,
    "IsEnabled" boolean NOT NULL
);


ALTER TABLE public."StyleErrorSettings" OWNER TO ulearn;

--
-- TOC entry 277 (class 1259 OID 57605)
-- Name: SystemAccesses; Type: TABLE; Schema: public; Owner: ulearn
--

CREATE TABLE public."SystemAccesses" (
    "Id" integer NOT NULL,
    "UserId" character varying(64) NOT NULL COLLATE public.case_insensitive,
    "GrantedById" character varying(64) NOT NULL COLLATE public.case_insensitive,
    "AccessType" smallint NOT NULL,
    "GrantTime" timestamp without time zone NOT NULL,
    "IsEnabled" boolean NOT NULL
);


ALTER TABLE public."SystemAccesses" OWNER TO ulearn;

--
-- TOC entry 276 (class 1259 OID 57603)
-- Name: SystemAccesses_Id_seq; Type: SEQUENCE; Schema: public; Owner: ulearn
--

ALTER TABLE public."SystemAccesses" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."SystemAccesses_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 238 (class 1259 OID 57303)
-- Name: TempCourseErrors; Type: TABLE; Schema: public; Owner: ulearn
--

CREATE TABLE public."TempCourseErrors" (
    "CourseId" character varying(100) NOT NULL COLLATE public.case_insensitive,
    "Error" text COLLATE public.case_insensitive
);


ALTER TABLE public."TempCourseErrors" OWNER TO ulearn;

--
-- TOC entry 278 (class 1259 OID 57620)
-- Name: TempCourses; Type: TABLE; Schema: public; Owner: ulearn
--

CREATE TABLE public."TempCourses" (
    "CourseId" character varying(100) NOT NULL COLLATE public.case_insensitive,
    "LoadingTime" timestamp without time zone NOT NULL,
    "LastUpdateTime" timestamp without time zone NOT NULL,
    "AuthorId" character varying(64) NOT NULL COLLATE public.case_insensitive
);


ALTER TABLE public."TempCourses" OWNER TO ulearn;

--
-- TOC entry 239 (class 1259 OID 57311)
-- Name: TextBlobs; Type: TABLE; Schema: public; Owner: ulearn
--

CREATE TABLE public."TextBlobs" (
    "Hash" character varying(40) NOT NULL COLLATE public.case_insensitive,
    "Text" text COLLATE public.case_insensitive
);


ALTER TABLE public."TextBlobs" OWNER TO ulearn;

--
-- TOC entry 241 (class 1259 OID 57321)
-- Name: UnitAppearances; Type: TABLE; Schema: public; Owner: ulearn
--

CREATE TABLE public."UnitAppearances" (
    "Id" integer NOT NULL,
    "CourseId" character varying(100) NOT NULL COLLATE public.case_insensitive,
    "UnitId" uuid NOT NULL,
    "UserName" text NOT NULL COLLATE public.case_insensitive,
    "PublishTime" timestamp without time zone NOT NULL
);


ALTER TABLE public."UnitAppearances" OWNER TO ulearn;

--
-- TOC entry 240 (class 1259 OID 57319)
-- Name: UnitAppearances_Id_seq; Type: SEQUENCE; Schema: public; Owner: ulearn
--

ALTER TABLE public."UnitAppearances" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."UnitAppearances_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 318 (class 1259 OID 57971)
-- Name: UserExerciseSubmissions; Type: TABLE; Schema: public; Owner: ulearn
--

CREATE TABLE public."UserExerciseSubmissions" (
    "Id" integer NOT NULL,
    "UserId" character varying(64) NOT NULL COLLATE public.case_insensitive,
    "CourseId" character varying(100) NOT NULL COLLATE public.case_insensitive,
    "SlideId" uuid NOT NULL,
    "Timestamp" timestamp without time zone NOT NULL,
    "SolutionCodeHash" character varying(40) NOT NULL COLLATE public.case_insensitive,
    "CodeHash" integer NOT NULL,
    "AutomaticCheckingId" integer,
    "AutomaticCheckingIsRightAnswer" boolean NOT NULL,
    "Language" smallint NOT NULL,
    "Sandbox" character varying(40) COLLATE public.case_insensitive,
    "AntiPlagiarismSubmissionId" integer
);


ALTER TABLE public."UserExerciseSubmissions" OWNER TO ulearn;

--
-- TOC entry 317 (class 1259 OID 57969)
-- Name: UserExerciseSubmissions_Id_seq; Type: SEQUENCE; Schema: public; Owner: ulearn
--

ALTER TABLE public."UserExerciseSubmissions" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."UserExerciseSubmissions_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 280 (class 1259 OID 57632)
-- Name: UserFlashcardsUnlocking; Type: TABLE; Schema: public; Owner: ulearn
--

CREATE TABLE public."UserFlashcardsUnlocking" (
    "Id" integer NOT NULL,
    "UserId" character varying(64) NOT NULL COLLATE public.case_insensitive,
    "CourseId" character varying(100) NOT NULL COLLATE public.case_insensitive,
    "UnitId" uuid NOT NULL
);


ALTER TABLE public."UserFlashcardsUnlocking" OWNER TO ulearn;

--
-- TOC entry 279 (class 1259 OID 57630)
-- Name: UserFlashcardsUnlocking_Id_seq; Type: SEQUENCE; Schema: public; Owner: ulearn
--

ALTER TABLE public."UserFlashcardsUnlocking" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."UserFlashcardsUnlocking_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 282 (class 1259 OID 57644)
-- Name: UserFlashcardsVisits; Type: TABLE; Schema: public; Owner: ulearn
--

CREATE TABLE public."UserFlashcardsVisits" (
    "Id" integer NOT NULL,
    "UserId" character varying(64) NOT NULL COLLATE public.case_insensitive,
    "CourseId" character varying(100) NOT NULL COLLATE public.case_insensitive,
    "UnitId" uuid NOT NULL,
    "FlashcardId" character varying(64) NOT NULL COLLATE public.case_insensitive,
    "Rate" integer NOT NULL,
    "Timestamp" timestamp without time zone NOT NULL
);


ALTER TABLE public."UserFlashcardsVisits" OWNER TO ulearn;

--
-- TOC entry 281 (class 1259 OID 57642)
-- Name: UserFlashcardsVisits_Id_seq; Type: SEQUENCE; Schema: public; Owner: ulearn
--

ALTER TABLE public."UserFlashcardsVisits" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."UserFlashcardsVisits_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 284 (class 1259 OID 57656)
-- Name: UserQuestions; Type: TABLE; Schema: public; Owner: ulearn
--

CREATE TABLE public."UserQuestions" (
    "QuestionId" integer NOT NULL,
    "SlideTitle" text NOT NULL COLLATE public.case_insensitive,
    "UserId" character varying(64) NOT NULL COLLATE public.case_insensitive,
    "UserName" character varying(64) NOT NULL COLLATE public.case_insensitive,
    "Question" text NOT NULL COLLATE public.case_insensitive,
    "UnitName" text NOT NULL COLLATE public.case_insensitive,
    "SlideId" uuid NOT NULL,
    "CourseId" character varying(100) COLLATE public.case_insensitive,
    "Time" timestamp without time zone NOT NULL
);


ALTER TABLE public."UserQuestions" OWNER TO ulearn;

--
-- TOC entry 283 (class 1259 OID 57654)
-- Name: UserQuestions_QuestionId_seq; Type: SEQUENCE; Schema: public; Owner: ulearn
--

ALTER TABLE public."UserQuestions" ALTER COLUMN "QuestionId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."UserQuestions_QuestionId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 316 (class 1259 OID 57956)
-- Name: UserQuizAnswers; Type: TABLE; Schema: public; Owner: ulearn
--

CREATE TABLE public."UserQuizAnswers" (
    "Id" integer NOT NULL,
    "SubmissionId" integer NOT NULL,
    "BlockId" character varying(64) COLLATE public.case_insensitive,
    "ItemId" character varying(64) COLLATE public.case_insensitive,
    "Text" character varying(8192) COLLATE public.case_insensitive,
    "IsRightAnswer" boolean NOT NULL,
    "QuizBlockScore" integer NOT NULL,
    "QuizBlockMaxScore" integer NOT NULL
);


ALTER TABLE public."UserQuizAnswers" OWNER TO ulearn;

--
-- TOC entry 315 (class 1259 OID 57954)
-- Name: UserQuizAnswers_Id_seq; Type: SEQUENCE; Schema: public; Owner: ulearn
--

ALTER TABLE public."UserQuizAnswers" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."UserQuizAnswers_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 286 (class 1259 OID 57671)
-- Name: UserQuizSubmissions; Type: TABLE; Schema: public; Owner: ulearn
--

CREATE TABLE public."UserQuizSubmissions" (
    "Id" integer NOT NULL,
    "UserId" character varying(40) NOT NULL COLLATE public.case_insensitive,
    "CourseId" character varying(100) NOT NULL COLLATE public.case_insensitive,
    "SlideId" uuid NOT NULL,
    "Timestamp" timestamp without time zone NOT NULL
);


ALTER TABLE public."UserQuizSubmissions" OWNER TO ulearn;

--
-- TOC entry 285 (class 1259 OID 57669)
-- Name: UserQuizSubmissions_Id_seq; Type: SEQUENCE; Schema: public; Owner: ulearn
--

ALTER TABLE public."UserQuizSubmissions" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."UserQuizSubmissions_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 288 (class 1259 OID 57683)
-- Name: UserRoles; Type: TABLE; Schema: public; Owner: ulearn
--

CREATE TABLE public."UserRoles" (
    "Id" integer NOT NULL,
    "UserId" character varying(64) COLLATE public.case_insensitive,
    "CourseId" text NOT NULL COLLATE public.case_insensitive,
    "Role" integer NOT NULL,
    "GrantedById" text COLLATE public.case_insensitive,
    "GrantTime" timestamp without time zone,
    "IsEnabled" boolean,
    "Comment" text COLLATE public.case_insensitive
);


ALTER TABLE public."UserRoles" OWNER TO ulearn;

--
-- TOC entry 287 (class 1259 OID 57681)
-- Name: UserRoles_Id_seq; Type: SEQUENCE; Schema: public; Owner: ulearn
--

ALTER TABLE public."UserRoles" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."UserRoles_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 290 (class 1259 OID 57698)
-- Name: Visits; Type: TABLE; Schema: public; Owner: ulearn
--

CREATE TABLE public."Visits" (
    "Id" integer NOT NULL,
    "UserId" character varying(64) NOT NULL COLLATE public.case_insensitive,
    "CourseId" character varying(100) NOT NULL COLLATE public.case_insensitive,
    "SlideId" uuid NOT NULL,
    "Timestamp" timestamp without time zone NOT NULL,
    "Score" integer NOT NULL,
    "HasManualChecking" boolean NOT NULL,
    "AttemptsCount" integer NOT NULL,
    "IsSkipped" boolean NOT NULL,
    "IsPassed" boolean NOT NULL,
    "IpAddress" text COLLATE public.case_insensitive
);


ALTER TABLE public."Visits" OWNER TO ulearn;

--
-- TOC entry 289 (class 1259 OID 57696)
-- Name: Visits_Id_seq; Type: SEQUENCE; Schema: public; Owner: ulearn
--

ALTER TABLE public."Visits" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Visits_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 243 (class 1259 OID 57331)
-- Name: WorkQueueItems; Type: TABLE; Schema: public; Owner: ulearn
--

CREATE TABLE public."WorkQueueItems" (
    "Id" integer NOT NULL,
    "QueueId" integer NOT NULL,
    "ItemId" text NOT NULL COLLATE public.case_insensitive,
    "Priority" integer NOT NULL,
    "Type" text COLLATE public.case_insensitive,
    "TakeAfterTime" timestamp without time zone
);


ALTER TABLE public."WorkQueueItems" OWNER TO ulearn;

--
-- TOC entry 242 (class 1259 OID 57329)
-- Name: WorkQueueItems_Id_seq; Type: SEQUENCE; Schema: public; Owner: ulearn
--

ALTER TABLE public."WorkQueueItems" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."WorkQueueItems_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 326 (class 1259 OID 58052)
-- Name: XQueueExerciseSubmissions; Type: TABLE; Schema: public; Owner: ulearn
--

CREATE TABLE public."XQueueExerciseSubmissions" (
    "Id" integer NOT NULL,
    "SubmissionId" integer NOT NULL,
    "WatcherId" integer NOT NULL,
    "XQueueHeader" text NOT NULL COLLATE public.case_insensitive,
    "IsResultSent" boolean NOT NULL
);


ALTER TABLE public."XQueueExerciseSubmissions" OWNER TO ulearn;

--
-- TOC entry 325 (class 1259 OID 58050)
-- Name: XQueueExerciseSubmissions_Id_seq; Type: SEQUENCE; Schema: public; Owner: ulearn
--

ALTER TABLE public."XQueueExerciseSubmissions" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."XQueueExerciseSubmissions_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 292 (class 1259 OID 57713)
-- Name: XQueueWatchers; Type: TABLE; Schema: public; Owner: ulearn
--

CREATE TABLE public."XQueueWatchers" (
    "Id" integer NOT NULL,
    "Name" text NOT NULL COLLATE public.case_insensitive,
    "BaseUrl" text NOT NULL COLLATE public.case_insensitive,
    "QueueName" text NOT NULL COLLATE public.case_insensitive,
    "UserName" text NOT NULL COLLATE public.case_insensitive,
    "Password" text NOT NULL COLLATE public.case_insensitive,
    "IsEnabled" boolean NOT NULL,
    "UserId" character varying(64) NOT NULL COLLATE public.case_insensitive
);


ALTER TABLE public."XQueueWatchers" OWNER TO ulearn;

--
-- TOC entry 291 (class 1259 OID 57711)
-- Name: XQueueWatchers_Id_seq; Type: SEQUENCE; Schema: public; Owner: ulearn
--

ALTER TABLE public."XQueueWatchers" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."XQueueWatchers_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 203 (class 1259 OID 57066)
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: ulearn
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO ulearn;

--
-- TOC entry 335 (class 1259 OID 58437)
-- Name: __MigrationHistory; Type: TABLE; Schema: public; Owner: ulearn
--

CREATE TABLE public."__MigrationHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ContextKey" character varying(300) NOT NULL,
    "Model" bytea NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);

ALTER TABLE public."__MigrationHistory" OWNER TO ulearn;

--
-- TOC entry 3375 (class 2606 OID 57078)
-- Name: Clients PK_Clients; Type: CONSTRAINT; Schema: antiplagiarism; Owner: ulearn
--

ALTER TABLE ONLY antiplagiarism."Clients"
    ADD CONSTRAINT "PK_Clients" PRIMARY KEY ("Id");


--
-- TOC entry 3377 (class 2606 OID 57088)
-- Name: Codes PK_Codes; Type: CONSTRAINT; Schema: antiplagiarism; Owner: ulearn
--

ALTER TABLE ONLY antiplagiarism."Codes"
    ADD CONSTRAINT "PK_Codes" PRIMARY KEY ("Id");


--
-- TOC entry 3379 (class 2606 OID 57093)
-- Name: ManualSuspicionLevels PK_ManualSuspicionLevels; Type: CONSTRAINT; Schema: antiplagiarism; Owner: ulearn
--

ALTER TABLE ONLY antiplagiarism."ManualSuspicionLevels"
    ADD CONSTRAINT "PK_ManualSuspicionLevels" PRIMARY KEY ("TaskId");


--
-- TOC entry 3407 (class 2606 OID 57164)
-- Name: MostSimilarSubmissions PK_MostSimilarSubmissions; Type: CONSTRAINT; Schema: antiplagiarism; Owner: ulearn
--

ALTER TABLE ONLY antiplagiarism."MostSimilarSubmissions"
    ADD CONSTRAINT "PK_MostSimilarSubmissions" PRIMARY KEY ("SubmissionId");


--
-- TOC entry 3381 (class 2606 OID 57100)
-- Name: OldSubmissionsInfluenceBorder PK_OldSubmissionsInfluenceBorder; Type: CONSTRAINT; Schema: antiplagiarism; Owner: ulearn
--

ALTER TABLE ONLY antiplagiarism."OldSubmissionsInfluenceBorder"
    ADD CONSTRAINT "PK_OldSubmissionsInfluenceBorder" PRIMARY KEY ("Id");


--
-- TOC entry 3384 (class 2606 OID 57107)
-- Name: Snippets PK_Snippets; Type: CONSTRAINT; Schema: antiplagiarism; Owner: ulearn
--

ALTER TABLE ONLY antiplagiarism."Snippets"
    ADD CONSTRAINT "PK_Snippets" PRIMARY KEY ("Id");


--
-- TOC entry 3412 (class 2606 OID 57181)
-- Name: SnippetsOccurences PK_SnippetsOccurences; Type: CONSTRAINT; Schema: antiplagiarism; Owner: ulearn
--

ALTER TABLE ONLY antiplagiarism."SnippetsOccurences"
    ADD CONSTRAINT "PK_SnippetsOccurences" PRIMARY KEY ("Id");


--
-- TOC entry 3403 (class 2606 OID 57149)
-- Name: SnippetsStatistics PK_SnippetsStatistics; Type: CONSTRAINT; Schema: antiplagiarism; Owner: ulearn
--

ALTER TABLE ONLY antiplagiarism."SnippetsStatistics"
    ADD CONSTRAINT "PK_SnippetsStatistics" PRIMARY KEY ("Id");


--
-- TOC entry 3399 (class 2606 OID 57132)
-- Name: Submissions PK_Submissions; Type: CONSTRAINT; Schema: antiplagiarism; Owner: ulearn
--

ALTER TABLE ONLY antiplagiarism."Submissions"
    ADD CONSTRAINT "PK_Submissions" PRIMARY KEY ("Id");


--
-- TOC entry 3416 (class 2606 OID 57198)
-- Name: TaskStatisticsSourceData PK_TaskStatisticsSourceData; Type: CONSTRAINT; Schema: antiplagiarism; Owner: ulearn
--

ALTER TABLE ONLY antiplagiarism."TaskStatisticsSourceData"
    ADD CONSTRAINT "PK_TaskStatisticsSourceData" PRIMARY KEY ("Id");


--
-- TOC entry 3386 (class 2606 OID 57112)
-- Name: TasksStatisticsParameters PK_TasksStatisticsParameters; Type: CONSTRAINT; Schema: antiplagiarism; Owner: ulearn
--

ALTER TABLE ONLY antiplagiarism."TasksStatisticsParameters"
    ADD CONSTRAINT "PK_TasksStatisticsParameters" PRIMARY KEY ("TaskId");


--
-- TOC entry 3389 (class 2606 OID 57122)
-- Name: WorkQueueItems PK_WorkQueueItems; Type: CONSTRAINT; Schema: antiplagiarism; Owner: ulearn
--

ALTER TABLE ONLY antiplagiarism."WorkQueueItems"
    ADD CONSTRAINT "PK_WorkQueueItems" PRIMARY KEY ("Id");


--
-- TOC entry 3465 (class 2606 OID 57360)
-- Name: AdditionalScores PK_AdditionalScores; Type: CONSTRAINT; Schema: public; Owner: ulearn
--

ALTER TABLE ONLY public."AdditionalScores"
    ADD CONSTRAINT "PK_AdditionalScores" PRIMARY KEY ("Id");


--
-- TOC entry 3458 (class 2606 OID 57348)
-- Name: AspNetRoleClaims PK_AspNetRoleClaims; Type: CONSTRAINT; Schema: public; Owner: ulearn
--

ALTER TABLE ONLY public."AspNetRoleClaims"
    ADD CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id");


--
-- TOC entry 3418 (class 2606 OID 57238)
-- Name: AspNetRoles PK_AspNetRoles; Type: CONSTRAINT; Schema: public; Owner: ulearn
--

ALTER TABLE ONLY public."AspNetRoles"
    ADD CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id");


--
-- TOC entry 3468 (class 2606 OID 57380)
-- Name: AspNetUserClaims PK_AspNetUserClaims; Type: CONSTRAINT; Schema: public; Owner: ulearn
--

ALTER TABLE ONLY public."AspNetUserClaims"
    ADD CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id");


--
-- TOC entry 3471 (class 2606 OID 57393)
-- Name: AspNetUserLogins PK_AspNetUserLogins; Type: CONSTRAINT; Schema: public; Owner: ulearn
--

ALTER TABLE ONLY public."AspNetUserLogins"
    ADD CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey");


--
-- TOC entry 3474 (class 2606 OID 57406)
-- Name: AspNetUserRoles PK_AspNetUserRoles; Type: CONSTRAINT; Schema: public; Owner: ulearn
--

ALTER TABLE ONLY public."AspNetUserRoles"
    ADD CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId");


--
-- TOC entry 3476 (class 2606 OID 57424)
-- Name: AspNetUserTokens PK_AspNetUserTokens; Type: CONSTRAINT; Schema: public; Owner: ulearn
--

ALTER TABLE ONLY public."AspNetUserTokens"
    ADD CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name");


--
-- TOC entry 3425 (class 2606 OID 57247)
-- Name: AspNetUsers PK_AspNetUsers; Type: CONSTRAINT; Schema: public; Owner: ulearn
--

ALTER TABLE ONLY public."AspNetUsers"
    ADD CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id");


--
-- TOC entry 3587 (class 2606 OID 57771)
-- Name: AutomaticExerciseCheckings PK_AutomaticExerciseCheckings; Type: CONSTRAINT; Schema: public; Owner: ulearn
--

ALTER TABLE ONLY public."AutomaticExerciseCheckings"
    ADD CONSTRAINT "PK_AutomaticExerciseCheckings" PRIMARY KEY ("Id");


--
-- TOC entry 3633 (class 2606 OID 57923)
-- Name: AutomaticQuizCheckings PK_AutomaticQuizCheckings; Type: CONSTRAINT; Schema: public; Owner: ulearn
--

ALTER TABLE ONLY public."AutomaticQuizCheckings"
    ADD CONSTRAINT "PK_AutomaticQuizCheckings" PRIMARY KEY ("Id");


--
-- TOC entry 3576 (class 2606 OID 57756)
-- Name: CertificateTemplateArchives PK_CertificateTemplateArchives; Type: CONSTRAINT; Schema: public; Owner: ulearn
--

ALTER TABLE ONLY public."CertificateTemplateArchives"
    ADD CONSTRAINT "PK_CertificateTemplateArchives" PRIMARY KEY ("ArchiveName");


--
-- TOC entry 3429 (class 2606 OID 57255)
-- Name: CertificateTemplates PK_CertificateTemplates; Type: CONSTRAINT; Schema: public; Owner: ulearn
--

ALTER TABLE ONLY public."CertificateTemplates"
    ADD CONSTRAINT "PK_CertificateTemplates" PRIMARY KEY ("Id");


--
-- TOC entry 3573 (class 2606 OID 57733)
-- Name: Certificates PK_Certificates; Type: CONSTRAINT; Schema: public; Owner: ulearn
--

ALTER TABLE ONLY public."Certificates"
    ADD CONSTRAINT "PK_Certificates" PRIMARY KEY ("Id");


--
-- TOC entry 3591 (class 2606 OID 57798)
-- Name: CommentLikes PK_CommentLikes; Type: CONSTRAINT; Schema: public; Owner: ulearn
--

ALTER TABLE ONLY public."CommentLikes"
    ADD CONSTRAINT "PK_CommentLikes" PRIMARY KEY ("Id");


--
-- TOC entry 3480 (class 2606 OID 57439)
-- Name: Comments PK_Comments; Type: CONSTRAINT; Schema: public; Owner: ulearn
--

ALTER TABLE ONLY public."Comments"
    ADD CONSTRAINT "PK_Comments" PRIMARY KEY ("Id");


--
-- TOC entry 3431 (class 2606 OID 57260)
-- Name: CommentsPolicies PK_CommentsPolicies; Type: CONSTRAINT; Schema: public; Owner: ulearn
--

ALTER TABLE ONLY public."CommentsPolicies"
    ADD CONSTRAINT "PK_CommentsPolicies" PRIMARY KEY ("CourseId");


--
-- TOC entry 3488 (class 2606 OID 57454)
-- Name: CourseAccesses PK_CourseAccesses; Type: CONSTRAINT; Schema: public; Owner: ulearn
--

ALTER TABLE ONLY public."CourseAccesses"
    ADD CONSTRAINT "PK_CourseAccesses" PRIMARY KEY ("Id");


--
-- TOC entry 3594 (class 2606 OID 57818)
-- Name: CourseFiles PK_CourseFiles; Type: CONSTRAINT; Schema: public; Owner: ulearn
--

ALTER TABLE ONLY public."CourseFiles"
    ADD CONSTRAINT "PK_CourseFiles" PRIMARY KEY ("Id");


--
-- TOC entry 3433 (class 2606 OID 57270)
-- Name: CourseGitRepos PK_CourseGitRepos; Type: CONSTRAINT; Schema: public; Owner: ulearn
--

ALTER TABLE ONLY public."CourseGitRepos"
    ADD CONSTRAINT "PK_CourseGitRepos" PRIMARY KEY ("Id");


--
-- TOC entry 3493 (class 2606 OID 57472)
-- Name: CourseVersions PK_CourseVersions; Type: CONSTRAINT; Schema: public; Owner: ulearn
--

ALTER TABLE ONLY public."CourseVersions"
    ADD CONSTRAINT "PK_CourseVersions" PRIMARY KEY ("Id");


--
-- TOC entry 3597 (class 2606 OID 57833)
-- Name: EnabledAdditionalScoringGroups PK_EnabledAdditionalScoringGroups; Type: CONSTRAINT; Schema: public; Owner: ulearn
--

ALTER TABLE ONLY public."EnabledAdditionalScoringGroups"
    ADD CONSTRAINT "PK_EnabledAdditionalScoringGroups" PRIMARY KEY ("Id");


--
-- TOC entry 3691 (class 2606 OID 58104)
-- Name: ExerciseCodeReviewComments PK_ExerciseCodeReviewComments; Type: CONSTRAINT; Schema: public; Owner: ulearn
--

ALTER TABLE ONLY public."ExerciseCodeReviewComments"
    ADD CONSTRAINT "PK_ExerciseCodeReviewComments" PRIMARY KEY ("Id");


--
-- TOC entry 3686 (class 2606 OID 58079)
-- Name: ExerciseCodeReviews PK_ExerciseCodeReviews; Type: CONSTRAINT; Schema: public; Owner: ulearn
--

ALTER TABLE ONLY public."ExerciseCodeReviews"
    ADD CONSTRAINT "PK_ExerciseCodeReviews" PRIMARY KEY ("Id");


--
-- TOC entry 3664 (class 2606 OID 58000)
-- Name: ExerciseSolutionByGraders PK_ExerciseSolutionByGraders; Type: CONSTRAINT; Schema: public; Owner: ulearn
--

ALTER TABLE ONLY public."ExerciseSolutionByGraders"
    ADD CONSTRAINT "PK_ExerciseSolutionByGraders" PRIMARY KEY ("Id");


--
-- TOC entry 3620 (class 2606 OID 57901)
-- Name: FeedViewTimestamps PK_FeedViewTimestamps; Type: CONSTRAINT; Schema: public; Owner: ulearn
--

ALTER TABLE ONLY public."FeedViewTimestamps"
    ADD CONSTRAINT "PK_FeedViewTimestamps" PRIMARY KEY ("Id");


--
-- TOC entry 3496 (class 2606 OID 57482)
-- Name: GraderClients PK_GraderClients; Type: CONSTRAINT; Schema: public; Owner: ulearn
--

ALTER TABLE ONLY public."GraderClients"
    ADD CONSTRAINT "PK_GraderClients" PRIMARY KEY ("Id");


--
-- TOC entry 3605 (class 2606 OID 57845)
-- Name: GroupAccesses PK_GroupAccesses; Type: CONSTRAINT; Schema: public; Owner: ulearn
--

ALTER TABLE ONLY public."GroupAccesses"
    ADD CONSTRAINT "PK_GroupAccesses" PRIMARY KEY ("Id");


--
-- TOC entry 3500 (class 2606 OID 57494)
-- Name: GroupLabels PK_GroupLabels; Type: CONSTRAINT; Schema: public; Owner: ulearn
--

ALTER TABLE ONLY public."GroupLabels"
    ADD CONSTRAINT "PK_GroupLabels" PRIMARY KEY ("Id");


--
-- TOC entry 3609 (class 2606 OID 57867)
-- Name: GroupMembers PK_GroupMembers; Type: CONSTRAINT; Schema: public; Owner: ulearn
--

ALTER TABLE ONLY public."GroupMembers"
    ADD CONSTRAINT "PK_GroupMembers" PRIMARY KEY ("Id");


--
-- TOC entry 3505 (class 2606 OID 57506)
-- Name: Groups PK_Groups; Type: CONSTRAINT; Schema: public; Owner: ulearn
--

ALTER TABLE ONLY public."Groups"
    ADD CONSTRAINT "PK_Groups" PRIMARY KEY ("Id");


--
-- TOC entry 3614 (class 2606 OID 57884)
-- Name: LabelOnGroups PK_LabelOnGroups; Type: CONSTRAINT; Schema: public; Owner: ulearn
--

ALTER TABLE ONLY public."LabelOnGroups"
    ADD CONSTRAINT "PK_LabelOnGroups" PRIMARY KEY ("Id");


--
-- TOC entry 3509 (class 2606 OID 57518)
-- Name: LastVisits PK_LastVisits; Type: CONSTRAINT; Schema: public; Owner: ulearn
--

ALTER TABLE ONLY public."LastVisits"
    ADD CONSTRAINT "PK_LastVisits" PRIMARY KEY ("Id");


--
-- TOC entry 3668 (class 2606 OID 58017)
-- Name: Likes PK_Likes; Type: CONSTRAINT; Schema: public; Owner: ulearn
--

ALTER TABLE ONLY public."Likes"
    ADD CONSTRAINT "PK_Likes" PRIMARY KEY ("Id");


--
-- TOC entry 3436 (class 2606 OID 57277)
-- Name: LtiConsumers PK_LtiConsumers; Type: CONSTRAINT; Schema: public; Owner: ulearn
--

ALTER TABLE ONLY public."LtiConsumers"
    ADD CONSTRAINT "PK_LtiConsumers" PRIMARY KEY ("ConsumerId");


--
-- TOC entry 3439 (class 2606 OID 57287)
-- Name: LtiSlideRequests PK_LtiSlideRequests; Type: CONSTRAINT; Schema: public; Owner: ulearn
--

ALTER TABLE ONLY public."LtiSlideRequests"
    ADD CONSTRAINT "PK_LtiSlideRequests" PRIMARY KEY ("RequestId");


--
-- TOC entry 3677 (class 2606 OID 58034)
-- Name: ManualExerciseCheckings PK_ManualExerciseCheckings; Type: CONSTRAINT; Schema: public; Owner: ulearn
--

ALTER TABLE ONLY public."ManualExerciseCheckings"
    ADD CONSTRAINT "PK_ManualExerciseCheckings" PRIMARY KEY ("Id");


--
-- TOC entry 3641 (class 2606 OID 57938)
-- Name: ManualQuizCheckings PK_ManualQuizCheckings; Type: CONSTRAINT; Schema: public; Owner: ulearn
--

ALTER TABLE ONLY public."ManualQuizCheckings"
    ADD CONSTRAINT "PK_ManualQuizCheckings" PRIMARY KEY ("Id");


--
-- TOC entry 3724 (class 2606 OID 58241)
-- Name: NotificationDeliveries PK_NotificationDeliveries; Type: CONSTRAINT; Schema: public; Owner: ulearn
--

ALTER TABLE ONLY public."NotificationDeliveries"
    ADD CONSTRAINT "PK_NotificationDeliveries" PRIMARY KEY ("Id");


--
-- TOC entry 3626 (class 2606 OID 57913)
-- Name: NotificationTransportSettings PK_NotificationTransportSettings; Type: CONSTRAINT; Schema: public; Owner: ulearn
--

ALTER TABLE ONLY public."NotificationTransportSettings"
    ADD CONSTRAINT "PK_NotificationTransportSettings" PRIMARY KEY ("Id");


--
-- TOC entry 3513 (class 2606 OID 57533)
-- Name: NotificationTransports PK_NotificationTransports; Type: CONSTRAINT; Schema: public; Owner: ulearn
--

ALTER TABLE ONLY public."NotificationTransports"
    ADD CONSTRAINT "PK_NotificationTransports" PRIMARY KEY ("Id");


--
-- TOC entry 3718 (class 2606 OID 58124)
-- Name: Notifications PK_Notifications; Type: CONSTRAINT; Schema: public; Owner: ulearn
--

ALTER TABLE ONLY public."Notifications"
    ADD CONSTRAINT "PK_Notifications" PRIMARY KEY ("Id");


--
-- TOC entry 3516 (class 2606 OID 57546)
-- Name: RestoreRequests PK_RestoreRequests; Type: CONSTRAINT; Schema: public; Owner: ulearn
--

ALTER TABLE ONLY public."RestoreRequests"
    ADD CONSTRAINT "PK_RestoreRequests" PRIMARY KEY ("Id");


--
-- TOC entry 3520 (class 2606 OID 57558)
-- Name: SlideHints PK_SlideHints; Type: CONSTRAINT; Schema: public; Owner: ulearn
--

ALTER TABLE ONLY public."SlideHints"
    ADD CONSTRAINT "PK_SlideHints" PRIMARY KEY ("Id");


--
-- TOC entry 3524 (class 2606 OID 57570)
-- Name: SlideRates PK_SlideRates; Type: CONSTRAINT; Schema: public; Owner: ulearn
--

ALTER TABLE ONLY public."SlideRates"
    ADD CONSTRAINT "PK_SlideRates" PRIMARY KEY ("Id");


--
-- TOC entry 3528 (class 2606 OID 57582)
-- Name: StepikAccessTokens PK_StepikAccessTokens; Type: CONSTRAINT; Schema: public; Owner: ulearn
--

ALTER TABLE ONLY public."StepikAccessTokens"
    ADD CONSTRAINT "PK_StepikAccessTokens" PRIMARY KEY ("Id");


--
-- TOC entry 3531 (class 2606 OID 57597)
-- Name: StepikExportProcesses PK_StepikExportProcesses; Type: CONSTRAINT; Schema: public; Owner: ulearn
--

ALTER TABLE ONLY public."StepikExportProcesses"
    ADD CONSTRAINT "PK_StepikExportProcesses" PRIMARY KEY ("Id");


--
-- TOC entry 3444 (class 2606 OID 57297)
-- Name: StepikExportSlideAndStepMaps PK_StepikExportSlideAndStepMaps; Type: CONSTRAINT; Schema: public; Owner: ulearn
--

ALTER TABLE ONLY public."StepikExportSlideAndStepMaps"
    ADD CONSTRAINT "PK_StepikExportSlideAndStepMaps" PRIMARY KEY ("Id");


--
-- TOC entry 3446 (class 2606 OID 57302)
-- Name: StyleErrorSettings PK_StyleErrorSettings; Type: CONSTRAINT; Schema: public; Owner: ulearn
--

ALTER TABLE ONLY public."StyleErrorSettings"
    ADD CONSTRAINT "PK_StyleErrorSettings" PRIMARY KEY ("ErrorType");


--
-- TOC entry 3538 (class 2606 OID 57609)
-- Name: SystemAccesses PK_SystemAccesses; Type: CONSTRAINT; Schema: public; Owner: ulearn
--

ALTER TABLE ONLY public."SystemAccesses"
    ADD CONSTRAINT "PK_SystemAccesses" PRIMARY KEY ("Id");


--
-- TOC entry 3448 (class 2606 OID 57310)
-- Name: TempCourseErrors PK_TempCourseErrors; Type: CONSTRAINT; Schema: public; Owner: ulearn
--

ALTER TABLE ONLY public."TempCourseErrors"
    ADD CONSTRAINT "PK_TempCourseErrors" PRIMARY KEY ("CourseId");


--
-- TOC entry 3541 (class 2606 OID 57624)
-- Name: TempCourses PK_TempCourses; Type: CONSTRAINT; Schema: public; Owner: ulearn
--

ALTER TABLE ONLY public."TempCourses"
    ADD CONSTRAINT "PK_TempCourses" PRIMARY KEY ("CourseId");


--
-- TOC entry 3450 (class 2606 OID 57318)
-- Name: TextBlobs PK_TextBlobs; Type: CONSTRAINT; Schema: public; Owner: ulearn
--

ALTER TABLE ONLY public."TextBlobs"
    ADD CONSTRAINT "PK_TextBlobs" PRIMARY KEY ("Hash");


--
-- TOC entry 3453 (class 2606 OID 57328)
-- Name: UnitAppearances PK_UnitAppearances; Type: CONSTRAINT; Schema: public; Owner: ulearn
--

ALTER TABLE ONLY public."UnitAppearances"
    ADD CONSTRAINT "PK_UnitAppearances" PRIMARY KEY ("Id");


--
-- TOC entry 3660 (class 2606 OID 57975)
-- Name: UserExerciseSubmissions PK_UserExerciseSubmissions; Type: CONSTRAINT; Schema: public; Owner: ulearn
--

ALTER TABLE ONLY public."UserExerciseSubmissions"
    ADD CONSTRAINT "PK_UserExerciseSubmissions" PRIMARY KEY ("Id");


--
-- TOC entry 3544 (class 2606 OID 57636)
-- Name: UserFlashcardsUnlocking PK_UserFlashcardsUnlocking; Type: CONSTRAINT; Schema: public; Owner: ulearn
--

ALTER TABLE ONLY public."UserFlashcardsUnlocking"
    ADD CONSTRAINT "PK_UserFlashcardsUnlocking" PRIMARY KEY ("Id");


--
-- TOC entry 3547 (class 2606 OID 57648)
-- Name: UserFlashcardsVisits PK_UserFlashcardsVisits; Type: CONSTRAINT; Schema: public; Owner: ulearn
--

ALTER TABLE ONLY public."UserFlashcardsVisits"
    ADD CONSTRAINT "PK_UserFlashcardsVisits" PRIMARY KEY ("Id");


--
-- TOC entry 3550 (class 2606 OID 57663)
-- Name: UserQuestions PK_UserQuestions; Type: CONSTRAINT; Schema: public; Owner: ulearn
--

ALTER TABLE ONLY public."UserQuestions"
    ADD CONSTRAINT "PK_UserQuestions" PRIMARY KEY ("QuestionId");


--
-- TOC entry 3645 (class 2606 OID 57963)
-- Name: UserQuizAnswers PK_UserQuizAnswers; Type: CONSTRAINT; Schema: public; Owner: ulearn
--

ALTER TABLE ONLY public."UserQuizAnswers"
    ADD CONSTRAINT "PK_UserQuizAnswers" PRIMARY KEY ("Id");


--
-- TOC entry 3556 (class 2606 OID 57675)
-- Name: UserQuizSubmissions PK_UserQuizSubmissions; Type: CONSTRAINT; Schema: public; Owner: ulearn
--

ALTER TABLE ONLY public."UserQuizSubmissions"
    ADD CONSTRAINT "PK_UserQuizSubmissions" PRIMARY KEY ("Id");


--
-- TOC entry 3559 (class 2606 OID 57690)
-- Name: UserRoles PK_UserRoles; Type: CONSTRAINT; Schema: public; Owner: ulearn
--

ALTER TABLE ONLY public."UserRoles"
    ADD CONSTRAINT "PK_UserRoles" PRIMARY KEY ("Id");


--
-- TOC entry 3565 (class 2606 OID 57705)
-- Name: Visits PK_Visits; Type: CONSTRAINT; Schema: public; Owner: ulearn
--

ALTER TABLE ONLY public."Visits"
    ADD CONSTRAINT "PK_Visits" PRIMARY KEY ("Id");


--
-- TOC entry 3455 (class 2606 OID 57338)
-- Name: WorkQueueItems PK_WorkQueueItems; Type: CONSTRAINT; Schema: public; Owner: ulearn
--

ALTER TABLE ONLY public."WorkQueueItems"
    ADD CONSTRAINT "PK_WorkQueueItems" PRIMARY KEY ("Id");


--
-- TOC entry 3681 (class 2606 OID 58059)
-- Name: XQueueExerciseSubmissions PK_XQueueExerciseSubmissions; Type: CONSTRAINT; Schema: public; Owner: ulearn
--

ALTER TABLE ONLY public."XQueueExerciseSubmissions"
    ADD CONSTRAINT "PK_XQueueExerciseSubmissions" PRIMARY KEY ("Id");


--
-- TOC entry 3568 (class 2606 OID 57720)
-- Name: XQueueWatchers PK_XQueueWatchers; Type: CONSTRAINT; Schema: public; Owner: ulearn
--

ALTER TABLE ONLY public."XQueueWatchers"
    ADD CONSTRAINT "PK_XQueueWatchers" PRIMARY KEY ("Id");


--
-- TOC entry 3371 (class 2606 OID 57070)
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: ulearn
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- TOC entry 3726 (class 2606 OID 58444)
-- Name: __MigrationHistory PK_public.__MigrationHistory; Type: CONSTRAINT; Schema: public; Owner: ulearn
--

ALTER TABLE ONLY public."__MigrationHistory"
    ADD CONSTRAINT "PK_public.__MigrationHistory" PRIMARY KEY ("MigrationId", "ContextKey");










-- Временные изменения для того, чтобы pgloader справился с миграцией.

ALTER TABLE public."AspNetUsers"
    DROP COLUMN "Names";

ALTER TABLE public."AspNetUsers"
    ADD "Names" text COLLATE public.case_insensitive;

ALTER TABLE public."Likes"
    RENAME COLUMN "Id" TO "ID";