
//automatically generated by Tuto
using uLearn;
namespace AIML 
{
    [Slide(@"Исправление грубых ошибок","94a0af9e-8862-4c23-a89c-b6504626fa6f")]
    public class Исправление_грубых_ошибок
        {
		//#video GLAlC6YHbYI

        }
}