
//automatically generated by Tuto
using uLearn;
namespace UXR 
{
    [Slide(@"Примеры заданий для юзабилити-тестирования","b59bffa9-9b11-4ed5-9434-d69919ad9c77")]
    public class Примеры_заданий_для_юзабилити_тестирования
        {
		//#video eUms373QqD0

        }
}