
//automatically generated by Tuto
using uLearn;
namespace Parprog 
{
    [Slide(@"Работа с исключениями","76444954-281d-464f-9e5c-b3348f86e8c3")]
    public class Работа_с_исключениями
        {
		//#video CtpaZmt5EQI

        }
}