using Database.Extensions;
using Ulearn.Core;
using Ulearn.Core.Courses.Slides.Blocks;

#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Runtime Version:4.0.30319.42000
//
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uLearn.Web.Views.Course
{
	using System;
	using System.Collections.Generic;
	using System.IO;
	using System.Linq;
	using System.Net;
	using System.Text;
	using System.Web;
	using System.Web.Helpers;
	using System.Web.Mvc;
	using System.Web.Mvc.Ajax;
	using System.Web.Mvc.Html;
	using System.Web.Routing;
	using System.Web.Security;
	using System.Web.UI;
	using System.Web.WebPages;
	using Database.Models;
	using uLearn;
	using uLearn.Web.Extensions;
	using uLearn.Web.Models;
	using uLearn.Web.Views.Course;
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
	public static class AcceptedSolutionsHtml
	{

public static System.Web.WebPages.HelperResult AcceptedSolutions(AcceptedSolutionsPageModel model) {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {


															 

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "	<div id=\"LikeSolutionUrl\" data-url=\"");


WebViewPage.WriteTo(@__razor_helper_writer, model.LikeSolutionUrl);

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\"></div>\r\n");



WebViewPage.WriteLiteralTo(@__razor_helper_writer, "	<p>");


WebViewPage.WriteTo(@__razor_helper_writer, MvcHtmlString.Create(model.Slide.Exercise.CommentAfterExerciseIsSolved.RenderMarkdown(model.Slide.Info.SlideFile)));

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</p>\r\n");



WebViewPage.WriteLiteralTo(@__razor_helper_writer, "	<p>Изучите решения ваших коллег. Проголосуйте за решения, в которых вы нашли что" +
"-то новое для себя.</p>\r\n");


	foreach (var solution in model.AcceptedSolutions)
	{
		var id = "solution_" + solution.Id;
		var code = new CodeBlock(solution.Code, model.Slide.Exercise.Language);

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "		<div id=\"");


WebViewPage.WriteTo(@__razor_helper_writer, id);

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\">\r\n			<button class=\"like-left-location btn ");


WebViewPage.WriteTo(@__razor_helper_writer, solution.LikedAlready ? "btn-primary" : "btn-default");

WebViewPage.WriteLiteralTo(@__razor_helper_writer, " like-button\" onclick=\"likeSolution(");


																						  WebViewPage.WriteTo(@__razor_helper_writer, solution.Id);

WebViewPage.WriteLiteralTo(@__razor_helper_writer, ")\">\r\n				<i class=\"glyphicon glyphicon-heart\"></i>\r\n				<span class=\"likes-counte" +
"r\">");


WebViewPage.WriteTo(@__razor_helper_writer, solution.UsersWhoLike.Count);

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</span>\r\n			</button>\r\n\r\n");


 			if (model.User.HasAccessFor(model.CourseId, CourseRole.Instructor))
			{

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "				<form action=\"");


WebViewPage.WriteTo(@__razor_helper_writer, solution.RemoveSolutionUrl);

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\" method=\"POST\" novalidate=\"novalidate\">\r\n					<button class=\"btn btn-danger\">\r\n	" +
"					<i class=\"glyphicon glyphicon-remove\"></i>\r\n						Удалить решение\r\n					</b" +
"utton>\r\n				</form>\r\n");


			}

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\r\n			");


WebViewPage.WriteTo(@__razor_helper_writer, SlideHtml.Block(code, null, null));

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\r\n		</div>\r\n");


	}

});

}


	}
}
#pragma warning restore 1591
