#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uLearn.Web.Views.Course
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Database.Models;
    using log4net;
    using uLearn;
    using Ulearn.Common.Extensions;
    using uLearn.Model.Blocks;
    using uLearn.Quizes;
    using uLearn.Web;
    using uLearn.Web.Controllers;
    using uLearn.Web.Extensions;
    using uLearn.Web.Models;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public class SlideHtml : System.Web.WebPages.HelperPage
    {

#line default
#line hidden
public static System.Web.WebPages.HelperResult Slide(BlockRenderContext context, HtmlHelper Html, int currentScore = 0)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {
 

WriteLiteralTo(__razor_helper_writer, "\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"slide\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t<h1>\r\n");

WriteLiteralTo(__razor_helper_writer, "\t\t\t");

WriteTo(__razor_helper_writer, context.Slide.Title);

WriteLiteralTo(__razor_helper_writer, "\r\n\t\t\t<span");

WriteLiteralTo(__razor_helper_writer, " class=\"score\"");

WriteLiteralTo(__razor_helper_writer, ">");

  WriteTo(__razor_helper_writer, Score(currentScore, context.Slide.MaxScore));

WriteLiteralTo(__razor_helper_writer, "</span>\r\n\t\t</h1>\r\n");

WriteLiteralTo(__razor_helper_writer, "\t\t");

WriteTo(__razor_helper_writer, Blocks(context, Html));

WriteLiteralTo(__razor_helper_writer, "\r\n\t</div>\r\n");


});

#line default
#line hidden
}
#line default
#line hidden

#line default
#line hidden
public static System.Web.WebPages.HelperResult Blocks(BlockRenderContext context, HtmlHelper Html)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {
 
	var countHiddenBlocks = context.Slide.GetBlocksRangesWithSameVisibility().Count(b => b[0].Hide);
	var firstHiddenBlock = true;
	foreach (var blockRange in context.Slide.GetBlocksRangesWithSameVisibility())
	{
		if (!blockRange[0].Hide)
		{
			foreach (var block in blockRange)
			{
				
WriteTo(__razor_helper_writer, Block((dynamic)block, context, Html));

                                                     
			}
		}
		else if (context.RevealHidden)
		{

WriteLiteralTo(__razor_helper_writer, "\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"revealed\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n");

                
                 if (firstHiddenBlock)
                {
	                firstHiddenBlock = false;

WriteLiteralTo(__razor_helper_writer, "\t                <div");

WriteLiteralTo(__razor_helper_writer, " class=\"revealed__description\"");

WriteLiteralTo(__razor_helper_writer, ">Студенты не&nbsp;видят ");

                                                 WriteTo(__razor_helper_writer, countHiddenBlocks > 1 ? "синие блоки" : "этот блок");

WriteLiteralTo(__razor_helper_writer, "</div>\r\n");

                }

WriteLiteralTo(__razor_helper_writer, "                ");

                 foreach (var block in blockRange)
                {
	                
WriteTo(__razor_helper_writer, Block((dynamic)block, context, Html));

                                                         
                }

WriteLiteralTo(__razor_helper_writer, "            </div>\r\n");

		}
	}

});

#line default
#line hidden
}
#line default
#line hidden

#line default
#line hidden
public static System.Web.WebPages.HelperResult Block(AbstractQuestionBlock block, BlockRenderContext context, HtmlHelper Html)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {
 
	var mark = "";
	var style = "";
	var blockScore = -1;
	QuizBlockData model = context.GetBlockData(block);
	if (model.QuizState != QuizState.NotPassed && model.QuizState != QuizState.WaitForCheck && model.QuizState != QuizState.IsChecking)
	{
		if (model.QuizModel != null && model.QuizModel.ResultsForQuizes != null)
		{
			var res = model.QuizModel.ResultsForQuizes.TryGetValue(block.Id, out blockScore) && blockScore == block.MaxScore;
			mark = "glyphicon " + (res ? "glyphicon-ok" : "glyphicon-remove");
			style = "color: " + (res ? "green" : "red");
		}
	}

WriteLiteralTo(__razor_helper_writer, "\t<h4>\r\n\t\t<i");

WriteAttributeTo(__razor_helper_writer, "class", Tuple.Create(" class=\"", 2265), Tuple.Create("\"", 2278)
, Tuple.Create(Tuple.Create("", 2273), Tuple.Create<System.Object, System.Int32>(mark
, 2273), false)
);

WriteAttributeTo(__razor_helper_writer, "style", Tuple.Create(" style=\"", 2279), Tuple.Create("\"", 2293)
, Tuple.Create(Tuple.Create("", 2287), Tuple.Create<System.Object, System.Int32>(style
, 2287), false)
);

WriteLiteralTo(__razor_helper_writer, "></i>\r\n\t\t<span");

WriteLiteralTo(__razor_helper_writer, " class=\"quiz-block__text\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n");

WriteLiteralTo(__razor_helper_writer, "\t\t\t");

WriteTo(__razor_helper_writer, block.QuestionIndex);

WriteLiteralTo(__razor_helper_writer, ". ");

    WriteTo(__razor_helper_writer, block.Text.RenderTex().ToLegacyHtmlString());

WriteLiteralTo(__razor_helper_writer, "\r\n\t\t</span>\r\n\t\t<span");

WriteLiteralTo(__razor_helper_writer, " class=\"quiz-block__score\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n");

			
             if (blockScore >= 0)
			{

WriteLiteralTo(__razor_helper_writer, "\t\t\t\t<nobr>");

WriteTo(__razor_helper_writer, blockScore);

WriteLiteralTo(__razor_helper_writer, " из ");

       WriteTo(__razor_helper_writer, block.MaxScore);

WriteLiteralTo(__razor_helper_writer, " балл");

                            WriteTo(__razor_helper_writer,  block.MaxScore == 1 ? "а" : "ов");

WriteLiteralTo(__razor_helper_writer, "</nobr>\r\n");

			}
			else
			{

WriteLiteralTo(__razor_helper_writer, "\t\t\t\t<nobr>");

WriteTo(__razor_helper_writer, block.MaxScore.PluralizeInRussian(RussianPluralizationOptions.Score));

WriteLiteralTo(__razor_helper_writer, "</nobr>\r\n");

			}

WriteLiteralTo(__razor_helper_writer, "\t\t</span>\r\n\t</h4>\r\n");


	
WriteTo(__razor_helper_writer, QuizBlock((dynamic)block, context));

                                       
	if (context.ManualChecking != null)
	{

WriteLiteralTo(__razor_helper_writer, "\t\t<h4>Оцените от 0 до ");

WriteTo(__razor_helper_writer, block.MaxScore);

WriteLiteralTo(__razor_helper_writer, "</h4>\r\n");

WriteLiteralTo(__razor_helper_writer, "\t\t<div>\r\n\t\t\t<input");

WriteLiteralTo(__razor_helper_writer, " type=\"number\"");

WriteLiteralTo(__razor_helper_writer, " class=\"form-control\"");

WriteLiteralTo(__razor_helper_writer, " min=\"0\"");

WriteAttributeTo(__razor_helper_writer, "max", Tuple.Create(" max=\"", 2897), Tuple.Create("\"", 2918)
, Tuple.Create(Tuple.Create("", 2903), Tuple.Create<System.Object, System.Int32>(block.MaxScore
, 2903), false)
);

WriteAttributeTo(__razor_helper_writer, "name", Tuple.Create(" name=\"", 2919), Tuple.Create("\"", 2951)
, Tuple.Create(Tuple.Create("", 2926), Tuple.Create("quiz__score__", 2926), true)
                        , Tuple.Create(Tuple.Create("", 2939), Tuple.Create<System.Object, System.Int32>( block.Id
, 2939), false)
);

WriteLiteralTo(__razor_helper_writer, "/>\r\n\t\t</div>\r\n");

	}


WriteLiteralTo(__razor_helper_writer, "\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"quiz-block-delimiter\"");

WriteLiteralTo(__razor_helper_writer, "></div>\r\n");


});

#line default
#line hidden
}
#line default
#line hidden

#line default
#line hidden
public static System.Web.WebPages.HelperResult Score(int currentScore, int maxScore)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {
  
WriteTo(__razor_helper_writer,  maxScore == 0 ? "" : string.Format("{0}/{1}", currentScore, maxScore));

                                                                            
});

#line default
#line hidden
}
#line default
#line hidden

#line default
#line hidden
public static System.Web.WebPages.HelperResult Block(MdBlock block, BlockRenderContext context, HtmlHelper Html)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {
 
	
WriteTo(__razor_helper_writer, MvcHtmlString.Create(block.RenderMd(context.Course.Id, context.Slide.Id, context.BaseUrl)));

                                                                                               

});

#line default
#line hidden
}
#line default
#line hidden

#line default
#line hidden
public static System.Web.WebPages.HelperResult Block(CodeBlock block, BlockRenderContext context, HtmlHelper Html)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {
 

WriteLiteralTo(__razor_helper_writer, "\t<textarea");

WriteLiteralTo(__razor_helper_writer, " class=\"code code-sample\"");

WriteLiteralTo(__razor_helper_writer, " data-lang=\"");

                    WriteTo(__razor_helper_writer, block.LangId);

WriteLiteralTo(__razor_helper_writer, "\"");

WriteLiteralTo(__razor_helper_writer, " data-ver=\"");

                                             WriteTo(__razor_helper_writer, block.LangVer);

WriteLiteralTo(__razor_helper_writer, "\"");

WriteLiteralTo(__razor_helper_writer, ">");

                                                             WriteTo(__razor_helper_writer, block.Code);

WriteLiteralTo(__razor_helper_writer, "</textarea>\r\n");


});

#line default
#line hidden
}
#line default
#line hidden

#line default
#line hidden
public static System.Web.WebPages.HelperResult Block(TexBlock block, BlockRenderContext context, HtmlHelper Html)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {
 
	foreach (var texLine in block.TexLines)
	{

WriteLiteralTo(__razor_helper_writer, "\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"tex\"");

WriteLiteralTo(__razor_helper_writer, ">\\displaystyle ");

         WriteTo(__razor_helper_writer, texLine.Trim());

WriteLiteralTo(__razor_helper_writer, "</div>\r\n");

	}

});

#line default
#line hidden
}
#line default
#line hidden

#line default
#line hidden
public static System.Web.WebPages.HelperResult Block(YoutubeBlock block, BlockRenderContext context, HtmlHelper Html)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {
 

WriteLiteralTo(__razor_helper_writer, "\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"video-container\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"youtube-video\"");

WriteLiteralTo(__razor_helper_writer, " data-width=\"864\"");

WriteLiteralTo(__razor_helper_writer, " data-height=\"480\"");

WriteLiteralTo(__razor_helper_writer, " data-video-id=\"");

                                                       WriteTo(__razor_helper_writer, block.VideoId);

WriteLiteralTo(__razor_helper_writer, "\"");

WriteLiteralTo(__razor_helper_writer, " data-autoplay=\"");

                                                                                      WriteTo(__razor_helper_writer, context.Autoplay.ToString().ToLower());

WriteLiteralTo(__razor_helper_writer, "\"");

WriteLiteralTo(__razor_helper_writer, "></div>\r\n\t</div>\r\n");

WriteLiteralTo(__razor_helper_writer, "\t<div>\r\n\t\t<a");

WriteLiteralTo(__razor_helper_writer, " href=\"javascript://\"");

WriteLiteralTo(__razor_helper_writer, " class=\"popover-trigger pull-right\"");

WriteLiteralTo(__razor_helper_writer, "\r\n\t\t\ttitle=\"Как ускорить видео?\"");

WriteLiteralTo(__razor_helper_writer, "\r\n\t\t\tdata-content=\"Выберите скорость в иконке с шестеренкой или используйте горяч" +
"ие клавиши Shift+> и Shift+<\"");

WriteLiteralTo(__razor_helper_writer, "\r\n\t\t\tdata-placement=\"bottom\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t\t<span");

WriteLiteralTo(__razor_helper_writer, " class=\"glyphicon glyphicon-question-sign\"");

WriteLiteralTo(__razor_helper_writer, "></span>\r\n\t\t\tУскорить видео?\r\n\t\t</a>\r\n\t</div>\r\n");


});

#line default
#line hidden
}
#line default
#line hidden

#line default
#line hidden
public static System.Web.WebPages.HelperResult Block(ImageGaleryBlock block, BlockRenderContext context, HtmlHelper Html)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {
 

WriteLiteralTo(__razor_helper_writer, "\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"flexslider\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t<ul");

WriteLiteralTo(__razor_helper_writer, " class=\"slides\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n");

			
             foreach (var imageUrl in block.ImageUrls)
			{

WriteLiteralTo(__razor_helper_writer, "\t\t\t\t<li>\r\n\t\t\t\t\t<img");

WriteAttributeTo(__razor_helper_writer, "src", Tuple.Create(" src=\"", 4548), Tuple.Create("\"", 4606)
, Tuple.Create(Tuple.Create("", 4554), Tuple.Create<System.Object, System.Int32>(string.Format("{0}/{1}", context.BaseUrl, imageUrl)
, 4554), false)
);

WriteAttributeTo(__razor_helper_writer, "alt", Tuple.Create(" alt=\"", 4607), Tuple.Create("\"", 4622)
         , Tuple.Create(Tuple.Create("", 4613), Tuple.Create<System.Object, System.Int32>(imageUrl
, 4613), false)
);

WriteLiteralTo(__razor_helper_writer, "/>\r\n\t\t\t\t</li>\r\n");

			}

WriteLiteralTo(__razor_helper_writer, "\t\t</ul>\r\n\t</div>\r\n");


});

#line default
#line hidden
}
#line default
#line hidden

#line default
#line hidden
public static System.Web.WebPages.HelperResult CodeTextArea(string initialCode, string langId, string runSolutionUrl)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {
 

WriteLiteralTo(__razor_helper_writer, "\t<textarea");

WriteLiteralTo(__razor_helper_writer, " class=\"code code-exercise\"");

WriteLiteralTo(__razor_helper_writer, " data-lang=\"");

                      WriteTo(__razor_helper_writer, langId);

WriteLiteralTo(__razor_helper_writer, "\"");

WriteLiteralTo(__razor_helper_writer, ">");

                               WriteTo(__razor_helper_writer, initialCode);

WriteLiteralTo(__razor_helper_writer, "</textarea>\r\n");

WriteLiteralTo(__razor_helper_writer, "\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"solution-control btn-group ctrl-group\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t<button");

WriteLiteralTo(__razor_helper_writer, " type=\"button\"");

WriteLiteralTo(__razor_helper_writer, " class=\"run-solution-button btn btn-primary no-rounds\"");

WriteLiteralTo(__razor_helper_writer, " data-url=\"");

                                                                WriteTo(__razor_helper_writer, runSolutionUrl);

WriteLiteralTo(__razor_helper_writer, "\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t\tRun\r\n\t\t</button>\r\n\t</div>\r\n");


	
WriteTo(__razor_helper_writer, RunErrors());

                

});

#line default
#line hidden
}
#line default
#line hidden

#line default
#line hidden
public static System.Web.WebPages.HelperResult Block(ExerciseBlock block, BlockRenderContext context, HtmlHelper Html)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {
 

WriteLiteralTo(__razor_helper_writer, "\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"exercise\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n");

		
          
			ExerciseBlockData data = context.GetBlockData(block) ?? new ExerciseBlockData(context.Course.Id, context.Slide as ExerciseSlide) { IsGuest = context.IsGuest, IsLti = context.IsLti };
			var manualCheckingId = context.ManualChecking != null ? (int?)context.ManualChecking.Id : null;

			if (Html != null)
			{
				
WriteTo(__razor_helper_writer, Html.Action("Submission", "Exercise", new { courseId = context.Course.Id, slideId = context.Slide.Id, submissionId = context.VersionId, manualCheckingId = manualCheckingId, isLti = data.IsLti, instructorView = manualCheckingId != null }));

                                                                                                                                                                                                                                                              
			}
			else
			{

WriteLiteralTo(__razor_helper_writer, "\t\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"exercise__submission\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t\t\t\t<textarea");

WriteLiteralTo(__razor_helper_writer, " class=\"code code-exercise hidden\"");

WriteLiteralTo(__razor_helper_writer, " data-lang=\"");

                                             WriteTo(__razor_helper_writer, block.LangId);

WriteLiteralTo(__razor_helper_writer, "\"");

WriteLiteralTo(__razor_helper_writer, ">");

                                                             WriteTo(__razor_helper_writer,  block.ExerciseInitialCode.EnsureEnoughLines(4));

WriteLiteralTo(__razor_helper_writer, "</textarea>\r\n\t\t\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"loading-spinner\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t\t\t\t\t<img");

WriteLiteralTo(__razor_helper_writer, " src=\"/Content/loading.gif\"");

WriteLiteralTo(__razor_helper_writer, "/>\r\n\t\t\t\t\t</div>\r\n");

WriteLiteralTo(__razor_helper_writer, "\t\t\t\t\t");

WriteTo(__razor_helper_writer, ExerciseControls(new ExerciseControlsModel(context.Course.Id, (ExerciseSlide)context.Slide)
					{
						IsLti = context.IsLti,
						IsCodeEditableAndSendable = true,
						DebugView = data.DebugView,
						RunSolutionUrl = data.RunSolutionUrl,
					}));

WriteLiteralTo(__razor_helper_writer, "\r\n\r\n");

WriteLiteralTo(__razor_helper_writer, "\t\t\t\t\t");

WriteTo(__razor_helper_writer, RunErrors());

WriteLiteralTo(__razor_helper_writer, "\r\n\t\t\t\t</div>\r\n");

			}
		
WriteLiteralTo(__razor_helper_writer, "\r\n\r\n");

		
         if (data.DebugView)
		{

WriteLiteralTo(__razor_helper_writer, "\t\t\t<div>\r\n\t\t\t\t<h3>Подсказки</h3>\r\n\t\t\t\t<ol>\r\n");

					
                     foreach (var hint in data.Block.HintsMd)
					{

WriteLiteralTo(__razor_helper_writer, "\t\t\t\t\t\t<li>\r\n");

WriteLiteralTo(__razor_helper_writer, "\t\t\t\t\t\t\t");

WriteTo(__razor_helper_writer, MvcHtmlString.Create(hint.RenderMd(context.BaseUrl)));

WriteLiteralTo(__razor_helper_writer, "\r\n\t\t\t\t\t\t</li>\r\n");

					}

WriteLiteralTo(__razor_helper_writer, "\t\t\t\t</ol>\r\n\t\t\t\t<h3>Комментарий после решения</h3>\r\n\t\t\t\t<p>");

WriteTo(__razor_helper_writer, data.Block.CommentAfterExerciseIsSolved);

WriteLiteralTo(__razor_helper_writer, "</p>\r\n\t\t\t</div>\r\n");

		}

WriteLiteralTo(__razor_helper_writer, "\r\n");

		
         if (context.ManualChecking != null)
		{
			var checking = (ManualExerciseChecking)context.ManualChecking;

			
WriteTo(__razor_helper_writer, Html.Partial(
				"~/Views/Exercise/_ExerciseScoreForm.cshtml",
				new ExerciseScoreFormModel(
					context.Course.Id,
					(ExerciseSlide)context.Slide,
					checking,
					context.ManualCheckingsLeft,
					context.GroupsIds,
					isCurrentSubmissionChecking: (context.VersionId == null || checking.Submission.Id == context.VersionId) && !context.IsManualCheckingReadonly,
					defaultProhibitFutherReview: context.DefaultProhibitFutherReview
					)));

                      
		}

WriteLiteralTo(__razor_helper_writer, "\t</div>\r\n");


});

#line default
#line hidden
}
#line default
#line hidden

#line default
#line hidden
public static System.Web.WebPages.HelperResult QuizBlock(ChoiceBlock block, BlockRenderContext context)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {
 
	var items = block.ShuffledItems();
	var isMultiply = block.Multiple;
	var typeInp = isMultiply ? "checkbox" : "radio";
	QuizBlockData model = context.GetBlockData(block) ?? new QuizBlockData(new QuizModel(), 1, QuizState.NotPassed);

WriteLiteralTo(__razor_helper_writer, "\t<div");

WriteAttributeTo(__razor_helper_writer, "class", Tuple.Create(" class=\"", 7583), Tuple.Create("\"", 7632)
, Tuple.Create(Tuple.Create("", 7591), Tuple.Create("quiz-block-mark", 7591), true)
, Tuple.Create(Tuple.Create(" ", 7606), Tuple.Create<System.Object, System.Int32>(typeInp
, 7607), false)
, Tuple.Create(Tuple.Create(" ", 7615), Tuple.Create<System.Object, System.Int32>(typeInp
, 7616), false)
, Tuple.Create(Tuple.Create("", 7624), Tuple.Create("-default", 7624), true)
);

WriteAttributeTo(__razor_helper_writer, "id", Tuple.Create(" id=\'", 7633), Tuple.Create("\'", 7665)
, Tuple.Create(Tuple.Create("", 7638), Tuple.Create<System.Object, System.Int32>( block.Id + "_quizBlock"
, 7638), false)
);

WriteLiteralTo(__razor_helper_writer, ">\r\n");

		
         for (var itemIndex = 0; itemIndex < items.Length; itemIndex++)
		{
			var item = items[itemIndex];
			var id = isMultiply ? itemIndex + "noMult" : model.BlockIndex.ToString();
			var itemChecked = model.QuizState != QuizState.NotPassed && model.QuizModel.AnswersToQuizes[block.Id].Select(x => x.ItemId).Contains(item.Id);
			var ans = itemChecked ? "checked" : "";
			var itemClass = "";
			var title = "";
			var readonlyAttr = context.CanUserFillQuiz ? "" : "disabled";
			if (model.QuizState == QuizState.Total)
			{
				itemClass = item.IsCorrect ? "right-quiz" : itemChecked ? "wrong-quiz" : "";
				title = (item.IsCorrect ? "Правильный" : "Неправильный") + " вариант";
			}

WriteLiteralTo(__razor_helper_writer, "\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"quiz\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t\t\t<input ");

WriteTo(__razor_helper_writer, ans);

WriteLiteralTo(__razor_helper_writer, " autocomplete=\"off\" id=\'");

                      WriteTo(__razor_helper_writer,  block.Id + "quizBlock" + item.Id);

WriteLiteralTo(__razor_helper_writer, "\' name=");

                                                                 WriteTo(__razor_helper_writer,  "group" + id);

WriteLiteralTo(__razor_helper_writer, " type=\"");

                                                                                       WriteTo(__razor_helper_writer, typeInp);

WriteLiteralTo(__razor_helper_writer, "\" ");

                                                                                                 WriteTo(__razor_helper_writer, GetGuestDisable(context.IsGuest));

WriteLiteralTo(__razor_helper_writer, " ");

                                                                                                                                   WriteTo(__razor_helper_writer, readonlyAttr);

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t\t\t<label");

WriteAttributeTo(__razor_helper_writer, "class", Tuple.Create(" class=\"", 8565), Tuple.Create("\"", 8583)
, Tuple.Create(Tuple.Create("", 8573), Tuple.Create<System.Object, System.Int32>(itemClass
, 8573), false)
);

WriteAttributeTo(__razor_helper_writer, "title", Tuple.Create(" title=\"", 8584), Tuple.Create("\"", 8598)
, Tuple.Create(Tuple.Create("", 8592), Tuple.Create<System.Object, System.Int32>(title
, 8592), false)
);

WriteAttributeTo(__razor_helper_writer, "for", Tuple.Create(" for=\"", 8599), Tuple.Create("\"", 8641)
, Tuple.Create(Tuple.Create("", 8605), Tuple.Create<System.Object, System.Int32>( block.Id + "quizBlock" + item.Id
, 8605), false)
);

WriteLiteralTo(__razor_helper_writer, " ");

                                                                      WriteTo(__razor_helper_writer, GetGuestOnclick(context.IsGuest));

WriteLiteralTo(__razor_helper_writer, ">\r\n");

WriteLiteralTo(__razor_helper_writer, "\t\t\t\t\t");

WriteTo(__razor_helper_writer, item.Description.Trim().RenderTex().ToLegacyHtmlString());

WriteLiteralTo(__razor_helper_writer, "\r\n");

					
                     if (model.ShowCorrectAnswers && item.IsCorrect)
					{

WriteLiteralTo(__razor_helper_writer, "\t\t\t\t\t\t<i");

WriteLiteralTo(__razor_helper_writer, " class=\"glyphicon glyphicon-ok\"");

WriteLiteralTo(__razor_helper_writer, " style=\"color: green\"");

WriteAttributeTo(__razor_helper_writer, "title", Tuple.Create(" title=\"", 8866), Tuple.Create("\"", 8880)
      , Tuple.Create(Tuple.Create("", 8874), Tuple.Create<System.Object, System.Int32>(title
, 8874), false)
);

WriteLiteralTo(__razor_helper_writer, "></i>\r\n");

					}

WriteLiteralTo(__razor_helper_writer, "\t\t\t\t</label>\r\n");

				
                 if (model.ShowExplanations && !string.IsNullOrEmpty(item.Explanation))
				{

WriteLiteralTo(__razor_helper_writer, "\t\t\t\t\t<p");

WriteLiteralTo(__razor_helper_writer, " class=\"quiz__explanation\"");

WriteLiteralTo(__razor_helper_writer, ">");

                   WriteTo(__razor_helper_writer, item.Explanation);

WriteLiteralTo(__razor_helper_writer, "</p>\r\n");

				}

WriteLiteralTo(__razor_helper_writer, "\t\t\t</div>\r\n");

		}

WriteLiteralTo(__razor_helper_writer, "\t</div>\r\n");


});

#line default
#line hidden
}
#line default
#line hidden

#line default
#line hidden
public static System.Web.WebPages.HelperResult QuizBlock(FillInBlock block, BlockRenderContext context)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {
 
	var value = "";
	var quizRes = "";
	QuizBlockData model = context.GetBlockData(block) ?? new QuizBlockData(new QuizModel(), 1, QuizState.NotPassed);
	if (model.QuizState != QuizState.NotPassed && model.QuizModel.AnswersToQuizes[block.Id].FirstOrDefault() != null)
	{
		var answers = model.QuizModel.AnswersToQuizes[block.Id];
		var userAnswer = answers.FirstOrDefault();
		value = userAnswer.Text;
		quizRes = model.QuizState == QuizState.Total
			? (userAnswer.IsRightAnswer ? "right-quiz" : "wrong-quiz") : "";
	}
	var sample = block.Sample;
	var readonlyAttr = context.CanUserFillQuiz ? "" : "readonly";

WriteLiteralTo(__razor_helper_writer, "\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"quiz quiz-block-input\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t<label ");

WriteTo(__razor_helper_writer, GetGuestOnclick(context.IsGuest));

WriteLiteralTo(__razor_helper_writer, ">\r\n");

			
             if (block.Multiline)
			{

WriteLiteralTo(__razor_helper_writer, "\t\t\t\t<textarea");

WriteAttributeTo(__razor_helper_writer, "class", Tuple.Create(" class=\"", 9906), Tuple.Create("\"", 9935)
, Tuple.Create(Tuple.Create("", 9914), Tuple.Create("form-control", 9914), true)
, Tuple.Create(Tuple.Create(" ", 9926), Tuple.Create<System.Object, System.Int32>(quizRes
, 9927), false)
);

WriteAttributeTo(__razor_helper_writer, "id", Tuple.Create(" id=\'", 9936), Tuple.Create("\'", 9967)
, Tuple.Create(Tuple.Create("", 9941), Tuple.Create<System.Object, System.Int32>( block.Id + "quizBlock"
, 9941), false)
);

WriteAttributeTo(__razor_helper_writer, "maxlength", Tuple.Create(" maxlength=\"", 9968), Tuple.Create("\"", 10014)
                   , Tuple.Create(Tuple.Create("", 9980), Tuple.Create<System.Object, System.Int32>(QuizController.MaxFillinblockSize
, 9980), false)
);

WriteLiteralTo(__razor_helper_writer, " ");

                                                                                                         WriteTo(__razor_helper_writer, GetGuestDisable(context.IsGuest));

WriteLiteralTo(__razor_helper_writer, " ");

                                                                                                                                           WriteTo(__razor_helper_writer, readonlyAttr);

WriteLiteralTo(__razor_helper_writer, " cols=\"70\" rows=\"5\">");

                                                                                                                                                                            WriteTo(__razor_helper_writer, value);

WriteLiteralTo(__razor_helper_writer, "</textarea>\r\n");

			}
			else
			{

WriteLiteralTo(__razor_helper_writer, "\t\t\t\t<input\r\n\t\t\t\t\tautocomplete=\"off\"\r\n\t\t\t\t\tclass=\"form-control ");

          WriteTo(__razor_helper_writer, quizRes);

WriteLiteralTo(__razor_helper_writer, "\"\r\n\t\t\t\t\tvalue=\"");

WriteTo(__razor_helper_writer, value);

WriteLiteralTo(__razor_helper_writer, "\" id=\'");

          WriteTo(__razor_helper_writer,  block.Id + "quizBlock");

WriteLiteralTo(__razor_helper_writer, "\'\r\n\t\t\t\t\tmaxlength=\"");

 WriteTo(__razor_helper_writer, QuizController.MaxFillinblockSize);

WriteLiteralTo(__razor_helper_writer, "\"\r\n\t\t\t\t\tsize=\"68\"\r\n");

WriteLiteralTo(__razor_helper_writer, "\t\t\t\t\t");

WriteTo(__razor_helper_writer, GetGuestDisable(context.IsGuest));

WriteLiteralTo(__razor_helper_writer, "\r\n");

WriteLiteralTo(__razor_helper_writer, "\t\t\t\t\t");

WriteTo(__razor_helper_writer, readonlyAttr);

WriteLiteralTo(__razor_helper_writer, "/>\r\n");

			}

WriteLiteralTo(__razor_helper_writer, "\t\t</label>\r\n\t</div>\r\n");

	if (model.QuizState == QuizState.Total)
	{
		if (model.ShowCorrectAnswers)
		{

WriteLiteralTo(__razor_helper_writer, "\t\t\t<div>Правильный ответ: ");

     WriteTo(__razor_helper_writer, sample);

WriteLiteralTo(__razor_helper_writer, "</div>\r\n");

		}
		if (model.ShowExplanations && !string.IsNullOrEmpty(block.Explanation))
		{

WriteLiteralTo(__razor_helper_writer, "\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"text-muted\"");

WriteLiteralTo(__razor_helper_writer, ">");

      WriteTo(__razor_helper_writer, block.Explanation);

WriteLiteralTo(__razor_helper_writer, "</div>\r\n");

		}
	}

});

#line default
#line hidden
}
#line default
#line hidden

#line default
#line hidden
public static System.Web.WebPages.HelperResult QuizBlock(IsTrueBlock block, BlockRenderContext context)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {
 
	var tchecked = "";
	var fchecked = "";
	var trueItemClass = "";
	var falseItemClass = "";
	var ttitle = "";
	var ftitle = "";
	QuizBlockData model = context.GetBlockData(block) ?? new QuizBlockData(new QuizModel(), 1, QuizState.NotPassed);
	if (model.QuizState != QuizState.NotPassed && model.QuizModel.AnswersToQuizes[block.Id].FirstOrDefault() != null)
	{
		var userAnswer = model.QuizModel.AnswersToQuizes[block.Id].Select(x => x.Text).FirstOrDefault() == "True";
		tchecked = userAnswer ? "checked" : "";
		fchecked = userAnswer ? "" : "checked";
		if (model.QuizState == QuizState.Total)
		{
			trueItemClass = block.Answer ? "right-quiz" : userAnswer ? "wrong-quiz" : "";
			falseItemClass = !block.Answer ? "right-quiz" : !userAnswer ? "wrong-quiz" : "";
		}
	}
	if (model.QuizState == QuizState.Total)
	{
		ttitle = (block.Answer ? "Правильный" : "Неправильный") + " вариант";
		ftitle = (!block.Answer ? "Правильный" : "Неправильный") + " вариант";
	}
	var readonlyAttr = context.CanUserFillQuiz ? "" : "disabled";

WriteLiteralTo(__razor_helper_writer, "\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"radio quiz-block-mark\"");

WriteAttributeTo(__razor_helper_writer, "id", Tuple.Create(" id=\"", 11837), Tuple.Create("\"", 11869)
, Tuple.Create(Tuple.Create("", 11842), Tuple.Create<System.Object, System.Int32>( block.Id + "_quizBlock"
, 11842), false)
);

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"quiz\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t\t<input");

WriteLiteralTo(__razor_helper_writer, " autocomplete=\"off\"");

WriteLiteralTo(__razor_helper_writer, " ");

        WriteTo(__razor_helper_writer, tchecked);

WriteLiteralTo(__razor_helper_writer, " id=\'");

                       WriteTo(__razor_helper_writer,  block.Id + "quizBlock" + "True");

WriteLiteralTo(__razor_helper_writer, "\' name=\'");

                                                                  WriteTo(__razor_helper_writer,  block.Id + "group");

WriteLiteralTo(__razor_helper_writer, "\' type=\"radio\" ");

                                                                                                      WriteTo(__razor_helper_writer, GetGuestDisable(context.IsGuest));

WriteLiteralTo(__razor_helper_writer, " ");

                                                                                                                                        WriteTo(__razor_helper_writer, readonlyAttr);

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t\t<label");

WriteAttributeTo(__razor_helper_writer, "class", Tuple.Create(" class=\"", 12077), Tuple.Create("\"", 12099)
, Tuple.Create(Tuple.Create("", 12085), Tuple.Create<System.Object, System.Int32>(trueItemClass
, 12085), false)
);

WriteAttributeTo(__razor_helper_writer, "title", Tuple.Create(" title=\"", 12100), Tuple.Create("\"", 12115)
, Tuple.Create(Tuple.Create("", 12108), Tuple.Create<System.Object, System.Int32>(ttitle
, 12108), false)
);

WriteAttributeTo(__razor_helper_writer, "for", Tuple.Create(" for=\"", 12116), Tuple.Create("\"", 12157)
, Tuple.Create(Tuple.Create("", 12122), Tuple.Create<System.Object, System.Int32>( block.Id + "quizBlock" + "True"
, 12122), false)
);

WriteLiteralTo(__razor_helper_writer, " ");

                                                                      WriteTo(__razor_helper_writer, GetGuestOnclick(context.IsGuest));

WriteLiteralTo(__razor_helper_writer, ">Верно</label>\r\n");

			
             if (model.ShowCorrectAnswers && block.Answer)
			{

WriteLiteralTo(__razor_helper_writer, "\t\t\t\t<i");

WriteLiteralTo(__razor_helper_writer, " class=\"glyphicon glyphicon-ok\"");

WriteLiteralTo(__razor_helper_writer, " style=\"color: green\"");

WriteAttributeTo(__razor_helper_writer, "title", Tuple.Create(" title=\"", 12323), Tuple.Create("\"", 12338)
, Tuple.Create(Tuple.Create("", 12331), Tuple.Create<System.Object, System.Int32>(ttitle
, 12331), false)
);

WriteLiteralTo(__razor_helper_writer, "></i>\r\n");

			}

WriteLiteralTo(__razor_helper_writer, "\t\t</div>\r\n\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"quiz\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t\t<input");

WriteLiteralTo(__razor_helper_writer, " autocomplete=\"off\"");

WriteLiteralTo(__razor_helper_writer, " ");

        WriteTo(__razor_helper_writer, fchecked);

WriteLiteralTo(__razor_helper_writer, " id=\'");

                       WriteTo(__razor_helper_writer,  block.Id + "quizBlock" + "False");

WriteLiteralTo(__razor_helper_writer, "\' name=\'");

                                                                   WriteTo(__razor_helper_writer,  block.Id + "group");

WriteLiteralTo(__razor_helper_writer, "\' type=\"radio\" ");

                                                                                                       WriteTo(__razor_helper_writer, GetGuestDisable(context.IsGuest));

WriteLiteralTo(__razor_helper_writer, " ");

                                                                                                                                         WriteTo(__razor_helper_writer, readonlyAttr);

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t\t<label");

WriteAttributeTo(__razor_helper_writer, "class", Tuple.Create(" class=\"", 12567), Tuple.Create("\"", 12590)
, Tuple.Create(Tuple.Create("", 12575), Tuple.Create<System.Object, System.Int32>(falseItemClass
, 12575), false)
);

WriteAttributeTo(__razor_helper_writer, "title", Tuple.Create(" title=\"", 12591), Tuple.Create("\"", 12606)
, Tuple.Create(Tuple.Create("", 12599), Tuple.Create<System.Object, System.Int32>(ftitle
, 12599), false)
);

WriteAttributeTo(__razor_helper_writer, "for", Tuple.Create(" for=\"", 12607), Tuple.Create("\"", 12649)
, Tuple.Create(Tuple.Create("", 12613), Tuple.Create<System.Object, System.Int32>( block.Id + "quizBlock" + "False"
, 12613), false)
);

WriteLiteralTo(__razor_helper_writer, " ");

                                                                        WriteTo(__razor_helper_writer, GetGuestOnclick(context.IsGuest));

WriteLiteralTo(__razor_helper_writer, ">Неверно</label>\r\n");

			
             if (model.ShowCorrectAnswers && !block.Answer)
			{

WriteLiteralTo(__razor_helper_writer, "\t\t\t\t<i");

WriteLiteralTo(__razor_helper_writer, " class=\"glyphicon glyphicon-ok\"");

WriteLiteralTo(__razor_helper_writer, " style=\"color: green\"");

WriteAttributeTo(__razor_helper_writer, "title", Tuple.Create(" title=\"", 12818), Tuple.Create("\"", 12833)
, Tuple.Create(Tuple.Create("", 12826), Tuple.Create<System.Object, System.Int32>(ftitle
, 12826), false)
);

WriteLiteralTo(__razor_helper_writer, "></i>\r\n");

			}

WriteLiteralTo(__razor_helper_writer, "\t\t</div>\r\n\t</div>\r\n");

	if (model.ShowExplanations && !string.IsNullOrEmpty(block.Explanation))
	{

WriteLiteralTo(__razor_helper_writer, "\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"text-muted\"");

WriteLiteralTo(__razor_helper_writer, ">");

  WriteTo(__razor_helper_writer, block.Explanation);

WriteLiteralTo(__razor_helper_writer, "</div>\r\n");

	}

});

#line default
#line hidden
}
#line default
#line hidden

#line default
#line hidden
public static System.Web.WebPages.HelperResult QuizBlock(OrderingBlock block, BlockRenderContext context)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {
 
	var items = block.ShuffledItems();
	var correctItems = block.Items;
	QuizBlockData model = context.GetBlockData(block) ?? new QuizBlockData(new QuizModel(), 1, QuizState.NotPassed);
	if (model.QuizState != QuizState.NotPassed && model.QuizModel.AnswersToQuizes[block.Id].FirstOrDefault() != null)
	{
		var userAnswers = model.QuizModel.AnswersToQuizes[block.Id].Select(x => x.ItemId).ToList();
		items = items.OrderBy(item => userAnswers.IndexOf(item.GetHash())).ToArray();
	}

WriteLiteralTo(__razor_helper_writer, "\t<div");

WriteAttributeTo(__razor_helper_writer, "class", Tuple.Create(" class=\"", 13567), Tuple.Create("\"", 13643)
, Tuple.Create(Tuple.Create("", 13575), Tuple.Create("quiz-block-ordering", 13575), true)
, Tuple.Create(Tuple.Create(" ", 13594), Tuple.Create<System.Object, System.Int32>( context.CanUserFillQuiz ? "" : "not-movable"
, 13595), false)
);

WriteAttributeTo(__razor_helper_writer, "id", Tuple.Create(" id=\'", 13644), Tuple.Create("\'", 13676)
          , Tuple.Create(Tuple.Create("", 13649), Tuple.Create<System.Object, System.Int32>( block.Id + "_quizBlock"
, 13649), false)
);

WriteLiteralTo(__razor_helper_writer, " ");

                                                                                         WriteTo(__razor_helper_writer, GetGuestOnclick(context.IsGuest));

WriteLiteralTo(__razor_helper_writer, ">\r\n");

		
         if (model.ShowCorrectAnswers)
		{

WriteLiteralTo(__razor_helper_writer, "\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"quiz-block-ordering__correct-description row\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"text-success col-sm-5 col-sm-offset-6\"");

WriteLiteralTo(__razor_helper_writer, ">Правильный ответ</div>\r\n\t\t\t</div>\r\n");

		}

WriteLiteralTo(__razor_helper_writer, "\t\t<ul>\r\n");

			
             for (var itemIndex = 0; itemIndex < items.Length; itemIndex++)
			{
				var item = items[itemIndex];

WriteLiteralTo(__razor_helper_writer, "\t\t\t\t<li");

WriteLiteralTo(__razor_helper_writer, " class=\"row\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"quiz quiz-block-ordering__item col-xs-12 col-sm-5\"");

WriteLiteralTo(__razor_helper_writer, " data-item-id=\"");

                                                                   WriteTo(__razor_helper_writer, item.GetHash());

WriteLiteralTo(__razor_helper_writer, "\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n");

						
                         if (context.CanUserFillQuiz)
						{

WriteLiteralTo(__razor_helper_writer, "\t\t\t\t\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"quiz-block-ordering__item__icons\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t\t\t\t\t\t\t<span");

WriteLiteralTo(__razor_helper_writer, " class=\"glyphicon glyphicon-arrow-up\"");

WriteLiteralTo(__razor_helper_writer, "></span>\r\n\t\t\t\t\t\t\t\t<span");

WriteLiteralTo(__razor_helper_writer, " class=\"glyphicon glyphicon-arrow-down\"");

WriteLiteralTo(__razor_helper_writer, "></span>\r\n\t\t\t\t\t\t\t</div>\r\n");

						}

WriteLiteralTo(__razor_helper_writer, "\t\t\t\t\t\t<input");

WriteLiteralTo(__razor_helper_writer, " autocomplete=\"off\"");

WriteAttributeTo(__razor_helper_writer, "id", Tuple.Create(" id=\'", 14428), Tuple.Create("\'", 14476)
, Tuple.Create(Tuple.Create("", 14433), Tuple.Create<System.Object, System.Int32>( block.Id + "quizBlock" + item.GetHash()
, 14433), false)
);

WriteLiteralTo(__razor_helper_writer, " type=\"hidden\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t\t\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"text\"");

WriteLiteralTo(__razor_helper_writer, ">");

            WriteTo(__razor_helper_writer, item.Text.RenderTex().ToLegacyHtmlString());

WriteLiteralTo(__razor_helper_writer, "</div>\r\n\t\t\t\t\t</div>\r\n");

					
                     if (model.ShowCorrectAnswers)
					{
						var correctItem = correctItems[itemIndex];

WriteLiteralTo(__razor_helper_writer, "\t\t\t\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"quiz-block-ordering__item correct col-xs-12 col-sm-offset-1 col-sm-5\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n");

WriteLiteralTo(__razor_helper_writer, "\t\t\t\t\t\t\t");

WriteTo(__razor_helper_writer, correctItem.Text.RenderTex().ToLegacyHtmlString());

WriteLiteralTo(__razor_helper_writer, "\r\n\t\t\t\t\t\t</div>\r\n");

					}

WriteLiteralTo(__razor_helper_writer, "\t\t\t\t</li>\r\n");

			}

WriteLiteralTo(__razor_helper_writer, "\t\t</ul>\r\n\t</div>\r\n");

	if (model.ShowExplanations && !string.IsNullOrEmpty(block.Explanation))
	{

WriteLiteralTo(__razor_helper_writer, "\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"text-muted\"");

WriteLiteralTo(__razor_helper_writer, ">");

  WriteTo(__razor_helper_writer, block.Explanation);

WriteLiteralTo(__razor_helper_writer, "</div>\r\n");

	}

});

#line default
#line hidden
}
#line default
#line hidden

#line default
#line hidden
public static System.Web.WebPages.HelperResult QuizBlock(MatchingBlock block, BlockRenderContext context)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {
 
	var fixedItems = block.GetMatches(block.ShuffleFixed);
	var movableItems = block.GetMatches(true);

	QuizBlockData model = context.GetBlockData(block) ?? new QuizBlockData(new QuizModel(), 1, QuizState.NotPassed);
	if (model.QuizState != QuizState.NotPassed && model.QuizModel.AnswersToQuizes[block.Id].FirstOrDefault() != null)
	{
		var userAnswers = model.QuizModel.AnswersToQuizes[block.Id];
		fixedItems = GetFixedItemsAccordingToUserAnswers(userAnswers, fixedItems)
			.OrderBy(item => userAnswers.FindIndex(answer => item.GetHashForFixedItem() == answer.ItemId)).ToList();
		movableItems = GetMovableItemsAccordingToUserAnswers(userAnswers, fixedItems);
	}

WriteLiteralTo(__razor_helper_writer, "\t<div");

WriteAttributeTo(__razor_helper_writer, "class", Tuple.Create(" class=\"", 15773), Tuple.Create("\"", 15849)
, Tuple.Create(Tuple.Create("", 15781), Tuple.Create("quiz-block-matching", 15781), true)
, Tuple.Create(Tuple.Create(" ", 15800), Tuple.Create<System.Object, System.Int32>( context.CanUserFillQuiz ? "" : "not-movable"
, 15801), false)
);

WriteAttributeTo(__razor_helper_writer, "id", Tuple.Create(" id=\'", 15850), Tuple.Create("\'", 15882)
          , Tuple.Create(Tuple.Create("", 15855), Tuple.Create<System.Object, System.Int32>( block.Id + "_quizBlock"
, 15855), false)
);

WriteLiteralTo(__razor_helper_writer, " ");

                                                                                         WriteTo(__razor_helper_writer, GetGuestOnclick(context.IsGuest));

WriteLiteralTo(__razor_helper_writer, ">\r\n");

		
         if (model.QuizState == QuizState.NotPassed)
		{

WriteLiteralTo(__razor_helper_writer, "\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"quiz-block-matching__description text-muted\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n                <span");

WriteLiteralTo(__razor_helper_writer, " class=\"visible-xs\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n                    Нажмите сначала на&nbsp;блоке из&nbsp;правого столбца, а&n" +
"bsp;затем на&nbsp;свободном месте в&nbsp;левом.\r\n                </span>\r\n      " +
"          <span");

WriteLiteralTo(__razor_helper_writer, " class=\"hidden-xs\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n                    Перетащите блоки из&nbsp;правого столбца на&nbsp;свободные" +
" места.\r\n                </span>\r\n            </div>\r\n");

		}

WriteLiteralTo(__razor_helper_writer, "\t\t");

         if (model.QuizState == QuizState.Total)
		{

WriteLiteralTo(__razor_helper_writer, "\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"quiz-block-matching__correct-description row\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"text-muted col-sm-3 col-sm-offset-3\"");

WriteLiteralTo(__razor_helper_writer, ">Ваш вариант</div>\r\n");

				
                 if (model.ShowCorrectAnswers)
				{

WriteLiteralTo(__razor_helper_writer, "\t\t\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"text-success col-sm-3 col-xs-offset-1\"");

WriteLiteralTo(__razor_helper_writer, ">Правильный вариант</div>\r\n");

				}

WriteLiteralTo(__razor_helper_writer, "\t\t\t</div>\r\n");

		}

WriteLiteralTo(__razor_helper_writer, "\t\t<ul>\r\n");

			
             for (var itemIndex = 0; itemIndex < fixedItems.Count; itemIndex++)
			{
				var fixedItem = fixedItems[itemIndex];
				var movableItem = movableItems[itemIndex];
				var isRightClass = "";
				if (model.ShowCorrectAnswers)
				{
					isRightClass = fixedItem.Id == movableItem.Id ? "right" : "wrong";
				}

WriteLiteralTo(__razor_helper_writer, "\t\t\t\t<li>\r\n\t\t\t\t\t<div");

WriteAttributeTo(__razor_helper_writer, "class", Tuple.Create(" class=\"", 17088), Tuple.Create("\"", 17144)
, Tuple.Create(Tuple.Create("", 17096), Tuple.Create("quiz", 17096), true)
, Tuple.Create(Tuple.Create(" ", 17100), Tuple.Create("quiz-block-matching__item", 17101), true)
, Tuple.Create(Tuple.Create(" ", 17126), Tuple.Create<System.Object, System.Int32>(isRightClass
, 17127), false)
, Tuple.Create(Tuple.Create(" ", 17140), Tuple.Create("row", 17141), true)
);

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t\t\t\t\t<input");

WriteLiteralTo(__razor_helper_writer, " autocomplete=\"off\"");

WriteAttributeTo(__razor_helper_writer, "id", Tuple.Create(" id=\'", 17179), Tuple.Create("\'", 17244)
, Tuple.Create(Tuple.Create("", 17184), Tuple.Create<System.Object, System.Int32>( block.Id + "quizBlock" + fixedItem.GetHashForFixedItem()
, 17184), false)
);

WriteLiteralTo(__razor_helper_writer, " type=\"hidden\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t\t\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"quiz-block-matching__fixed-item col-xs-3\"");

WriteLiteralTo(__razor_helper_writer, " data-item-id=\"");

                                                              WriteTo(__razor_helper_writer, fixedItem.GetHashForFixedItem());

WriteLiteralTo(__razor_helper_writer, "\"");

WriteLiteralTo(__razor_helper_writer, ">");

                                                                                                WriteTo(__razor_helper_writer, fixedItem.FixedItem.RenderTex().ToLegacyHtmlString());

WriteLiteralTo(__razor_helper_writer, "</div>\r\n");

						
                         if (model.QuizState == QuizState.NotPassed)
						{

WriteLiteralTo(__razor_helper_writer, "\t\t\t\t\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"quiz-block-matching__droppable col-xs-3\"");

WriteLiteralTo(__razor_helper_writer, " data-block-id=\"");

                                                                  WriteTo(__razor_helper_writer, block.Id);

WriteLiteralTo(__razor_helper_writer, "\"");

WriteLiteralTo(__razor_helper_writer, " data-item-id=\"");

                                                                                           WriteTo(__razor_helper_writer, fixedItem.GetHashForFixedItem());

WriteLiteralTo(__razor_helper_writer, "\"");

WriteLiteralTo(__razor_helper_writer, "></div>\r\n");

WriteLiteralTo(__razor_helper_writer, "\t\t\t\t\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"quiz-block-matching__source__droppable col-xs-3 col-xs-offset-1 added\"");

WriteLiteralTo(__razor_helper_writer, " data-block-id=\"");

                                                                                                WriteTo(__razor_helper_writer, block.Id);

WriteLiteralTo(__razor_helper_writer, "\"");

WriteLiteralTo(__razor_helper_writer, " data-movable-item-id=\"");

                                                                                                                                 WriteTo(__razor_helper_writer, movableItem.GetHashForMovableItem());

WriteLiteralTo(__razor_helper_writer, "\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t\t\t\t\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"quiz-block-matching__movable-item\"");

WriteLiteralTo(__razor_helper_writer, " data-block-id=\"");

                                                                WriteTo(__razor_helper_writer, block.Id);

WriteLiteralTo(__razor_helper_writer, "\"");

WriteLiteralTo(__razor_helper_writer, " data-item-id=\"");

                                                                                         WriteTo(__razor_helper_writer, movableItem.GetHashForMovableItem());

WriteLiteralTo(__razor_helper_writer, "\"");

WriteLiteralTo(__razor_helper_writer, ">");

                                                                                                                               WriteTo(__razor_helper_writer, movableItem.MovableItem.RenderTex().ToLegacyHtmlString());

WriteLiteralTo(__razor_helper_writer, "</div>\r\n\t\t\t\t\t\t\t</div>\r\n");

						}
						else
						{

WriteLiteralTo(__razor_helper_writer, "\t\t\t\t\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"quiz-block-matching__droppable col-xs-3 added\"");

WriteLiteralTo(__razor_helper_writer, " data-block-id=\"");

                                                                        WriteTo(__razor_helper_writer, block.Id);

WriteLiteralTo(__razor_helper_writer, "\"");

WriteLiteralTo(__razor_helper_writer, " data-item-id=\"");

                                                                                                 WriteTo(__razor_helper_writer, fixedItem.GetHashForFixedItem());

WriteLiteralTo(__razor_helper_writer, "\"");

WriteLiteralTo(__razor_helper_writer, " data-movable-item-id=\"");

                                                                                                                                                         WriteTo(__razor_helper_writer, movableItem.GetHashForMovableItem());

WriteLiteralTo(__razor_helper_writer, "\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t\t\t\t\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"quiz-block-matching__movable-item\"");

WriteLiteralTo(__razor_helper_writer, " data-block-id=\"");

                                                                WriteTo(__razor_helper_writer, block.Id);

WriteLiteralTo(__razor_helper_writer, "\"");

WriteLiteralTo(__razor_helper_writer, " data-item-id=\"");

                                                                                         WriteTo(__razor_helper_writer, movableItem.GetHashForMovableItem());

WriteLiteralTo(__razor_helper_writer, "\"");

WriteLiteralTo(__razor_helper_writer, ">");

                                                                                                                               WriteTo(__razor_helper_writer, movableItem.MovableItem.RenderTex().ToLegacyHtmlString());

WriteLiteralTo(__razor_helper_writer, "</div>\r\n\t\t\t\t\t\t\t</div>\r\n");

							if (model.ShowCorrectAnswers)
							{

WriteLiteralTo(__razor_helper_writer, "\t\t\t\t\t\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"quiz-block-matching__fixed-item correct col-xs-3 col-xs-offset-1\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n");

WriteLiteralTo(__razor_helper_writer, "\t\t\t\t\t\t\t\t\t");

      WriteTo(__razor_helper_writer, fixedItem.MovableItem.RenderTex().ToLegacyHtmlString());

WriteLiteralTo(__razor_helper_writer, "\r\n\t\t\t\t\t\t\t\t</div>\r\n");

							}
							if (context.CanUserFillQuiz)
							{

WriteLiteralTo(__razor_helper_writer, "\t\t\t\t\t\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"quiz-block-matching__source__droppable col-xs-3 col-xs-offset-1\"");

WriteLiteralTo(__razor_helper_writer, " data-block-id=\"");

                                                                                              WriteTo(__razor_helper_writer, block.Id);

WriteLiteralTo(__razor_helper_writer, "\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t\t\t\t\t\t\t</div>\r\n");

							}
						}

WriteLiteralTo(__razor_helper_writer, "\r\n\t\t\t\t\t</div>\r\n\t\t\t\t</li>\r\n");

			}

WriteLiteralTo(__razor_helper_writer, "\t\t</ul>\r\n\t</div>\r\n");

	if (model.ShowExplanations && !string.IsNullOrEmpty(block.Explanation))
	{

WriteLiteralTo(__razor_helper_writer, "\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"text-muted\"");

WriteLiteralTo(__razor_helper_writer, ">");

  WriteTo(__razor_helper_writer, block.Explanation);

WriteLiteralTo(__razor_helper_writer, "</div>\r\n");

	}

});

#line default
#line hidden
}
#line default
#line hidden

#line default
#line hidden
public static System.Web.WebPages.HelperResult RunErrors()
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {
 

WriteLiteralTo(__razor_helper_writer, "\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"run-result run-service-error\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"run-verdict label-warning\"");

WriteLiteralTo(__razor_helper_writer, ">Ошибка сервера :(</div>\r\n\t\t<pre");

WriteLiteralTo(__razor_helper_writer, " class=\"no-rounds\"");

WriteLiteralTo(__razor_helper_writer, "><code");

WriteLiteralTo(__razor_helper_writer, " class=\"run-details\"");

WriteLiteralTo(__razor_helper_writer, "></code></pre>\r\n\t</div>\r\n");



WriteLiteralTo(__razor_helper_writer, "\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"run-result run-compile-error\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"run-verdict label-danger\"");

WriteLiteralTo(__razor_helper_writer, ">Ошибка компиляции</div>\r\n\t\t<pre");

WriteLiteralTo(__razor_helper_writer, " class=\"no-rounds\"");

WriteLiteralTo(__razor_helper_writer, "><code");

WriteLiteralTo(__razor_helper_writer, " class=\"run-details\"");

WriteLiteralTo(__razor_helper_writer, "></code></pre>\r\n\t</div>\r\n");



WriteLiteralTo(__razor_helper_writer, "\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"run-result run-style-error\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"run-verdict label-warning\"");

WriteLiteralTo(__razor_helper_writer, ">Задача сдана. Осталось исправить стилевые ошибки!</div>\r\n\t\t<pre");

WriteLiteralTo(__razor_helper_writer, " class=\"no-rounds\"");

WriteLiteralTo(__razor_helper_writer, "><code");

WriteLiteralTo(__razor_helper_writer, " class=\"run-details\"");

WriteLiteralTo(__razor_helper_writer, "></code></pre>\r\n\t\t<div>\r\n\t\t\t<small>Код со стилевыми ошибками трудно или неприятно" +
" читать другим программистам, поэтому он может не пройти код-ревью.</small>\r\n\t\t<" +
"/div>\r\n\t</div>\r\n");



WriteLiteralTo(__razor_helper_writer, "\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"run-result run-wa\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"run-verdict label-danger\"");

WriteLiteralTo(__razor_helper_writer, ">Неверный результат</div>\r\n\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"diff-table tablesorter\"");

WriteLiteralTo(__razor_helper_writer, "></div>\r\n\t</div>\r\n");



WriteLiteralTo(__razor_helper_writer, "\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"run-result run-wa-no-diff\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"run-verdict label-danger\"");

WriteLiteralTo(__razor_helper_writer, ">Неверный результат</div>\r\n\t\t<pre");

WriteLiteralTo(__razor_helper_writer, " class=\"no-rounds\"");

WriteLiteralTo(__razor_helper_writer, "><code");

WriteLiteralTo(__razor_helper_writer, " class=\"run-details\"");

WriteLiteralTo(__razor_helper_writer, "></code></pre>\r\n\t</div>\r\n");



WriteLiteralTo(__razor_helper_writer, "\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"run-result run-success\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"run-verdict label-success clearfix\"");

WriteLiteralTo(__razor_helper_writer, ">Задача сдана!</div>\r\n\t\t<pre");

WriteLiteralTo(__razor_helper_writer, " class=\"no-rounds\"");

WriteLiteralTo(__razor_helper_writer, "><code");

WriteLiteralTo(__razor_helper_writer, " class=\"run-details\"");

WriteLiteralTo(__razor_helper_writer, "></code></pre>\r\n\t</div>\r\n");


});

#line default
#line hidden
}
#line default
#line hidden

#line default
#line hidden
public static System.Web.WebPages.HelperResult ExerciseControls(ExerciseControlsModel model)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {
 

WriteLiteralTo(__razor_helper_writer, "\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"solution-control btn-group ctrl-group\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n");

		
         if (!model.IsCodeEditableAndSendable)
		{

WriteLiteralTo(__razor_helper_writer, "\t\t\t<button");

WriteLiteralTo(__razor_helper_writer, " type=\"button\"");

WriteAttributeTo(__razor_helper_writer, "class", Tuple.Create(" class=\"", 20568), Tuple.Create("\"", 20695)
, Tuple.Create(Tuple.Create("", 20576), Tuple.Create("try-again-button", 20576), true)
, Tuple.Create(Tuple.Create(" ", 20592), Tuple.Create("btn", 20593), true)
, Tuple.Create(Tuple.Create(" ", 20596), Tuple.Create("btn-primary", 20597), true)
, Tuple.Create(Tuple.Create(" ", 20608), Tuple.Create("no-rounds", 20609), true)
, Tuple.Create(Tuple.Create(" ", 20618), Tuple.Create("exercise-version-link", 20619), true)
                         , Tuple.Create(Tuple.Create(" ", 20640), Tuple.Create<System.Object, System.Int32>( model.IsLti ? "exercise-controls_button-long" : ""
, 20641), false)
);

WriteLiteralTo(__razor_helper_writer, " data-version-id=\"-1\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t\t\tЕщё раз\r\n\t\t\t</button>\r\n");

		}
		else
		{

WriteLiteralTo(__razor_helper_writer, "\t\t\t<button");

WriteLiteralTo(__razor_helper_writer, " type=\"button\"");

WriteAttributeTo(__razor_helper_writer, "class", Tuple.Create(" class=\"", 20789), Tuple.Create("\"", 20897)
, Tuple.Create(Tuple.Create("", 20797), Tuple.Create("run-solution-button", 20797), true)
, Tuple.Create(Tuple.Create(" ", 20816), Tuple.Create("btn", 20817), true)
, Tuple.Create(Tuple.Create(" ", 20820), Tuple.Create("btn-primary", 20821), true)
, Tuple.Create(Tuple.Create(" ", 20832), Tuple.Create("no-rounds", 20833), true)
      , Tuple.Create(Tuple.Create(" ", 20842), Tuple.Create<System.Object, System.Int32>( model.IsLti ? "exercise-controls_button-long" : ""
, 20843), false)
);

WriteLiteralTo(__razor_helper_writer, " data-url=\"");

                                                                                                                            WriteTo(__razor_helper_writer,  model.RunSolutionUrl);

WriteLiteralTo(__razor_helper_writer, "\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t\t\tОтправить\r\n\t\t\t</button>\r\n");

		}

WriteLiteralTo(__razor_helper_writer, "\t\t");

         if (!model.DebugView)
		{
			var hints = model.Block.HintsMd;

WriteLiteralTo(__razor_helper_writer, "\t\t\t<button");

WriteLiteralTo(__razor_helper_writer, " id=\"GetHintButton\"");

WriteLiteralTo(__razor_helper_writer, " type=\"button\"");

WriteLiteralTo(__razor_helper_writer, " class=\"btn btn-default hints-btn\"");

WriteLiteralTo(__razor_helper_writer, " data-course-id=\"");

                                                                          WriteTo(__razor_helper_writer,  model.CourseId);

WriteLiteralTo(__razor_helper_writer, "\"");

WriteLiteralTo(__razor_helper_writer, " data-slide-id=\"");

                                                                                                             WriteTo(__razor_helper_writer,  model.Slide.Id);

WriteLiteralTo(__razor_helper_writer, "\"");

WriteLiteralTo(__razor_helper_writer, " data-hints-count=\"");

                                                                                                                                                   WriteTo(__razor_helper_writer,  hints.Count);

WriteLiteralTo(__razor_helper_writer, "\"");

WriteLiteralTo(__razor_helper_writer, " data-url=\"");

                                                                                                                                                                              WriteTo(__razor_helper_writer,  model.UseHintUrl);

WriteLiteralTo(__razor_helper_writer, "\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t\t\tВзять подсказку\r\n\t\t\t</button>\r\n");

			if (model.CanShowOutput)
			{

WriteLiteralTo(__razor_helper_writer, "\t\t\t\t<button");

WriteLiteralTo(__razor_helper_writer, " type=\"button\"");

WriteAttributeTo(__razor_helper_writer, "class", Tuple.Create(" class=\"", 21352), Tuple.Create("\"", 21455)
, Tuple.Create(Tuple.Create("", 21360), Tuple.Create("show-output-button", 21360), true)
, Tuple.Create(Tuple.Create(" ", 21378), Tuple.Create("btn", 21379), true)
, Tuple.Create(Tuple.Create(" ", 21382), Tuple.Create("btn-default", 21383), true)
, Tuple.Create(Tuple.Create(" ", 21394), Tuple.Create("no-rounds", 21395), true)
         , Tuple.Create(Tuple.Create(" ", 21404), Tuple.Create<System.Object, System.Int32>( model.IsShowOutputButtonActive ? "active" : ""
, 21405), false)
);

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t\t\t\tПоказать вывод\r\n\t\t\t\t</button>\r\n");

			}
			if (!model.IsLti && !model.HideShowSolutionsButton)
			{

WriteLiteralTo(__razor_helper_writer, "\t\t\t\t<button");

WriteLiteralTo(__razor_helper_writer, " type=\"button\"");

WriteLiteralTo(__razor_helper_writer, " class=\"btn btn-default giveup-btn no-rounds\"");

WriteAttributeTo(__razor_helper_writer, "onclick", Tuple.Create(" onclick=\"", 21633), Tuple.Create("\"", 21676)
            , Tuple.Create(Tuple.Create("", 21643), Tuple.Create<System.Object, System.Int32>( model.AcceptedSolutionsAction
, 21643), false)
);

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t\t\t\tЧужие решения\r\n\t\t\t\t</button>\r\n");

			}
			if (model.IsCodeEditableAndSendable)
			{

WriteLiteralTo(__razor_helper_writer, "\t\t\t\t<button");

WriteLiteralTo(__razor_helper_writer, " type=\"button\"");

WriteLiteralTo(__razor_helper_writer, " class=\"btn btn-default reset-btn no-rounds\"");

WriteLiteralTo(__razor_helper_writer, " onclick=\"cleanUserCode()\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t\t\t\tНачать с начала\r\n\t\t\t\t</button>\r\n");

			}
		}

WriteLiteralTo(__razor_helper_writer, "\t</div>\r\n");


});

#line default
#line hidden
}
#line default
#line hidden
 

	public static string GetGuestOnclick(bool isGuest)
	{
		return isGuest ? "onclick=loginForContinue()" : "";
	}

	public static string GetGuestDisable(bool isGuest)
	{
		return isGuest ? "disabled" : null;
	}

	private static List<MatchingMatch> GetFixedItemsAccordingToUserAnswers(List<UserQuiz> userAnswers, List<MatchingMatch> fixedItems)
	{
		var filteredFixedItems = new List<MatchingMatch>();
		foreach (var fixedItem in fixedItems)
		{
			var userAnswered = userAnswers.Any(answer => answer.ItemId == fixedItem.GetHashForFixedItem());
			if (userAnswered)
				filteredFixedItems.Add(fixedItem);
		}
		return filteredFixedItems;
	}

	private static List<MatchingMatch> GetMovableItemsAccordingToUserAnswers(List<UserQuiz> userAnswers, List<MatchingMatch> fixedItems)
	{
		var movableItems = new List<MatchingMatch>();
		foreach (var fixedItem in fixedItems)
		{
			var userAnswer = userAnswers.FirstOrDefault(answer => answer.ItemId == fixedItem.GetHashForFixedItem());
			if (userAnswer != null)
				movableItems.Add(fixedItems.FirstOrDefault(item => item.GetHashForMovableItem() == userAnswer.Text));
		}
		return movableItems;
	}


    }
}
#pragma warning restore 1591
