
//automatically generated by Tuto
using uLearn;
namespace AIML 
{
    [Slide(@"Логика высказываний","72da07e2-eef5-4c5a-9aca-6b417fa35e6f")]
    public class Логика_высказываний
        {
		//#video 3xpkr5Dyi0c
		/*
		[Презентация](_S02-slides.pdf)
		*/

        }
}