
//automatically generated by Tuto
using uLearn;
namespace AIML 
{
    [Slide(@"Поиск теорем","4f4ddaf6-7aed-4bc5-98cc-ea88a63a3ac9")]
    public class Поиск_теорем
        {
		//#video 25KSb4VhVBk
		/*
		[Презентация](_S05-slides.pdf)
		*/

        }
}