#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Runtime Version:4.0.30319.42000
//
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uLearn.Web.Views.Shared.Helpers
{
	using System;
	using System.Collections.Generic;
	using System.IO;
	using System.Linq;
	using System.Net;
	using System.Text;
	using System.Web;
	using System.Web.Helpers;
	using System.Web.Mvc;
	using System.Web.Mvc.Ajax;
	using System.Web.Mvc.Html;
	using System.Web.Routing;
	using System.Web.Security;
	using System.Web.UI;
	using System.Web.WebPages;
	using uLearn.Web.Models;
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
	public static class SwitchablePanel
	{

public static System.Web.WebPages.HelperResult Panel(string idPrefix, params SwitchablePanelModel[] switches)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {


 
	if (string.IsNullOrWhiteSpace(idPrefix))
	{
		 idPrefix = "sw-panel-" + Guid.NewGuid();
	}

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "	<div>\r\n		<div class=\"btn-group\">\r\n");


 			for (var i = 0; i < switches.Length; ++i)
			{

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "				<button type=\"button\" class=\"btn btn-default ");


	   WebViewPage.WriteTo(@__razor_helper_writer, i == 0 ? "btn-primary" : "");

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\" onclick=\"ShowPanel(event)\" data-div-id=\"");


																			  WebViewPage.WriteTo(@__razor_helper_writer, idPrefix);

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "-");


																						WebViewPage.WriteTo(@__razor_helper_writer, i);

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\">");


																							WebViewPage.WriteTo(@__razor_helper_writer, switches[i].Name);

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</button>\r\n");


			}

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "		</div>\r\n");


 		for (var i = 0; i < switches.Length; ++i)
		{

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "			<div id=\"");


WebViewPage.WriteTo(@__razor_helper_writer, idPrefix);

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "-");


WebViewPage.WriteTo(@__razor_helper_writer, i);

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\" class=\"statistic-container ");


		   WebViewPage.WriteTo(@__razor_helper_writer, i == 0 ? "load-content" : "");

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\" data-url=\"");


													 WebViewPage.WriteTo(@__razor_helper_writer, switches[i].Url);

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\"></div>\r\n");


		}

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "	</div>\r\n");



});

}


public static System.Web.WebPages.HelperResult TimePanel(string idPrefix, Func<RouteValueDictionary, string> getUrl, dynamic arguments, params Tuple<string, double>[] intervals) 
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {


 
	var switches = new List<SwitchablePanelModel>();
	foreach (var interval in intervals)
	{
		var periodStart = DateTime.Now.Subtract(TimeSpan.FromDays(interval.Item2));
		switches.Add(new SwitchablePanelModel
		{
			Name = interval.Item1,
			Url = GetUrl(getUrl, arguments, periodStart)
		});
	}
	switches.Add(new SwitchablePanelModel
	{
		Name = "За всё время",
		Url = GetUrl(getUrl, arguments, DateTime.MinValue)
	});
	
WebViewPage.WriteTo(@__razor_helper_writer, Panel(idPrefix, switches.ToArray()));

									 

});

}



	private static string GetUrl(Func<RouteValueDictionary, string> getUrl, object arguments, DateTime periodStart)
	{
		var arg = new RouteValueDictionary(arguments);
		arg["periodStart"] = periodStart;
		return getUrl(arg);
	}


	}
}
#pragma warning restore 1591
