// Courses
export const COURSES__COURSE_ENTERED = "COURSES__COURSE_ENTERED";
export const COURSES__COURSE_LOAD = "COURSES__COURSE_LOAD";
export const COURSES__UPDATED = "COURSES__UPDATED";
export const COURSES_FLASHCARDS = "COURSES_FLASHCARDS";
export const COURSES_FLASHCARDS_RATE = "COURSES_FLASHCARDS_RATE";

// User
export const USER__PROGRESS_LOAD = "USER__PROGRESS_LOAD";
export const USER__PROGRESS_UPDATE = "USER__PROGRESS_UPDATE";

// common
export const START = "_START";
export const SUCCESS = "_SUCCESS";
export const FAIL = "_FAIL";