// Courses
export const COURSES__COURSE_ENTERED = "COURSES__COURSE_ENTERED";
export const COURSES__COURSE_LOAD = "COURSES__COURSE_LOAD";
export const COURSES__COURSE_LOAD_ERRORS = "COURSES__COURSE_LOAD_ERRORS";
export const COURSES__UPDATED = "COURSES__UPDATED";
export const COURSES__FLASHCARDS = "COURSES__FLASHCARDS";
export const COURSES__FLASHCARDS_RATE = "COURSES__FLASHCARDS_RATE";

// Slide
export const COURSES__SLIDE_LOAD = "COURSES__SLIDE_LOAD";
export const COURSES__SLIDE_READY = "COURSES__SLIDE_READY";
export const COURSES__EXERCISE_ADD_SUBMISSIONS = "COURSES__EXERCISE_ADD_SUBMISSIONS";

// User
export const USER__PROGRESS_LOAD = "USER__PROGRESS_LOAD";
export const USER__PROGRESS_UPDATE = "USER__PROGRESS_UPDATE";

// Navigation
export const NAVIGATION__TOGGLE = 'NAVIGATION__TOGGLE';

// Account
export const ACCOUNT__USER_HIJACK = "ACCOUNT__USER_HIJACK";
export const ACCOUNT__USER_INFO_UPDATED = 'ACCOUNT__USER_INFO_UPDATED';
export const ACCOUNT__USER_ROLES_UPDATED = 'ACCOUNT__USER_ROLES_UPDATED';

// Notifications
export const NOTIFICATIONS__COUNT_UPDATED = 'NOTIFICATIONS__COUNT_UPDATED';
export const NOTIFICATIONS__COUNT_RESETED = 'NOTIFICATIONS__COUNT_RESETED';

//Instructor
export const INSTRUCTOR__STUDENT_MODE_TOGGLE = 'INSTRUCTOR__STUDENT_MODE_TOGGLE';

// common
export const START = "_START";
export const SUCCESS = "_SUCCESS";
export const FAIL = "_FAIL";
