#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uLearn.Web.Views.Shared
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Database.Models;
    using uLearn;
    using uLearn.Extensions;
    using uLearn.Quizes;
    using uLearn.Web;
    using uLearn.Web.Extensions;
    using uLearn.Web.Models;
    using uLearn.Web.Views.Shared;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public class Notifications : System.Web.WebPages.HelperPage
    {
 

	private static string GetSlideUrl(UrlHelper Url, Course course, Slide slide)
	{
		return Url.RouteUrl("Course.SlideById", new { courseId = course.Id, slideId = slide.Url });
	}

	private static IHtmlString CollapseIfNeed(bool collapse, HtmlHelper Html, string text, int truncateMaxLength, bool renderSimpleMarkdown=false)
	{
		var encodedText = Html.EncodeMultiLineText(text);
		if (renderSimpleMarkdown)
			encodedText = encodedText.RenderSimpleMarkdown();
		if (collapse)
			encodedText = encodedText.TruncateHtmlWithEllipsis(truncateMaxLength);
		return Html.Raw(collapse ? encodedText : Html.HighlightLink(encodedText));
	}


#line default
#line hidden
public static System.Web.WebPages.HelperResult SlideLink(UrlHelper Url, Course course, Slide slide)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {
 

WriteLiteralTo(__razor_helper_writer, "\t<a");

WriteAttributeTo(__razor_helper_writer, "href", Tuple.Create(" href=\"", 990), Tuple.Create("\"", 1029)
, Tuple.Create(Tuple.Create("", 997), Tuple.Create<System.Object, System.Int32>(GetSlideUrl(Url, course, slide)
, 997), false)
);

WriteLiteralTo(__razor_helper_writer, ">");

                 WriteTo(__razor_helper_writer, slide.Title.TruncateWithEllipsis(40));

WriteLiteralTo(__razor_helper_writer, "</a>\r\n");


});

#line default
#line hidden
}
#line default
#line hidden

#line default
#line hidden
public static System.Web.WebPages.HelperResult UserName(ApplicationUser user)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {
 

WriteLiteralTo(__razor_helper_writer, "\t<span");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__notification__user\"");

WriteLiteralTo(__razor_helper_writer, ">");

                      WriteTo(__razor_helper_writer, user.VisibleName);

WriteLiteralTo(__razor_helper_writer, "</span>\r\n");


});

#line default
#line hidden
}
#line default
#line hidden

#line default
#line hidden
public static System.Web.WebPages.HelperResult Notification(SystemMessageNotification notification, Course course, HtmlHelper Html, UrlHelper Url, bool collapse = true)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {
 

WriteLiteralTo(__razor_helper_writer, "\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__system-message-notification without-link media\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"media-left\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t</div>\r\n\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"media-body\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"\"");

WriteLiteralTo(__razor_helper_writer, ">");

WriteTo(__razor_helper_writer, CollapseIfNeed(collapse, Html, notification.Text, 100));

WriteLiteralTo(__razor_helper_writer, "</div>\r\n\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__notification__footer\"");

WriteAttributeTo(__razor_helper_writer, "title", Tuple.Create(" title=\"", 1611), Tuple.Create("\"", 1660)
, Tuple.Create(Tuple.Create("", 1619), Tuple.Create<System.Object, System.Int32>(notification.CreateTime.ToPrettyString()
, 1619), false)
);

WriteLiteralTo(__razor_helper_writer, ">");

                                                                                 WriteTo(__razor_helper_writer, notification.CreateTime.ToAgoPrettyString());

WriteLiteralTo(__razor_helper_writer, "</div>\r\n\t\t</div>\r\n\t</div>\r\n");


});

#line default
#line hidden
}
#line default
#line hidden

#line default
#line hidden
public static System.Web.WebPages.HelperResult Notification(InstructorMessageNotification notification, Course course, HtmlHelper Html, UrlHelper Url, bool collapse = true)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {
 

WriteLiteralTo(__razor_helper_writer, "\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__instructor-message-notification without-link media\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"media-left\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n");

WriteLiteralTo(__razor_helper_writer, "\t\t\t");

WriteTo(__razor_helper_writer, UserAvatar.Avatar(notification.InitiatedBy));

WriteLiteralTo(__razor_helper_writer, "\r\n\t\t</div>\r\n\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"media-body\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__notification__header\"");

WriteLiteralTo(__razor_helper_writer, ">");

                               WriteTo(__razor_helper_writer, UserName(notification.InitiatedBy));

WriteLiteralTo(__razor_helper_writer, ":</div>\r\n\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"\"");

WriteLiteralTo(__razor_helper_writer, ">");

WriteTo(__razor_helper_writer, CollapseIfNeed(collapse, Html, notification.Text, 100));

WriteLiteralTo(__razor_helper_writer, "</div>\r\n\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__notification__footer\"");

WriteAttributeTo(__razor_helper_writer, "title", Tuple.Create(" title=\"", 2300), Tuple.Create("\"", 2349)
, Tuple.Create(Tuple.Create("", 2308), Tuple.Create<System.Object, System.Int32>(notification.CreateTime.ToPrettyString()
, 2308), false)
);

WriteLiteralTo(__razor_helper_writer, ">");

                                                                                 WriteTo(__razor_helper_writer, notification.CreateTime.ToAgoPrettyString());

WriteLiteralTo(__razor_helper_writer, "</div>\r\n\t\t</div>\r\n\t</div>\r\n");


});

#line default
#line hidden
}
#line default
#line hidden

#line default
#line hidden
public static System.Web.WebPages.HelperResult Notification(NewCommentNotification notification, Course course, HtmlHelper Html, UrlHelper Url, bool collapse = true)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {
 
	var slide = course.GetSlideById(notification.Comment.SlideId);

WriteLiteralTo(__razor_helper_writer, "\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__new-comment-notification media\"");

WriteLiteralTo(__razor_helper_writer, " data-href=\"");

                                            WriteTo(__razor_helper_writer, GetSlideUrl(Url, course, slide));

WriteLiteralTo(__razor_helper_writer, "#comment-");

                                                                                     WriteTo(__razor_helper_writer, notification.Comment.Id);

WriteLiteralTo(__razor_helper_writer, "\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"media-left\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n");

WriteLiteralTo(__razor_helper_writer, "\t\t\t");

WriteTo(__razor_helper_writer, UserAvatar.Avatar(notification.Comment.Author));

WriteLiteralTo(__razor_helper_writer, "\r\n\t\t</div>\r\n\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"media-body\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__notification__header\"");

WriteLiteralTo(__razor_helper_writer, ">");

                               WriteTo(__razor_helper_writer, UserName(notification.Comment.Author));

WriteLiteralTo(__razor_helper_writer, "</div>\r\n\t\t\t<div");

WriteAttributeTo(__razor_helper_writer, "title", Tuple.Create(" title=\"", 2986), Tuple.Create("\"", 3046)
, Tuple.Create(Tuple.Create("", 2994), Tuple.Create<System.Object, System.Int32>(notification.Comment.Text.TruncateWithEllipsis(200)
, 2994), false)
);

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__comment-notification__text\"");

WriteLiteralTo(__razor_helper_writer, ">");

                                                                                                  WriteTo(__razor_helper_writer, CollapseIfNeed(collapse, Html, notification.Comment.Text, 100, renderSimpleMarkdown: true));

WriteLiteralTo(__razor_helper_writer, "</div>\r\n\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__notification__footer\"");

WriteLiteralTo(__razor_helper_writer, ">к&nbsp;слайду ");

                                             WriteTo(__razor_helper_writer, SlideLink(Url, course, slide));

WriteLiteralTo(__razor_helper_writer, "</div>\r\n\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__notification__footer\"");

WriteAttributeTo(__razor_helper_writer, "title", Tuple.Create(" title=\"", 3352), Tuple.Create("\"", 3401)
, Tuple.Create(Tuple.Create("", 3360), Tuple.Create<System.Object, System.Int32>(notification.CreateTime.ToPrettyString()
, 3360), false)
);

WriteLiteralTo(__razor_helper_writer, ">");

                                                                                 WriteTo(__razor_helper_writer, notification.CreateTime.ToAgoPrettyString());

WriteLiteralTo(__razor_helper_writer, "</div>\r\n\t\t</div>\r\n\t</div>\r\n");


});

#line default
#line hidden
}
#line default
#line hidden

#line default
#line hidden
public static System.Web.WebPages.HelperResult Notification(RepliedToYourCommentNotification notification, Course course, HtmlHelper Html, UrlHelper Url, bool collapse = true)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {
 
	var slide = course.GetSlideById(notification.Comment.SlideId);

WriteLiteralTo(__razor_helper_writer, "\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__replied-to-your-comment-notification media\"");

WriteLiteralTo(__razor_helper_writer, " data-href=\"");

                                                        WriteTo(__razor_helper_writer, GetSlideUrl(Url, course, slide));

WriteLiteralTo(__razor_helper_writer, "#comment-");

                                                                                                 WriteTo(__razor_helper_writer, notification.Comment.Id);

WriteLiteralTo(__razor_helper_writer, "\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"media-left\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n");

WriteLiteralTo(__razor_helper_writer, "\t\t\t");

WriteTo(__razor_helper_writer, UserAvatar.Avatar(notification.Comment.Author));

WriteLiteralTo(__razor_helper_writer, "\r\n\t\t</div>\r\n\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"media-body\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__notification__header\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n");

WriteLiteralTo(__razor_helper_writer, "\t\t\t\t");

WriteTo(__razor_helper_writer, UserName(notification.Comment.Author));

WriteLiteralTo(__razor_helper_writer, " ответил");

                                 WriteTo(__razor_helper_writer,  notification.Comment.Author.Gender.ChooseEnding());

WriteLiteralTo(__razor_helper_writer, " на&nbsp;ваш комментарий\r\n\t\t\t\t<span");

WriteAttributeTo(__razor_helper_writer, "title", Tuple.Create(" title=\"", 4147), Tuple.Create("\"", 4213)
, Tuple.Create(Tuple.Create("", 4155), Tuple.Create<System.Object, System.Int32>(notification.ParentComment.Text.TruncateWithEllipsis(200)
, 4155), false)
);

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__comment-notification__cite\"");

WriteLiteralTo(__razor_helper_writer, ">");

                                                                                                             WriteTo(__razor_helper_writer, CollapseIfNeed(collapse, Html, notification.ParentComment.Text, 50, renderSimpleMarkdown: true));

WriteLiteralTo(__razor_helper_writer, "</span>\r\n\t\t\t</div>\r\n\t\t\t<div");

WriteAttributeTo(__razor_helper_writer, "title", Tuple.Create(" title=\"", 4388), Tuple.Create("\"", 4448)
, Tuple.Create(Tuple.Create("", 4396), Tuple.Create<System.Object, System.Int32>(notification.Comment.Text.TruncateWithEllipsis(200)
, 4396), false)
);

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__comment-notification__text\"");

WriteLiteralTo(__razor_helper_writer, ">");

                                                                                                  WriteTo(__razor_helper_writer, CollapseIfNeed(collapse, Html, notification.Comment.Text, 100, renderSimpleMarkdown: true));

WriteLiteralTo(__razor_helper_writer, "</div>\r\n\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__notification__footer\"");

WriteLiteralTo(__razor_helper_writer, ">к&nbsp;слайду ");

                                             WriteTo(__razor_helper_writer, SlideLink(Url, course, slide));

WriteLiteralTo(__razor_helper_writer, "</div>\r\n\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__notification__footer\"");

WriteAttributeTo(__razor_helper_writer, "title", Tuple.Create(" title=\"", 4754), Tuple.Create("\"", 4803)
, Tuple.Create(Tuple.Create("", 4762), Tuple.Create<System.Object, System.Int32>(notification.CreateTime.ToPrettyString()
, 4762), false)
);

WriteLiteralTo(__razor_helper_writer, ">");

                                                                                 WriteTo(__razor_helper_writer, notification.CreateTime.ToAgoPrettyString());

WriteLiteralTo(__razor_helper_writer, "</div>\r\n\t\t</div>\r\n\t</div>\r\n");


});

#line default
#line hidden
}
#line default
#line hidden

#line default
#line hidden
public static System.Web.WebPages.HelperResult Notification(LikedYourCommentNotification notification, Course course, HtmlHelper Html, UrlHelper Url, bool collapse = true)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {
 
	var slide = course.GetSlideById(notification.Comment.SlideId);

WriteLiteralTo(__razor_helper_writer, "\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__liked-your-comment-notification media\"");

WriteLiteralTo(__razor_helper_writer, " data-href=\"");

                                                   WriteTo(__razor_helper_writer, GetSlideUrl(Url, course, slide));

WriteLiteralTo(__razor_helper_writer, "#comment-");

                                                                                            WriteTo(__razor_helper_writer, notification.Comment.Id);

WriteLiteralTo(__razor_helper_writer, "\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"media-left\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n");

WriteLiteralTo(__razor_helper_writer, "\t\t\t");

WriteTo(__razor_helper_writer, UserAvatar.Avatar(notification.LikedUser));

WriteLiteralTo(__razor_helper_writer, "\r\n\t\t</div>\r\n\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"media-body\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__notification__header\"");

WriteLiteralTo(__razor_helper_writer, ">");

                               WriteTo(__razor_helper_writer, UserName(notification.LikedUser));

WriteLiteralTo(__razor_helper_writer, " лайкнул");

                                                                         WriteTo(__razor_helper_writer,  notification.LikedUser.Gender.ChooseEnding());

WriteLiteralTo(__razor_helper_writer, " ваш комментарий</div>\r\n\t\t\t<div");

WriteAttributeTo(__razor_helper_writer, "title", Tuple.Create(" title=\"", 5515), Tuple.Create("\"", 5575)
, Tuple.Create(Tuple.Create("", 5523), Tuple.Create<System.Object, System.Int32>(notification.Comment.Text.TruncateWithEllipsis(200)
, 5523), false)
);

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__comment-notification__text\"");

WriteLiteralTo(__razor_helper_writer, ">");

                                                                                                  WriteTo(__razor_helper_writer, CollapseIfNeed(collapse, Html, notification.Comment.Text, 100, renderSimpleMarkdown: true));

WriteLiteralTo(__razor_helper_writer, "</div>\r\n\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__notification__footer\"");

WriteAttributeTo(__razor_helper_writer, "title", Tuple.Create(" title=\"", 5777), Tuple.Create("\"", 5826)
, Tuple.Create(Tuple.Create("", 5785), Tuple.Create<System.Object, System.Int32>(notification.CreateTime.ToPrettyString()
, 5785), false)
);

WriteLiteralTo(__razor_helper_writer, ">");

                                                                                 WriteTo(__razor_helper_writer, notification.CreateTime.ToAgoPrettyString());

WriteLiteralTo(__razor_helper_writer, "</div>\r\n\t\t</div>\r\n\t</div>\r\n");


});

#line default
#line hidden
}
#line default
#line hidden

#line default
#line hidden
public static System.Web.WebPages.HelperResult Notification(PassedManualExerciseCheckingNotification notification, Course course, HtmlHelper Html, UrlHelper Url, bool collapse = true)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {
 
	var slide = (ExerciseSlide)course.GetSlideById(notification.Checking.SlideId);

WriteLiteralTo(__razor_helper_writer, "\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__passed-manual-execise-checking-notification media\"");

WriteLiteralTo(__razor_helper_writer, " data-href=\"");

                                                               WriteTo(__razor_helper_writer, GetSlideUrl(Url, course, slide));

WriteLiteralTo(__razor_helper_writer, "\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"media-left\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n");

WriteLiteralTo(__razor_helper_writer, "\t\t\t");

WriteTo(__razor_helper_writer, UserAvatar.Avatar(notification.InitiatedBy));

WriteLiteralTo(__razor_helper_writer, "\r\n\t\t</div>\r\n\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"media-body\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__notification__header\"");

WriteLiteralTo(__razor_helper_writer, ">");

                               WriteTo(__razor_helper_writer, UserName(notification.InitiatedBy));

WriteLiteralTo(__razor_helper_writer, " проверил");

                                                                            WriteTo(__razor_helper_writer,  notification.InitiatedBy.Gender.ChooseEnding());

WriteLiteralTo(__razor_helper_writer, " ваше решение<br/>по&nbsp;«");

                                                                                                                                                        WriteTo(__razor_helper_writer, slide.Title);

WriteLiteralTo(__razor_helper_writer, "»\r\n\t\t\t</div>\r\n\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__notification__score\"");

WriteLiteralTo(__razor_helper_writer, ">");

                              WriteTo(__razor_helper_writer, notification.Checking.Score);

WriteLiteralTo(__razor_helper_writer, " из ");

                                                              WriteTo(__razor_helper_writer, slide.Exercise.MaxReviewScore.PluralizeInRussian(RussianPluralizationOptions.Score));

WriteLiteralTo(__razor_helper_writer, "</div>\r\n\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__notification__footer\"");

WriteAttributeTo(__razor_helper_writer, "title", Tuple.Create(" title=\"", 6800), Tuple.Create("\"", 6849)
, Tuple.Create(Tuple.Create("", 6808), Tuple.Create<System.Object, System.Int32>(notification.CreateTime.ToPrettyString()
, 6808), false)
);

WriteLiteralTo(__razor_helper_writer, ">");

                                                                                 WriteTo(__razor_helper_writer, notification.CreateTime.ToAgoPrettyString());

WriteLiteralTo(__razor_helper_writer, "</div>\r\n\t\t</div>\r\n\t</div>\r\n");


});

#line default
#line hidden
}
#line default
#line hidden

#line default
#line hidden
public static System.Web.WebPages.HelperResult Notification(PassedManualQuizCheckingNotification notification, Course course, HtmlHelper Html, UrlHelper Url, bool collapse = true)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {
 
	var slide = (QuizSlide)course.GetSlideById(notification.Checking.SlideId);

WriteLiteralTo(__razor_helper_writer, "\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__passed-manual-quiz-checking-notification media\"");

WriteLiteralTo(__razor_helper_writer, " data-href=\"");

                                                            WriteTo(__razor_helper_writer, GetSlideUrl(Url, course, slide));

WriteLiteralTo(__razor_helper_writer, "\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"media-left\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n");

WriteLiteralTo(__razor_helper_writer, "\t\t\t");

WriteTo(__razor_helper_writer, UserAvatar.Avatar(notification.InitiatedBy));

WriteLiteralTo(__razor_helper_writer, "\r\n\t\t</div>\r\n\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"media-body\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__notification__header\"");

WriteLiteralTo(__razor_helper_writer, ">");

                               WriteTo(__razor_helper_writer, UserName(notification.InitiatedBy));

WriteLiteralTo(__razor_helper_writer, " проверил");

                                                                            WriteTo(__razor_helper_writer,  notification.InitiatedBy.Gender.ChooseEnding());

WriteLiteralTo(__razor_helper_writer, " ваш тест<br/>«");

                                                                                                                                            WriteTo(__razor_helper_writer, slide.Title);

WriteLiteralTo(__razor_helper_writer, "»\r\n\t\t\t</div>\r\n\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__notification__score\"");

WriteLiteralTo(__razor_helper_writer, ">");

                              WriteTo(__razor_helper_writer, notification.Checking.Score);

WriteLiteralTo(__razor_helper_writer, " из ");

                                                              WriteTo(__razor_helper_writer, slide.MaxScore.PluralizeInRussian(RussianPluralizationOptions.ScoreDative));

WriteLiteralTo(__razor_helper_writer, "</div>\r\n\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__notification__footer\"");

WriteAttributeTo(__razor_helper_writer, "title", Tuple.Create(" title=\"", 7791), Tuple.Create("\"", 7840)
, Tuple.Create(Tuple.Create("", 7799), Tuple.Create<System.Object, System.Int32>(notification.CreateTime.ToPrettyString()
, 7799), false)
);

WriteLiteralTo(__razor_helper_writer, ">");

                                                                                 WriteTo(__razor_helper_writer, notification.CreateTime.ToAgoPrettyString());

WriteLiteralTo(__razor_helper_writer, "</div>\r\n\t\t</div>\r\n\t</div>\r\n");


});

#line default
#line hidden
}
#line default
#line hidden

#line default
#line hidden
public static System.Web.WebPages.HelperResult Notification(ReceivedCertificateNotification notification, Course course, HtmlHelper Html, UrlHelper Url, bool collapse = true)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {
 

WriteLiteralTo(__razor_helper_writer, "\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__received-certificate-notification media\"");

WriteLiteralTo(__razor_helper_writer, " data-href=\"");

                                                     WriteTo(__razor_helper_writer, Url.RouteUrl("Certificate", new { certificateId = notification.CertificateId }));

WriteLiteralTo(__razor_helper_writer, "\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"media-left\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n");

WriteLiteralTo(__razor_helper_writer, "\t\t\t");

WriteTo(__razor_helper_writer, UserAvatar.Avatar(notification.InitiatedBy));

WriteLiteralTo(__razor_helper_writer, "\r\n\t\t</div>\r\n\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"media-body\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__notification__header\"");

WriteLiteralTo(__razor_helper_writer, ">Поздравляем! Вы получили сертификат по&nbsp;курсу «");

                                                                                  WriteTo(__razor_helper_writer, course.Title);

WriteLiteralTo(__razor_helper_writer, "»</div>\r\n\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__notification__footer\"");

WriteAttributeTo(__razor_helper_writer, "title", Tuple.Create(" title=\"", 8513), Tuple.Create("\"", 8562)
, Tuple.Create(Tuple.Create("", 8521), Tuple.Create<System.Object, System.Int32>(notification.CreateTime.ToPrettyString()
, 8521), false)
);

WriteLiteralTo(__razor_helper_writer, ">");

                                                                                 WriteTo(__razor_helper_writer, notification.CreateTime.ToAgoPrettyString());

WriteLiteralTo(__razor_helper_writer, "</div>\r\n\t\t</div>\r\n\t</div>\r\n");


});

#line default
#line hidden
}
#line default
#line hidden

#line default
#line hidden
public static System.Web.WebPages.HelperResult Notification(ReceivedAdditionalScoreNotification notification, Course course, HtmlHelper Html, UrlHelper Url, bool collapse = true)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {
 
	var unit = course.GetUnitById(notification.Score.UnitId);
	var scoringGroup = unit.Scoring.Groups[notification.Score.ScoringGroupId];

WriteLiteralTo(__razor_helper_writer, "\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__received-additional-score-notification without-link media\"" +
"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"media-left\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n");

WriteLiteralTo(__razor_helper_writer, "\t\t\t");

WriteTo(__razor_helper_writer, UserAvatar.Avatar(notification.InitiatedBy));

WriteLiteralTo(__razor_helper_writer, "\r\n\t\t</div>\r\n\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"media-body\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__notification__header\"");

WriteLiteralTo(__razor_helper_writer, ">");

                               WriteTo(__razor_helper_writer, UserName(notification.InitiatedBy));

WriteLiteralTo(__razor_helper_writer, " поставил");

                                                                            WriteTo(__razor_helper_writer,  notification.InitiatedBy.Gender.ChooseEnding());

WriteLiteralTo(__razor_helper_writer, " вам баллы <b>");

                                                                                                                                           WriteTo(__razor_helper_writer, scoringGroup.Name);

WriteLiteralTo(__razor_helper_writer, "</b> в&nbsp;модуле «");

                                                                                                                                                                                 WriteTo(__razor_helper_writer, unit.Title);

WriteLiteralTo(__razor_helper_writer, "»\r\n\t\t\t</div>\r\n\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__notification__score\"");

WriteLiteralTo(__razor_helper_writer, "><b>");

                                 WriteTo(__razor_helper_writer, notification.Score.Score);

WriteLiteralTo(__razor_helper_writer, " из ");

                                                              WriteTo(__razor_helper_writer, scoringGroup.MaxAdditionalScore.PluralizeInRussian(RussianPluralizationOptions.ScoreDative));

WriteLiteralTo(__razor_helper_writer, "</b></div>\r\n\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__notification__footer\"");

WriteAttributeTo(__razor_helper_writer, "title", Tuple.Create(" title=\"", 9586), Tuple.Create("\"", 9635)
, Tuple.Create(Tuple.Create("", 9594), Tuple.Create<System.Object, System.Int32>(notification.CreateTime.ToPrettyString()
, 9594), false)
);

WriteLiteralTo(__razor_helper_writer, ">");

                                                                                 WriteTo(__razor_helper_writer, notification.CreateTime.ToAgoPrettyString());

WriteLiteralTo(__razor_helper_writer, "</div>\r\n\t\t</div>\r\n\t</div>\r\n");


});

#line default
#line hidden
}
#line default
#line hidden

#line default
#line hidden
public static System.Web.WebPages.HelperResult Notification(JoinedToYourGroupNotification notification, Course course, HtmlHelper Html, UrlHelper Url, bool collapse = true)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {
 

WriteLiteralTo(__razor_helper_writer, "\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__joined-to-your-group-notification media\"");

WriteLiteralTo(__razor_helper_writer, " data-href=\"");

                                                     WriteTo(__razor_helper_writer, Url.Action("Groups", "Admin", new { courseId = notification.CourseId }));

WriteLiteralTo(__razor_helper_writer, "\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"media-left\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n");

WriteLiteralTo(__razor_helper_writer, "\t\t\t");

WriteTo(__razor_helper_writer, UserAvatar.Avatar(notification.JoinedUser));

WriteLiteralTo(__razor_helper_writer, "\r\n\t\t</div>\r\n\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"media-body\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__notification__header\"");

WriteLiteralTo(__razor_helper_writer, ">");

                               WriteTo(__razor_helper_writer, UserName(notification.JoinedUser));

WriteLiteralTo(__razor_helper_writer, " присоедини");

                                                                             WriteTo(__razor_helper_writer,  notification.InitiatedBy.Gender.ChooseEnding("лся", "лась"));

WriteLiteralTo(__razor_helper_writer, " к&nbsp;вашей группе <b>«");

                                                                                                                                                                    WriteTo(__razor_helper_writer, notification.Group.Name);

WriteLiteralTo(__razor_helper_writer, "»</b>\r\n\t\t\t</div>\r\n\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__notification__footer\"");

WriteAttributeTo(__razor_helper_writer, "title", Tuple.Create(" title=\"", 10399), Tuple.Create("\"", 10448)
, Tuple.Create(Tuple.Create("", 10407), Tuple.Create<System.Object, System.Int32>(notification.CreateTime.ToPrettyString()
, 10407), false)
);

WriteLiteralTo(__razor_helper_writer, ">");

                                                                                 WriteTo(__razor_helper_writer, notification.CreateTime.ToAgoPrettyString());

WriteLiteralTo(__razor_helper_writer, "</div>\r\n\t\t</div>\r\n\t</div>\r\n");


});

#line default
#line hidden
}
#line default
#line hidden

#line default
#line hidden
public static System.Web.WebPages.HelperResult Notification(GrantedAccessToGroupNotification notification, Course course, HtmlHelper Html, UrlHelper Url, bool collapse = true)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {
 

WriteLiteralTo(__razor_helper_writer, "\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__granted-access-to-group-notification media\"");

WriteLiteralTo(__razor_helper_writer, " data-href=\"");

                                                        WriteTo(__razor_helper_writer, Url.Action("Groups", "Admin", new { courseId = notification.CourseId }));

WriteLiteralTo(__razor_helper_writer, "\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"media-left\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n");

WriteLiteralTo(__razor_helper_writer, "\t\t\t");

WriteTo(__razor_helper_writer, UserAvatar.Avatar(notification.Access.User));

WriteLiteralTo(__razor_helper_writer, "\r\n\t\t</div>\r\n\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"media-body\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__notification__header\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n");

WriteLiteralTo(__razor_helper_writer, "\t\t\t\t");

WriteTo(__razor_helper_writer, UserName(notification.Access.GrantedBy));

WriteLiteralTo(__razor_helper_writer, " назначил");

                                    WriteTo(__razor_helper_writer, notification.Access.GrantedBy.Gender.ChooseEnding());

WriteLiteralTo(__razor_helper_writer, " вас преподавателем группы <b>«");

                                                                                                                        WriteTo(__razor_helper_writer, notification.Access.Group.Name);

WriteLiteralTo(__razor_helper_writer, "»</b> в&nbsp;курсе «");

                                                                                                                                                                           WriteTo(__razor_helper_writer, course.Title);

WriteLiteralTo(__razor_helper_writer, "».\r\n\t\t\t</div>\r\n\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__notification__footer\"");

WriteAttributeTo(__razor_helper_writer, "title", Tuple.Create(" title=\"", 11263), Tuple.Create("\"", 11312)
, Tuple.Create(Tuple.Create("", 11271), Tuple.Create<System.Object, System.Int32>(notification.CreateTime.ToPrettyString()
, 11271), false)
);

WriteLiteralTo(__razor_helper_writer, ">");

                                                                                 WriteTo(__razor_helper_writer, notification.CreateTime.ToAgoPrettyString());

WriteLiteralTo(__razor_helper_writer, "</div>\r\n\t\t</div>\r\n\t</div>\r\n");


});

#line default
#line hidden
}
#line default
#line hidden

#line default
#line hidden
public static System.Web.WebPages.HelperResult Notification(RevokedAccessToGroupNotification notification, Course course, HtmlHelper Html, UrlHelper Url, bool collapse = true)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {
 

WriteLiteralTo(__razor_helper_writer, "\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__revoked-access-to-group-notification media\"");

WriteLiteralTo(__razor_helper_writer, " data-href=\"");

                                                        WriteTo(__razor_helper_writer, Url.Action("Groups", "Admin", new { courseId = notification.CourseId }));

WriteLiteralTo(__razor_helper_writer, "\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"media-left\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n");

WriteLiteralTo(__razor_helper_writer, "\t\t\t");

WriteTo(__razor_helper_writer, UserAvatar.Avatar(notification.Access.User));

WriteLiteralTo(__razor_helper_writer, "\r\n\t\t</div>\r\n\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"media-body\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__notification__header\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t\t\tВы перестали быть преподавателем группы <b>«");

                              WriteTo(__razor_helper_writer, notification.Access.Group.Name);

WriteLiteralTo(__razor_helper_writer, "»</b> в курсе «");

                                                                            WriteTo(__razor_helper_writer, course.Title);

WriteLiteralTo(__razor_helper_writer, "».\r\n\t\t\t</div>\r\n\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__notification__footer\"");

WriteAttributeTo(__razor_helper_writer, "title", Tuple.Create(" title=\"", 12032), Tuple.Create("\"", 12081)
, Tuple.Create(Tuple.Create("", 12040), Tuple.Create<System.Object, System.Int32>(notification.CreateTime.ToPrettyString()
, 12040), false)
);

WriteLiteralTo(__razor_helper_writer, ">");

                                                                                 WriteTo(__razor_helper_writer, notification.CreateTime.ToAgoPrettyString());

WriteLiteralTo(__razor_helper_writer, "</div>\r\n\t\t</div>\r\n\t</div>\r\n");


});

#line default
#line hidden
}
#line default
#line hidden

#line default
#line hidden
public static System.Web.WebPages.HelperResult Notification(GroupMemberHasBeenRemovedNotification notification, Course course, HtmlHelper Html, UrlHelper Url, bool collapse = true)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {
 

WriteLiteralTo(__razor_helper_writer, "\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__group-member-has-been-removed-notification media\"");

WriteLiteralTo(__razor_helper_writer, " data-href=\"");

                                                              WriteTo(__razor_helper_writer, Url.Action("Groups", "Admin", new { courseId = notification.CourseId }));

WriteLiteralTo(__razor_helper_writer, "\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"media-left\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n");

WriteLiteralTo(__razor_helper_writer, "\t\t\t");

WriteTo(__razor_helper_writer, UserAvatar.Avatar(notification.InitiatedBy));

WriteLiteralTo(__razor_helper_writer, "\r\n\t\t</div>\r\n\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"media-body\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__notification__header\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n");

WriteLiteralTo(__razor_helper_writer, "\t\t\t\t");

WriteTo(__razor_helper_writer, UserName(notification.InitiatedBy));

WriteLiteralTo(__razor_helper_writer, " удалил");

                             WriteTo(__razor_helper_writer, notification.InitiatedBy.Gender.ChooseEnding());

WriteLiteralTo(__razor_helper_writer, " студента ");

                                                                                       WriteTo(__razor_helper_writer, notification.User.VisibleName);

WriteLiteralTo(__razor_helper_writer, " из группы <b>«");

                                                                                                                                    WriteTo(__razor_helper_writer, notification.Group.Name);

WriteLiteralTo(__razor_helper_writer, "»</b> в курсе «");

                                                                                                                                                                           WriteTo(__razor_helper_writer, course.Title);

WriteLiteralTo(__razor_helper_writer, "».\r\n\t\t\t</div>\r\n\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__notification__footer\"");

WriteAttributeTo(__razor_helper_writer, "title", Tuple.Create(" title=\"", 12907), Tuple.Create("\"", 12956)
, Tuple.Create(Tuple.Create("", 12915), Tuple.Create<System.Object, System.Int32>(notification.CreateTime.ToPrettyString()
, 12915), false)
);

WriteLiteralTo(__razor_helper_writer, ">");

                                                                                 WriteTo(__razor_helper_writer, notification.CreateTime.ToAgoPrettyString());

WriteLiteralTo(__razor_helper_writer, "</div>\r\n\t\t</div>\r\n\t</div>\r\n");


});

#line default
#line hidden
}
#line default
#line hidden

#line default
#line hidden
public static System.Web.WebPages.HelperResult Notification(AddedInstructorNotification notification, Course course, HtmlHelper Html, UrlHelper Url, bool collapse = true)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {
 

WriteLiteralTo(__razor_helper_writer, "\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__added-instructor-notification media\"");

WriteLiteralTo(__razor_helper_writer, " data-href=\"");

                                                 WriteTo(__razor_helper_writer, Url.Action("Users", "Admin", new { courseId = notification.CourseId }));

WriteLiteralTo(__razor_helper_writer, "\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"media-left\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n");

WriteLiteralTo(__razor_helper_writer, "\t\t\t");

WriteTo(__razor_helper_writer, UserAvatar.Avatar(notification.AddedUser));

WriteLiteralTo(__razor_helper_writer, "\r\n\t\t</div>\r\n\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"media-body\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__notification__header\"");

WriteLiteralTo(__razor_helper_writer, ">");

                               WriteTo(__razor_helper_writer, UserName(notification.AddedUser));

WriteLiteralTo(__razor_helper_writer, " стал");

                                                                      WriteTo(__razor_helper_writer,  notification.InitiatedBy.Gender.ChooseEnding());

WriteLiteralTo(__razor_helper_writer, " преподавателем курса «");

                                                                                                                                              WriteTo(__razor_helper_writer, course.Title);

WriteLiteralTo(__razor_helper_writer, "»</div>\r\n\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__notification__footer\"");

WriteAttributeTo(__razor_helper_writer, "title", Tuple.Create(" title=\"", 13670), Tuple.Create("\"", 13719)
, Tuple.Create(Tuple.Create("", 13678), Tuple.Create<System.Object, System.Int32>(notification.CreateTime.ToPrettyString()
, 13678), false)
);

WriteLiteralTo(__razor_helper_writer, ">");

                                                                                 WriteTo(__razor_helper_writer, notification.CreateTime.ToAgoPrettyString());

WriteLiteralTo(__razor_helper_writer, "</div>\r\n\t\t</div>\r\n\t</div>\r\n");


});

#line default
#line hidden
}
#line default
#line hidden

#line default
#line hidden
public static System.Web.WebPages.HelperResult Notification(CreatedGroupNotification notification, Course course, HtmlHelper Html, UrlHelper Url, bool collapse = true)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {
 

WriteLiteralTo(__razor_helper_writer, "\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__created-group-notification media\"");

WriteLiteralTo(__razor_helper_writer, " data-href=\"");

                                              WriteTo(__razor_helper_writer, Url.Action("Groups", "Admin", new { courseId = notification.CourseId }));

WriteLiteralTo(__razor_helper_writer, "\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"media-left\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n");

WriteLiteralTo(__razor_helper_writer, "\t\t\t");

WriteTo(__razor_helper_writer, UserAvatar.Avatar(notification.InitiatedBy));

WriteLiteralTo(__razor_helper_writer, "\r\n\t\t</div>\r\n\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"media-body\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__notification__header\"");

WriteLiteralTo(__razor_helper_writer, ">");

                               WriteTo(__razor_helper_writer, UserName(notification.InitiatedBy));

WriteLiteralTo(__razor_helper_writer, " создал");

                                                                          WriteTo(__razor_helper_writer,  notification.InitiatedBy.Gender.ChooseEnding());

WriteLiteralTo(__razor_helper_writer, " группу «");

                                                                                                                                    WriteTo(__razor_helper_writer, notification.Group.Name);

WriteLiteralTo(__razor_helper_writer, "» в&nbsp;курсе «");

                                                                                                                                                                            WriteTo(__razor_helper_writer, course.Title);

WriteLiteralTo(__razor_helper_writer, "»</div>\r\n\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__notification__footer\"");

WriteAttributeTo(__razor_helper_writer, "title", Tuple.Create(" title=\"", 14460), Tuple.Create("\"", 14509)
, Tuple.Create(Tuple.Create("", 14468), Tuple.Create<System.Object, System.Int32>(notification.CreateTime.ToPrettyString()
, 14468), false)
);

WriteLiteralTo(__razor_helper_writer, ">");

                                                                                 WriteTo(__razor_helper_writer, notification.CreateTime.ToAgoPrettyString());

WriteLiteralTo(__razor_helper_writer, "</div>\r\n\t\t</div>\r\n\t</div>\r\n");


});

#line default
#line hidden
}
#line default
#line hidden

#line default
#line hidden
public static System.Web.WebPages.HelperResult Notification(UploadedPackageNotification notification, Course course, HtmlHelper Html, UrlHelper Url, bool collapse = true)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {
 

WriteLiteralTo(__razor_helper_writer, "\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__uploaded-package-notification media\"");

WriteLiteralTo(__razor_helper_writer, " data-href=\"");

                                                 WriteTo(__razor_helper_writer, Url.Action("Packages", "Admin", new { courseId = notification.CourseId }));

WriteLiteralTo(__razor_helper_writer, "\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"media-left\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n");

WriteLiteralTo(__razor_helper_writer, "\t\t\t");

WriteTo(__razor_helper_writer, UserAvatar.Avatar(notification.InitiatedBy));

WriteLiteralTo(__razor_helper_writer, "\r\n\t\t</div>\r\n\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"media-body\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__notification__header\"");

WriteLiteralTo(__razor_helper_writer, ">");

                               WriteTo(__razor_helper_writer, UserName(notification.InitiatedBy));

WriteLiteralTo(__razor_helper_writer, " загрузил");

                                                                            WriteTo(__razor_helper_writer,  notification.InitiatedBy.Gender.ChooseEnding());

WriteLiteralTo(__razor_helper_writer, " новую версию курса «");

                                                                                                                                                  WriteTo(__razor_helper_writer, course.Title);

WriteLiteralTo(__razor_helper_writer, "»</div>\r\n\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__notification__footer\"");

WriteAttributeTo(__razor_helper_writer, "title", Tuple.Create(" title=\"", 15232), Tuple.Create("\"", 15281)
, Tuple.Create(Tuple.Create("", 15240), Tuple.Create<System.Object, System.Int32>(notification.CreateTime.ToPrettyString()
, 15240), false)
);

WriteLiteralTo(__razor_helper_writer, ">");

                                                                                 WriteTo(__razor_helper_writer, notification.CreateTime.ToAgoPrettyString());

WriteLiteralTo(__razor_helper_writer, "</div>\r\n\t\t</div>\r\n\t</div>\r\n");


});

#line default
#line hidden
}
#line default
#line hidden

#line default
#line hidden
public static System.Web.WebPages.HelperResult Notification(PublishedPackageNotification notification, Course course, HtmlHelper Html, UrlHelper Url, bool collapse = true)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {
 

WriteLiteralTo(__razor_helper_writer, "\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__published-package-notification media\"");

WriteLiteralTo(__razor_helper_writer, " data-href=\"");

                                                  WriteTo(__razor_helper_writer, Url.Action("Packages", "Admin", new { courseId = notification.CourseId }));

WriteLiteralTo(__razor_helper_writer, "\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"media-left\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n");

WriteLiteralTo(__razor_helper_writer, "\t\t\t");

WriteTo(__razor_helper_writer, UserAvatar.Avatar(notification.InitiatedBy));

WriteLiteralTo(__razor_helper_writer, "\r\n\t\t</div>\r\n\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"media-body\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__notification__header\"");

WriteLiteralTo(__razor_helper_writer, ">");

                               WriteTo(__razor_helper_writer, UserName(notification.InitiatedBy));

WriteLiteralTo(__razor_helper_writer, " опубликовал");

                                                                               WriteTo(__razor_helper_writer,  notification.InitiatedBy.Gender.ChooseEnding());

WriteLiteralTo(__razor_helper_writer, " новую версию курса «");

                                                                                                                                                     WriteTo(__razor_helper_writer, course.Title);

WriteLiteralTo(__razor_helper_writer, "»</div>\r\n\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__notification__footer\"");

WriteAttributeTo(__razor_helper_writer, "title", Tuple.Create(" title=\"", 16009), Tuple.Create("\"", 16058)
, Tuple.Create(Tuple.Create("", 16017), Tuple.Create<System.Object, System.Int32>(notification.CreateTime.ToPrettyString()
, 16017), false)
);

WriteLiteralTo(__razor_helper_writer, ">");

                                                                                 WriteTo(__razor_helper_writer, notification.CreateTime.ToAgoPrettyString());

WriteLiteralTo(__razor_helper_writer, "</div>\r\n\t\t</div>\r\n\t</div>\r\n");


});

#line default
#line hidden
}
#line default
#line hidden

#line default
#line hidden
public static System.Web.WebPages.HelperResult Notification(CourseExportedToStepikNotification notification, Course course, HtmlHelper Html, UrlHelper Url, bool collapse = true)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {
 

WriteLiteralTo(__razor_helper_writer, "\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__course-exported-to-stepik-notification media\"");

WriteLiteralTo(__razor_helper_writer, " data-href=\"");

                                                          WriteTo(__razor_helper_writer, Url.Action("Process", "Stepik", new { courseId = course.Id, processId = notification.ProcessId }));

WriteLiteralTo(__razor_helper_writer, "\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"media-left\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n");

WriteLiteralTo(__razor_helper_writer, "\t\t\t");

WriteTo(__razor_helper_writer, UserAvatar.Avatar(notification.InitiatedBy));

WriteLiteralTo(__razor_helper_writer, "\r\n\t\t</div>\r\n\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"media-body\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n");

			
             if (notification.Process.IsSuccess)
			{

WriteLiteralTo(__razor_helper_writer, "\t\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__notification__header\"");

WriteLiteralTo(__razor_helper_writer, ">Курс <b>«");

                                            WriteTo(__razor_helper_writer, course.Title);

WriteLiteralTo(__razor_helper_writer, "»</b> успешно экспортирован на&nbsp;Степик. Нажмите для&nbsp;подробностей.</div>\r" +
"\n");

			}
			else
			{

WriteLiteralTo(__razor_helper_writer, "\t\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__notification__header\"");

WriteLiteralTo(__razor_helper_writer, ">Произошла ошибка при копировании курса <b>«");

                                                                              WriteTo(__razor_helper_writer, course.Title);

WriteLiteralTo(__razor_helper_writer, "»</b> на&nbsp;Степик. Нажмите для&nbsp;подробностей.</div>\r\n");

			}

WriteLiteralTo(__razor_helper_writer, "\t\t\t<div");

WriteLiteralTo(__razor_helper_writer, " class=\"notifications__notification__footer\"");

WriteAttributeTo(__razor_helper_writer, "title", Tuple.Create(" title=\"", 17032), Tuple.Create("\"", 17081)
, Tuple.Create(Tuple.Create("", 17040), Tuple.Create<System.Object, System.Int32>(notification.CreateTime.ToPrettyString()
, 17040), false)
);

WriteLiteralTo(__razor_helper_writer, ">");

                                                                                 WriteTo(__razor_helper_writer, notification.CreateTime.ToAgoPrettyString());

WriteLiteralTo(__razor_helper_writer, "</div>\r\n\t\t</div>\r\n\t</div>\r\n");


});

#line default
#line hidden
}
#line default
#line hidden

    }
}
#pragma warning restore 1591
