#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uLearn.Web.Views.SlideNavigation
{
    using System;
    using System.Collections.Generic;
    
    #line 3 "..\..\Views\SlideNavigation\TableOfContents.cshtml"
    using System.Globalization;
    
    #line default
    #line hidden
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 4 "..\..\Views\SlideNavigation\TableOfContents.cshtml"
    using uLearn;
    
    #line default
    #line hidden
    
    #line 6 "..\..\Views\SlideNavigation\TableOfContents.cshtml"
    using uLearn.Web.Models;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Views\SlideNavigation\TableOfContents.cshtml"
    using uLearn.Web.Views.Course;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public static class TableOfContents
    {

public static System.Web.WebPages.HelperResult Toc(TocModel toc)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 39 "..\..\Views\SlideNavigation\TableOfContents.cshtml"
 

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\t<ul class=\"nav\">\r\n\t\t<li class=\"units-list-item full-width units-list-item-text c" +
"ourse-name\"><a data-score=\"");



#line 41 "..\..\Views\SlideNavigation\TableOfContents.cshtml"
                                              WebViewPage.WriteTo(@__razor_helper_writer, SlideHtml.Score(toc.Score, toc.MaxScore));

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\">");



#line 41 "..\..\Views\SlideNavigation\TableOfContents.cshtml"
                                                                                         WebViewPage.WriteTo(@__razor_helper_writer, toc.Course.Title);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</a></li>\r\n");



#line 42 "..\..\Views\SlideNavigation\TableOfContents.cshtml"
  		
			int iUnit = 0;
			foreach (var unit in toc.Units)
			{
				
#line default
#line hidden


#line 46 "..\..\Views\SlideNavigation\TableOfContents.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, TocUnit(unit, iUnit));

#line default
#line hidden


#line 46 "..\..\Views\SlideNavigation\TableOfContents.cshtml"
                         
				iUnit++;
			}
		

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\t</ul>\r\n");



#line 51 "..\..\Views\SlideNavigation\TableOfContents.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult TocUnit(TocUnitModel unit, int index)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 53 "..\..\Views\SlideNavigation\TableOfContents.cshtml"
 
	var collapseOption = unit.IsCurrent ? "collapse in" : "collapse";

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\t<li class=\"units-list-item full-width\">\r\n\t\t<a data-toggle=\"collapse\" href=");



#line 56 "..\..\Views\SlideNavigation\TableOfContents.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, "#N" + index);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, " class=\"units-list-item-text\" data-score=\"");



#line 56 "..\..\Views\SlideNavigation\TableOfContents.cshtml"
                                               WebViewPage.WriteTo(@__razor_helper_writer, SlideHtml.Score(unit.Score, unit.MaxScore));

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\">");



#line 56 "..\..\Views\SlideNavigation\TableOfContents.cshtml"
                                                                                            WebViewPage.WriteTo(@__razor_helper_writer, unit.UnitName);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</a>\r\n\t\t<ul id=");



#line 57 "..\..\Views\SlideNavigation\TableOfContents.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, "N" + index);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, " class=\"slides-list ");



#line 57 "..\..\Views\SlideNavigation\TableOfContents.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, collapseOption);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\">\r\n");



#line 58 "..\..\Views\SlideNavigation\TableOfContents.cshtml"
 			foreach (var page in unit.Pages)
			{
				
#line default
#line hidden


#line 60 "..\..\Views\SlideNavigation\TableOfContents.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, TocItem(page));

#line default
#line hidden


#line 60 "..\..\Views\SlideNavigation\TableOfContents.cshtml"
                  
			}

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\t\t</ul>\r\n\t</li>\r\n");



#line 64 "..\..\Views\SlideNavigation\TableOfContents.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult TocItem(TocPageInfo page)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 69 "..\..\Views\SlideNavigation\TableOfContents.cshtml"
 

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\t<li class=\"slide-list-item ");



#line 70 "..\..\Views\SlideNavigation\TableOfContents.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, page.IsCurrent ? "selected" : "");

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, " full-size\" onclick=\"window.location.href=\'");



#line 70 "..\..\Views\SlideNavigation\TableOfContents.cshtml"
                                                               WebViewPage.WriteTo(@__razor_helper_writer, page.Url);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\'\">\r\n\t\t<i class=\"");



#line 71 "..\..\Views\SlideNavigation\TableOfContents.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, GetPageIconClass(page));

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, " navbar-label\" title=\"");



#line 71 "..\..\Views\SlideNavigation\TableOfContents.cshtml"
              WebViewPage.WriteTo(@__razor_helper_writer, GetTocPageTytle(page.PageType));

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\"></i>\r\n\t\t<a href=\"");



#line 72 "..\..\Views\SlideNavigation\TableOfContents.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, page.Url);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\" style=\"margin-right: 5px\">");



#line 72 "..\..\Views\SlideNavigation\TableOfContents.cshtml"
     WebViewPage.WriteTo(@__razor_helper_writer, page.Name);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</a>\r\n\t\t<span class=\"score right\">");



#line 73 "..\..\Views\SlideNavigation\TableOfContents.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, SlideHtml.Score(page.Score, page.MaxScore));

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</span>\r\n\t</li>\r\n");



#line 75 "..\..\Views\SlideNavigation\TableOfContents.cshtml"

#line default
#line hidden

});

}


        #line 78 "..\..\Views\SlideNavigation\TableOfContents.cshtml"


	private static string GetTocPageTytle(TocPageType pageType)
	{
		if (pageType == TocPageType.Theory) return "Теория";
		if (pageType == TocPageType.Exercise) return "Задача";
		if (pageType == TocPageType.Quiz) return "Тест";
		return "";
	}


        #line default
        #line hidden

public static System.Web.WebPages.HelperResult GetPageIconClass(TocPageInfo page)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 91 "..\..\Views\SlideNavigation\TableOfContents.cshtml"
 
	string progressClass;
	string typeClass;
	if (page.PageType == TocPageType.InstructorNotes || page.PageType == TocPageType.Statistics)
	{
		typeClass = "glyphicon-eye-close";
		progressClass = "navbar-label-privileged";
	}
	else
	{
		var isComplete = !page.ShouldBeSolved || page.IsSolved;
		progressClass = isComplete ? "navbar-label-success"
			: (page.IsVisited ? "navbar-label-danger" : "navbar-label-default");
		typeClass = page.PageType == TocPageType.Quiz ? "glyphicon-pushpin"
			: page.PageType == TocPageType.Exercise ? (isComplete ? "glyphicon-check" : "glyphicon-edit")
				: (page.IsVisited ? "glyphicon-ok" : "glyphicon-none");
	}
	
#line default
#line hidden


#line 108 "..\..\Views\SlideNavigation\TableOfContents.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, progressClass + " glyphicon " + typeClass);

#line default
#line hidden


#line 108 "..\..\Views\SlideNavigation\TableOfContents.cshtml"
                                             

#line default
#line hidden

});

}


    }
}
#pragma warning restore 1591
