
//automatically generated by Tuto
using uLearn;
namespace AIML 
{
    [Slide(@"Пример отошений и отображений","411381a8-7a2e-4e98-9877-b9a79335aaca")]
    public class Пример_отошений_и_отображений
        {
		//#video z06p6mhHmgI
		/*
		[Презентация](_S04-slides.pdf)
		*/

        }
}