
//automatically generated by Tuto
using uLearn;
namespace UXR 
{
    [Slide(@"Примеры вопросов для интервью","df571adb-9510-402b-9db8-50335fc105a6")]
    public class Примеры_вопросов_для_интервью
        {
		//#video ChQraXCg2EA

        }
}