
//automatically generated by Tuto
using uLearn;
namespace AIML 
{
    [Slide(@"Задача распознавания","6561540a-b843-4479-aa00-e0636c3555d2")]
    public class Задача_распознавания
        {
		//#video FF2JNqSb6vY

        }
}