
//automatically generated by Tuto
using uLearn;
namespace AIML 
{
    [Slide(@"Управление на нечеткой логике","1c297519-b61c-428f-8cf5-1106b31fa3b1")]
    public class Управление_на_нечеткой_логике
        {
		//#video 1hZ7hYSMBok
		/*
		[Презентация](_S04-slides.pdf)
		*/

        }
}