
//automatically generated by Tuto
using uLearn;
namespace AIML 
{
    [Slide(@"Вывод таблиц истинности","970c5f1d-fe2e-41c6-bf6a-e0303062e6d0")]
    public class Вывод_таблиц_истинности
        {
		//#video sBfCurmNtf8
		/*
		[Презентация](_S04-slides.pdf)
		*/

        }
}