
//automatically generated by Tuto
using uLearn;
namespace AIML 
{
    [Slide(@"Правило резолюций","3c4eccf9-72b0-437a-afdb-e1e557f3a4bc")]
    public class Правило_резолюций
        {
		//#video o_bN8sYkOng

        }
}