
//automatically generated by Tuto
using uLearn;
namespace AIML 
{
    [Slide(@"Развитие логических систем","03d7ad70-7c72-4ba9-8ebd-33a1c379c451")]
    public class Развитие_логических_систем
        {
		//#video 6dzvMKcGLyw
		/*
		[Презентация](_S00-slides.pdf)
		*/

        }
}