
//automatically generated by Tuto
using uLearn;
namespace AIML 
{
    [Slide(@"Нечеткие логические связки","92fb8f83-d8d7-47f6-9e2b-3534c11c77d5")]
    public class Нечеткие_логические_связки
        {
		//#video sUrdCzjTSas
		/*
		[Презентация](_S01-slides.pdf)
		*/

        }
}