
//automatically generated by Tuto
using uLearn;
namespace AIML 
{
    [Slide(@"Нечеткие множества","c539c54a-65ee-4367-b48b-fd3cf6f82322")]
    public class Нечеткие_множества
        {
		//#video M3W8I25ilwo
		/*
		[Презентация](_S02-slides.pdf)
		*/

        }
}